### ISSUE TITLE
Linux From Scratch

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#100]
Support Linux From Scratch (LFS)

see  http://www.linuxfromscratch.org/

**Comment by akesandgren** [comment]
@boegel status?

**Comment by boegel** [comment]
Well, we have easyconfigs for `glibc` now, see https://github.com/easybuilders/easybuild-easyconfigs/tree/master/easybuild/easyconfigs/g/glibc .

This issue was opened as a joke originally (it's not a coincidence it's issue `#100`), but I guess we did it... :)

**Comment by fgeorgatos** [comment]
`<necroposting mode on>`

@azet you were asking back then about who will be doing `glibc`. Here's an idea!
* https://www.freelists.org/post/bootstrappable/GNU-Mes-024-released
