### ISSUE TITLE
add support for Lmod

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#110]
_lmod_ is an alternative to environment modules (which has it's problems, e.g. the `modulecmd` segfault issue, or the way in which dependencies are handled)

We should add support for lmod to EasyBuild, without destroying the support for environment modules.

see http://www.tacc.utexas.edu/tacc-projects/mclay/lmod

**Comment by fgeorgatos** [comment]
This should be closed, no? 
sometimes we forget to acknowledge really important stuff ;-)

**Comment by fgeorgatos** [comment]
@boegel:
 - what is pending to consider this one done?! (any TODO list?)

**Comment by boegel** [comment]
Closing this, we can follow up on family/properties support in #1257...
