### ISSUE TITLE
add support for specifying alternative download methods

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#112]
(old internal ticket 317)

We need to be able to also specify alternative ways of downloading sources, e.g. checking out from a CVS/SVN/git/hg repository.

This is required for e.g. MTL4 (see issue #111), CP2K, ...

**Comment by akesandgren** [comment]
Cf, https://github.com/easybuilders/easybuild-framework/pull/2555

**Comment by boegel** [comment]
I'll go ahead and close this, since we have support for cloning a `git` repo.

Also supporting other methods like SVN can be done equivalently.
