### ISSUE TITLE
Bug: line number for errors in easyconfigs

### ISSUE THREAD

**Issue by gjbex** [easybuilders/easybuild-framework#1149]
When a syntax error occurs in an easyconfig, the line number on which the error occurs is reported, which is nice.

However, when the easyconfig starts with comment lines, the error is reported counting from the end of the comments, not the start of the easyconfig file.

**Comment by Micket** [comment]
Testing this out with an easyconfig with some comments and an intentional error, I'm directed to the correct line number, so it seems this has been resolved.
