### ISSUE TITLE
complete wiki page on code style

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#116]
The wiki page on [[Code style]] should explain our code style policy, i.e. PEP008 based with some exceptions (e.g. class names for easyblocks, cfg [[Encode class names]]).

It should make clear that the intention of the code style is too keep the management of the EasyBuild code base, with contributors from multiple sites, maintainable.

**Comment by akesandgren** [comment]
@boegel Is this still valid? It's in the ASAP milestone...

**Comment by boegel** [comment]
OK to close because of https://easybuild.readthedocs.io/en/latest/Code_style.html
