### ISSUE TITLE
update development guide wiki page

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#117]
The wiki page [[Development guide]] needs a thorough update after all the changes made in v0.9 (cfg. #99).

It also needs to be extended, outlining some guidelines to e.g. implement a new easyblock (+ example easyconfig), or make adjustments to the EasyBuild framework or tools.

**Comment by akesandgren** [comment]
@boegel Same one here... still valid? It's in the ASAP milestone.

**Comment by boegel** [comment]
Obviously the ASAP milestone doesn't make much sense... :)

We have documentation on implementing easyblock, see https://easybuild.readthedocs.io/en/latest/Implementing-easyblocks.html .

Not sure trying to add documentation on how to make changes to the framework makes sense, it would be quite hard to come up with something general I guess, and nobody has really asked for that either... So, closing.
