### ISSUE TITLE
Bad install on Fedora 21 VM

### ISSUE THREAD

**Issue by juanotto** [easybuilders/easybuild-framework#1172]
I'm trying to run easybuild in a Fedora 21 VM (virtualbox) running on Mac OS. The installation seems to be right as bootstrap_eb.py's messages are positive:

```
[...]
== COMPLETED: Installation ended successfully
== Results of the build can be found in the log file /home/juan/.local/easybuild/software/EasyBuild/1.16.1/easybuild/easybuild-EasyBuild-1.16.1-20150212.132121.log
```

but still doesn't seem to be working (no luck with "Typical workflow examples" yet). The info of my installation:

```
$ python -V
Python 2.7.8
```

```
$ type module
module is a function
module () 
{ 
    eval `/usr/bin/modulecmd bash $*`
}
```

```
$ type -f module
bash: type: module: not found
```

```
$ module --version
VERSION=3.2.10
DATE=2012-12-21

AUTOLOADPATH=undef
BASEPREFIX="/usr/share"
BEGINENV=99
CACHE_AVAIL=undef
DEF_COLLATE_BY_NUMBER=undef
DOT_EXT=""
EVAL_ALIAS=1
HAS_BOURNE_FUNCS=1
HAS_BOURNE_ALIAS=1
HAS_TCLXLIBS=undef
HAS_X11LIBS=1
LMSPLIT_SIZE=1000
MODULEPATH="/etc/modulefiles:/usr/share/modulefiles"
MODULES_INIT_DIR="/usr/share/Modules/init"
PREFIX="/usr/share/Modules"
TCL_VERSION="8.6"
TCL_PATCH_LEVEL="8.6.1"
TMP_DIR="/tmp"
USE_FREE=undef
VERSION_MAGIC=1
VERSIONPATH=undef
WANTS_VERSIONING=0
WITH_DEBUG_INFO=undef
```

```
$ module av EasyBuild

------------------------------------------------------------------------ /home/juan/.local/easybuild/modules/all -------------------------------------------------------------------------
EasyBuild/1.16.1
```

```
$ which -a eb
~/.local/easybuild/software/EasyBuild/1.16.1/bin/eb
```

```
$ eb --version
This is EasyBuild 1.16.1 (framework: 1.16.1, easyblocks: 1.16.1) on host localhost.localdomain.
```

I tried to run the tests but I get some errors till it goes in an infinite error loop. I cancelled the tests before that to get the following:

```
$ python -m test.framework.suite
WARNING: xmlrunner module not available, falling back to using unittest...

.....err: 'EasyBuild crashed with an error (at easybuild/software/EasyBuild/1.16.1/lib/python2.7/site-packages/easybuild_framework-1.16.1-py2.7.egg/easybuild/main.py:138 in build_and_install_software): Build of /home/juan/.local/easybuild/software/EasyBuild/1.16.1/lib/python2.7/site-packages/easybuild_framework-1.16.1-py2.7.egg/test/framework/easyconfigs/toy-0.0.eb failed (err: \'build failed (first 300 chars): EasyBuild crashed with an error (at easybuild/software/EasyBuild/1.16.1/lib/python2.7/site-packages/easybuild_framework-1.16.1-py2.7.egg/easybuild/tools/run.py:382 in parse_cmd_output): cmd "patch -b -p2 -i /home/juan/.local/easybuild/software/EasyBuild/1.16.1/lib/python2.7/site-packages/easybuild_f\')'
F.......E.err: You need a password or an OAuth token to authenticate as easybuild_test
F.........err: 'EasyBuild crashed with an error (at easybuild/software/EasyBuild/1.16.1/lib/python2.7/site-packages/easybuild_framework-1.16.1-py2.7.egg/easybuild/main.py:138 in build_and_install_software): Build of /home/juan/.local/easybuild/software/EasyBuild/1.16.1/lib/python2.7/site-packages/easybuild_framework-1.16.1-py2.7.egg/test/framework/easyconfigs/toy-0.0-deps.eb failed (err: \'build failed (first 300 chars): EasyBuild crashed with an error (at easybuild/software/EasyBuild/1.16.1/lib/python2.7/site-packages/easybuild_framework-1.16.1-py2.7.egg/easybuild/tools/run.py:382 in parse_cmd_output): cmd "patch -b -p2 -i /home/juan/.local/easybuild/software/EasyBuild/1.16.1/lib/python2.7/site-packages/easybuild_f\')'
```

Did I miss some configuration or requirement?

**Comment by boegel** [comment]
How exactly is it not working for you? What error messages are you getting when you're trying to build/install GCC, or some more simple like `bzip2` using the system compiler (which we do not recommend, but it's a good first test, i.e. `eb bzip2-1.0.6.eb`)?

Can you provide us with a full debug (that is, using the `--debug` or `-d` command line option) log file for a failing run? You can use http://gist.github.com to share it.

Since the bootstrap procedure worked, EasyBuild *is* working, since part of the bootstrap is to install EasyBuild with EasyBuild; that's how you obtain the module `EasyBuild/1.16.1`.

The unit tests need work to make them more robust to be reliable, but this is the first time I hear somebody mentioning that they go into an infinite loop... Is that really the case? Running all of the tests takes quite a while, e.g. 20-30min is not unlikely.

By default, EasyBuild uses `$HOME/.local/easybuild` as a prefix, which may not be what you want. See http://easybuild.readthedocs.org/en/latest/Configuration.html on configuring EasyBuild differently, in particular http://easybuild.readthedocs.org/en/latest/Configuration.html#mandatory-configuration-settings .

**Comment by juanotto** [comment]
Hi Boegel, thanks for the response. On the one hand I piped the tests outputs to have more info on that. It seems to be complaining about the space but its a fresh VM install with 32 Gb assigned, so should not be the problem (maybe my distro is limiting the /tmp space used by the tests?)
```
Logged from file templates.py, line 186
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 883, in emit
    self.flush()
  File "/usr/lib64/python2.7/logging/__init__.py", line 843, in flush
    self.stream.flush()
IOError: [Errno 28] No space left on device
Logged from file templates.py, line 186
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 883, in emit
    self.flush()
  File "/usr/lib64/python2.7/logging/__init__.py", line 843, in flush
    self.stream.flush()
IOError: [Errno 28] No space left on device
[...and so on for Mbs and Mbs till I kill it]
```
On the other hand I installed bzip2 without problem (module load + which work ok) With bzip2-1.0.6-GCC-4.8.1.eb instead, it complains about not finding a module for the toolchain GCC. Should I install the GCC toolchain before using it? The param --robot enables dependencies resolution but it seems to be have problems to untar mpc-1.0.1.tar.gz, Should it be doing tar xf instead of tar xzf?

The complete log is inhttps://gist.github.com/juanotto/e73a3a9c7f7260628d00#file-eb-d-bzip2-1-0-6-gcc-4-8-1-eb-robot-logfile

**Comment by juanotto** [comment]
Some updates on this.

The error seems to be the untar of mpc-1.0.1.tar.gz as the "tar xzf mpc-1.0.1.tar.gz" fails. The problem is that the file is not compressed anymore when eb reaches that point ("tar xf mpc-1.0.1.tar.gz" works perfect) I tried to reproduce the download/untar process using wget in the command line and got the same problem. The http headers says the length is 624125 but the size in disk is far bigger so: something is uncompressing my files and I didn't know it!

I repeated the same in a CentOS VM and I got the same. Then I did it in Mac OS and it worked perfect: the file is still compressed so tar xzf works as expected. So it should be some configuration but I don't know where to look yet.

Lastly, what I noticed is that eb had no problem with mpfr-3.1.2.tar.gz and started checking that. The difference I found is that this has Content-Type: application/x-gzip and mpc-1.0.1.tar.gz has Content-Type: application/x-tar... I'll be checking how Fedora and CentOS handle that...

**Comment by juanotto** [comment]
I just gziped the file in place hoping that it wont download again and replace the file and seems to be working (it has being building for ~15min now)

Do the guys of www.multiprecision.org have a bad config in their server? Maybe they have a .htaccess overriding the MIME type for mpc-1.0.1.tar.gz?

**Comment by Micket** [comment]
This is long since outdated. I hope the build worked, and/or that you updated to fedora 39 at this point :)
