### ISSUE TITLE
Please rename the `dummy` toolchain

### ISSUE THREAD

**Issue by riccardomurri** [easybuilders/easybuild-framework#1181]
I understand that `dummy` is a sensible name from the programmers' point of view: if one is conversant with the way EasyBuild works, it just translates to "do not build any tool, just use what's available".

However, for newcomers and "simple" users `dummy` is kind of misleading, as it suggests no-op or a "fake" toolchain.

May I suggest that it be renamed to "system" (use system tools/compilers) or "os"?

**Comment by boegel** [comment]
I feel that's a valid request, but we'll need to phase out the `dummy` name, rather than kill it hard.

We can deprecate `dummy`, and drop support for it in EasyBuild v3.0 all together.

@stdweird: thoughts?

**Comment by malcook** [comment]
FWIW: +1 - good idea - was a bit baffling to me too - of course it is
documented somewhere - I myself briefly had the thought that it might be
called 'base' or 'host' when I came to understand its purpose.  The word
"vendor" also came to mind, but only briefly.  A minor change I know but
one that might lend a little superficial maturity to the project.

~ Malcolm Cook
h: 913.642.5257
m: 913.226.1542
w: 816.926.4449

**Comment by stdweird** [comment]
to be clear, 'dummy' never meant 'use system tools'. it's a different discussion, but it might as well get cleaned up together.

2 usecases exists: 
'dummy' / 'noop' : simply unpack the sources, no compilation required
'dummy' / 'system': use the system compiler, not a full EB controlled toolchain  (can be system/OS, or vendor provided,...)

noop should stay the same obscure code path as dummy today :smile: 
for system, there should be a valid system toolchain.

**Comment by pforai** [comment]
+1 for renaming the dummy TC to something more sensible. Or clarify what exactly the dummy is, how it works and what the use case is.  There is some general knowledge among EBers how and when to use dummy. Mostly it boils down to use dummy for "TC independent"  (the EB way is to roll everything from EB and have reproducible builds and all nice things we have when rolling the EB way) builds.

According to https://github.com/hpcugent/easybuild-framework/blob/master/easybuild/toolchains/compiler/dummycompiler.py#L40 
it should _not_ even try to use a system GCC. But it certainly does that.

**Comment by boegel** [comment]
@pforai: no, it doesn't, EasyBuild even sets `$CC` to `dummy` in the environment

to actually build stuff when using a `dummy` toolchain, you need to use `prebuildopts = "CC=gcc"` to get around that

**Comment by pforai** [comment]
@boegel  You are right in the sense that EB will not try to pickup the system's compiler ... and it goes as far as EB can do (without bailing on building).

If the config part of the build can pickup a compiler then it will go ahead and build with that compiler. Some Makefiles and build systems have defaults set for CC (for example setting CC to cc as POSIX wants it) and friends and depending on the underlying system and as such building will work with whatever is in the environment. Out of practice in most cases dummy will just works (depending on system config and other things).

This yields a lot of implicit behaviour and we're left to the mercy of scientific software developers  which we all know all too well isn't what we want.

It is difficult to capture these semantics in a name for a toolchain, but somehow I'm not really satisfied with dummy either.

**Comment by boegel** [comment]
deprecation of `dummy` toolchain implemented in #1233 (WIP, but close to being complete)

**Comment by boegel** [comment]
done in #2877, which will be included in EasyBuild v4.0
