### ISSUE TITLE
promote EasyBuild

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#120]
(old internal ticket 9)

**(note: keep this overview up-to-date by editing this issue, and mention new promo-actions as a reply)**

Promote EasyBuild on suitable venues:
### conferences/magazines:
- [x] [HEPIX spring workshop 2012](https://indico.cern.ch/contributionDisplay.py?sessionId=3&contribId=39&confId=160737) (@JensTimmerman)
- [x] Supercomputing 2012 (@boegel, @JensTimmerman) [(see notes)](https://github.com/hpcugent/easybuild/wiki/Notes-on-EasyBuild-promotion-at-Supercomputing%272012)
  - paper at PyHPC-2012 (@ SC'12) (available [here](http://hpcugent.github.com/easybuild/files/easybuild-PyHPC-SC12_paper.pdf))
  - BoF session @ SC12 (not accepted) (but we did join in on Python for HPC and Small Clusters BoFs during SC12)
  - walk exhibit floor with EasyBuild business cards, talk to sysadmins of big sites [(see notes)](https://github.com/hpcugent/easybuild/wiki/Notes-on-EasyBuild-promotion-at-Supercomputing%272012)
- [ ] try and get an article in HPC-admin magazine, see e.g. [article on modules](http://hpc.admin-magazine.com/Articles/Environment-Modules) (talked to editor @ SC'12, he would mention EasyBuild to the writers)
### websites:
- [x] [EasyBuild webpage](http://hpcugent.github.com/easybuild/)
- [ ] Wikipedia : add http://en.wikipedia.org/wiki/EasyBuild
- [ ] http://openscience.org/
- [ ] Intel documentation on building HPC software (e.g. see [here](http://software.intel.com/en-us/articles/build-cp2k-using-intel-fortran-compiler-professional-edition/)), contact people setting this up (e.g. http://software.intel.com/en-us/blackbelt)
- [ ] [HPC Advisory Network of Expertise](http://www.hpcadvisorycouncil.com/subgroups_hpc_works.php)
- [ ] [Scipy](http://scipy.github.com/install.html) once we support it (see https://github.com/hpcugent/easybuild-easyconfigs/issues/35) 
- [ ] http://www.rescale.com/
#### software-specific
- DOLFIN:
- [ ] [stackoverflow question](http://stackoverflow.com/questions/11065082/how-can-i-get-fenics-working-in-ubuntu-12-04-with-epd-python) on building fenics/dolfin
- [x] let the guy who wrote [dorsal](http://code.google.com/p/dorsal/) know about EasyBuild
#### other
- [x] order EasyBuild business cards
- [x] order EasyBuild stickers
- [ ] promote EasyBuild in bioinformatics community (@fgeorgatos)
- [ ] [begrid](http://www.begrid.be/index.php?module=webpage&id=28)

**Comment by rjeschmi** [comment]
showterm.io is a nice tool for capturing the use of EB in an animated way.
It can then be embedded onto web pages, etc.

I'll upload an interesting example here in a bit :)

**Comment by boegel** [comment]
I'll close this, no need to have an issue open for this, we already actively promote EasyBuild whenever we get the chance...
