### ISSUE TITLE
support Python 3.x

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#133]
(old internal ticket 231)

We should try and make sure EasyBuild runs (correctly) with Python v3.x.

Supporting Python 2.4 -> 3.2 can be done in a single code base.

For example handling the changed named Exception syntax can be made to work in both 2.4 and 3.1 by using

```
try:
  #something
except SomeException:
  ex = sys.exc_info()
  #handle exception
```

**Comment by JensTimmerman** [comment]
@vsoch we would follow this guide: https://portingguide.readthedocs.io/en/latest/process.html
the dropping python2.4 and python2.5 part has already been done. We are contemplating dropping 2.6 but that's not really needed.

Our idea was to have a single codebase that supports both python2 and 3, having 2 releases with py2to3 seems brittle and cumbersome, especially if you target to eventually switch to python3 only.

First part is to have our dependencies supporting python 3
that would be: vsc-install, vsc-base and optionally
 'coloredlogs', and  'humanfriendly'

Our team (HPC UGent) also develops vsc-install and vsc-base and we certainly would not mind getting some test branches with python3 support.
We can start with extra tests that are running all code trough python modernize and run the tests for the generated code with both python2 and python3.
Once these tests are in place we can mandate that all new code should at least work for these tests, and then start updating module by module to make all code python2 and python3 compatible. 

vsc-install and vsc-base are transitioned this way we can start doing the same for easybuild.

This has been on our plan for a few years now, but we feel no real pressure in our team to take on this task already, python2 will be supported by RedHat and CentOS for a few years to come, and we have limited python coding resources.

Are you up for this task?

**Comment by vsoch** [comment]
Definitely! Would you like help with the dependency libraries or should I hold tight and start contribution for just easy build? If you can point me to the right places (links) I would be happy to take a shot at the first task too.

**Comment by boegel** [comment]
@vsoch There's little point on starting to point EasyBuild when `vsc-base` hasn't been ported...

We need `vsc-install` too, but currently only for running the tests (and if we need to we can probably get around that fairly easily, since I suspect it won't be that easy to port `vsc-install`).

So, if you would like to contribute: `vsc-base` is definitely a good place to start, see https://github.com/hpcugent/vsc-base.

The main modules we use there are:

* `vsc.utils.generaloption`
* `vsc.utils.fancylogger`
* `vsc.utils.missing`
* `vsc.utils.rest`
* `vsc.utils.affinity`
* ` vsc.utils.patterns`
* `vsc.utils.wrapper`

**Comment by boegel** [comment]
@vsoch This may be helpful, to get an idea what you're getting into... https://github.com/hpcugent/vsc-base/pull/142

**Comment by boegel** [comment]
Some progress on this, thanks to @vsoch:

* PR to add support for running `vsc-base` on top of Python 3.x: https://github.com/hpcugent/vsc-base/pull/258
  * which, in turn, requires `vsc-install` to be compatible with Python 3.x: https://github.com/hpcugent/vsc-install/pull/83

**Comment by boegel** [comment]
Python 3.x support is one of the main goals now for the upcoming EasyBuild 4.0 (see https://github.com/easybuilders/easybuild/issues/447); preliminary ETA is summer 2019 (but this will likely be revised at some point).

There's been quite a bit of progress on this already in a separate `4.x` branch, where the initial step was to ingest the parts of the code that we need from `vsc-base` and `vsc-install` (effectively removing them as dependencies), see #2708.

All PRs related to Python 3 support are grouped under the `python3` label, see https://github.com/easybuilders/easybuild-framework/labels/python3 .

**Comment by boegel** [comment]
Update: with #2789, the full framework test suite is passing with Python 3.6 🎉

**Comment by vsoch** [comment]
Congrats!!

**Comment by boegel** [comment]
More updates:

* framework test suite now passes with Python 2.6, 2.7, 3.5, 3.6 and 3.7 (using `4.x` branch)
* same for easyblocks test suite (using `4.x` branch)
* same for easyconfigs test suite (using `4.x` branch)

Successful builds using `eb` on top of Python 3.6:

* `Python-2.7.15-foss-2018b.eb` + `Python-3.6.6-foss-2018b.eb` + all deps (from scratch)` (from scratch)
* `OpenFOAM-6-foss-2018b.eb` + all deps

So I'm calling it, I consider that EasyBuild is fully ported to Python 3 in the `4.x` branch, and I'm closing this issue.
No doubt there some problems will still pop up with further testing, but that should be corner cases, which will be handled on a case by case basis.

The plan is to include these changes in the EasyBuild v4.0 release that we intend to release by summer 2019.
