### ISSUE TITLE
Bootstraping fails in Ubuntu 15.04, Sanity check failed: EasyBuild failed to install, cmd 'python -c "import easybuild"

### ISSUE THREAD

**Issue by cgsanchez** [easybuilders/easybuild-framework#1379]
Bootstraping in a pristine install of Ubuntu 15.04 with lmod 5.8 installed via apt fails with the following error message:

== sanity checking...
== FAILED: Installation ended unsuccessfully (build directory: /tmp/tmpzh8vtT/EasyBuild/2.3.0/dummy-dummy): build failed (first 300 chars): Sanity check failed: EasyBuild failed to install, cmd 'python -c "import easybuild"' (stdin: None) output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named easybuild
, sanity check command eb --version exited with code 1 (output: ERROR: Failed to
== Results of the build can be found in the log file /tmp/eb-fHo_5j/easybuild-EasyBuild-2.3.0-20150902.204614.QGoEv.log
Traceback (most recent call last):
  File "bootstrap_eb.py", line 648, in <module>
    main()
  File "bootstrap_eb.py", line 489, in main
    stage2(tmpdir, templates, install_path, distribute_egg_dir, sourcepath)
  File "bootstrap_eb.py", line 427, in stage2
    easybuild_main()
  File "/tmp/tmpzh8vtT/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.3.0-py2.7.egg/easybuild/main.py", line 323, in main
    ecs_with_res = build_and_install_software(ordered_ecs, init_session_state, exit_on_failure=exit_on_failure)
  File "/tmp/tmpzh8vtT/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.3.0-py2.7.egg/easybuild/main.py", line 147, in build_and_install_software
    raise EasyBuildError(test_msg)
easybuild.tools.build_log.EasyBuildError: 'Build of /tmp/tmpzh8vtT/EasyBuild-2.3.0.eb failed (err: \'build failed (first 300 chars): Sanity check failed: EasyBuild failed to install, cmd \\'python -c "import easybuild"\\' (stdin: None) output: Traceback (most recent call last):\n  File "<string>", line 1, in <module>\nImportError: No module named easybuild\n, sanity check command eb --version exited with code 1 (output: ERROR: Failed to\')'

Environment is as follows:

python -V
Python 2.7.9

vagrant@vagrant-ubuntu-vivid-64:~$ type module
module is a function
module ()
{
    eval $($LMOD_CMD bash "$@");
    [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}

vagrant@vagrant-ubuntu-vivid-64:~$ module --version

Modules based on Lua: Version 5.8  2014-11-04 12:46
    by Robert McLay mclay@tacc.utexas.edu

vagrant@vagrant-ubuntu-vivid-64:~$ module av EasyBuild

Use "module spider" to find all possible modules.
Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".

**Comment by boegel** [comment]
Can you try enabling debug, and providing us the full output (e.g. via https://gist.github.com)?

```
export EASYBUILD_BOOTSTRAP_DEBUG=1
# replace <prefix> with a (test) installation prefix of your choice
python bootstrap_eb.py <prefix> 2>&1 | tee eb_bootstrap.log
```

**Comment by cgsanchez** [comment]
Ok...this is weird, booted the machine again to launch the installer with debugging enabled...and it works. I'm puzzled. I must have something poisoning my ENV. Now I just ssh'ed, sourced /usr/share/lmod/lmod/init/bash, exported PATH=/usr/share/lmod/lmod/libexec:$PATH and it works without errors. Closing and moving along! Cheers!

**Comment by boegel** [comment]
The only thing I can think of that may have caused trouble is `$LANG`, `$LC_ALL`, etc, i.e. locale settings.

Python can be quite sensitive to those things (see https://github.com/hpcugent/easybuild-easyconfigs/pull/1876#issuecomment-132573166 and https://bugs.python.org/issue19977).

**Comment by jbd** [comment]
Hello,

I don't know if it is the right thing to do, but I've got the exact same problem using a debian testing. Here is the step to reproduce on a clean installation (I'm using docker here just as an easy way to start clean) :

`
(... docker run -it debian:testing /bin/bash ...)

# apt-get update
# apt-get install lmod python python-pkg-resources curl
# useradd --create-home --shell /bin/bash eb
# su - eb
$ EASYBUILD_PREFIX=/tmp/easybuild
$ export PATH=/usr/share/lmod/lmod/libexec:$PATH
$ which lmod
/usr/share/lmod/lmod/libexec/lmod
$ which lmod
/usr/share/lmod/lmod/libexec/lmod
eb@36f2e928449a:~$ lmod --version

Modules based on Lua: Version 5.8  2014-11-04 12:46
    by Robert McLay mclay@tacc.utexas.edu
$ source /usr/share/lmod/lmod/init/bash
$ type module
module is a function
module () 
{ 
    eval $($LMOD_CMD bash "$@");
    [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}

$ curl -O https://raw.githubusercontent.com/hpcugent/easybuild-framework/develop/easybuild/scripts/bootstrap_eb.py
$ python bootstrap_eb.py $EASYBUILD_PREFIX
....
== FAILED: Installation ended unsuccessfully (build directory: /tmp/tmpgox43m/EasyBuild/2.7.0/dummy-dummy): build failed (first 300 chars): Sanity check failed: EasyBuild failed to install, cmd '/usr/bin/python -c "import easybuild"' (stdin: None) output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named easybuild
, sanity check command eb --version exited with code 1 (output: /usr/bi
== Results of the build can be found in the log file /tmp/eb-jFHSR1/easybuild-EasyBuild-2.7.0-20160401.210444.pKibR.log
`

Results of the build are here : https://gist.github.com/jbd/531474258111b30f2d241238d6979ae7

I've re-run the boostrap with EASYBUILD_BOOTSTRAP_DEBUG=1 in a new destination directory, results are here : https://gist.github.com/jbd/58b9610c9e148fccf50720e431fc6a05

**Comment by boegel** [comment]
@jbd: can you share the contents of the directory `/tmp/easybuild/software/EasyBuild/2.7.0/lib/python2.7/site-packages`? If you have any `.pth` files in there, please also share the contents of those files.

**Comment by boegel** [comment]
@jbd: I found this in the debug log you provided:

```
== 2016-04-01 21:15:44,459 modules.py:522 DEBUG Running module command '/usr/share/lmod/lmod/libexec/lmod python load EasyBuild/2.7.0' from /tmp/tmpuvd27Z
== 2016-04-01 21:15:44,484 modules.py:527 DEBUG Output of module command '/usr/share/lmod/lmod/libexec/lmod python load EasyBuild/2.7.0': stdout: os.environ["LMOD_DEFAULT_MODULEPATH"] = "/tmp/eb-7KHqx6/tmp2Doutk/all:/tmp/easybuild-debug/modules/all";
os.environ["MODULEPATH"] = "/tmp/eb-7KHqx6/tmp2Doutk/all:/tmp/easybuild-debug/modules/all";
os.environ["LMOD_DEFAULT_MODULEPATH"] = "/tmp/eb-7KHqx6/tmp2Doutk/all:/tmp/easybuild-debug/modules/all";
os.environ["LOADEDMODULES"] = "EasyBuild/2.7.0";
os.environ["MODULEPATH"] = "/tmp/eb-7KHqx6/tmp2Doutk/all:/tmp/easybuild-debug/modules/all";
os.environ["_LMFILES_"] = "/tmp/eb-7KHqx6/tmp2Doutk/all/EasyBuild/2.7.0";
os.environ["_ModuleTable001_"] = "X01vZHVsZVRhYmxlXz17WyJhY3RpdmVTaXplIl09MSxiYXNlTXBhdGhBPXsiL3RtcC9lYi03S0hxeDYvdG1wMkRvdXRrL2FsbCIsIi90bXAvZWFzeWJ1aWxkLWRlYnVnL21vZHVsZXMvYWxsIix9LFsiY19yZWJ1aWxkVGltZSJdPWZhbHNlLFsiY19zaG9ydFRpbWUiXT1mYWxzZSxmYW1pbHk9e30saW5hY3RpdmU9e30sbVQ9e0Vhc3lCdWlsZD17WyJGTiJdPSIvdG1wL2ViLTdLSHF4Ni90bXAyRG91dGsvYWxsL0Vhc3lCdWlsZC8yLjcuMCIsWyJkZWZhdWx0Il09MCxbImZ1bGxOYW1lIl09IkVhc3lCdWlsZC8yLjcuMCIsWyJsb2FkT3JkZXIiXT0xLHByb3BUPXt9LFsic2hvcnQiXT0iRWFzeUJ1aWxkIixbInN0YXR1cyJdPSJhY3RpdmUiLH0sfSxtcGF0aEE9eyIvdG1wL2ViLTdL";
os.environ["_ModuleTable002_"] = "SHF4Ni90bXAyRG91dGsvYWxsIiwiL3RtcC9lYXN5YnVpbGQtZGVidWcvbW9kdWxlcy9hbGwiLH0sWyJzeXN0ZW1CYXNlTVBBVEgiXT0iIixbInZlcnNpb24iXT0yLH0=";
os.environ["_ModuleTable_Sz_"] = "2";
; stderr: /usr/bin/env: 'tclsh': No such file or directory
```

**Comment by boegel** [comment]
@jbd: So, it seems like you're just missing `tclsh`?

Older version of Lmod, like the one you are using, were not checking for `tclsh` at configure time, which may explain why it's not listed as a dependency.

Also note that Lmod 5.8 is quite old (Nov'14), you should probably try and get a hold of a newer version since a lot of things have been improved since then. This may help: http://easybuild.readthedocs.org/en/latest/Installing-Lmod-without-root-permissions.html

**Comment by jbd** [comment]
You're right, I'm missing tclsh. Now everything is working. I didn't take a good look at the output, sorry for that. I agree with your remark regarding the old version. I just wanted to see if I could "easily" try Easybuild on my distribution.

Thank you for your prompt response =).

**Comment by boegel** [comment]
@jbd Another alternative is to go with Lmod 'all the way', and instruct EasyBuild to generate module files in Lua syntax (as opposed to Tcl syntax, which is the default).

See also http://easybuild.readthedocs.org/en/latest/Configuration.html#module-files-syntax-module-syntax .

Basically, configure EasyBuild to use Lua syntax for module files by defining this environment variable, before running the bootstrap script:

```
export EASYBUILD_MODULE_SYNTAX=Lua
```

Once you've obtained an EasyBuild module, you can then make that configuration setting persistent, e.g. through a configuration file picked up by EasyBuild (cfr. http://easybuild.readthedocs.org/en/latest/Configuration.html#configuration-file-s.

**Comment by boegel** [comment]
@jdb Note that if you use Lua syntax in module files, you won't need `tclsh` at all, it's only required to let Lmod consume module files in Tcl syntax...

**Comment by jbd** [comment]
Got it, thank you for the clarificaton !

**Comment by Flamefire** [comment]
Can this be closed then?
