### ISSUE TITLE
provide generic way for sanity_check to look in both `lib` and `lib64` for library files

### ISSUE THREAD

**Issue by torbjoernk** [easybuilders/easybuild-framework#1404]
AFAIK the only way of checking whether library files ended up in `lib/` or `lib64/` is via

``` .py
sanity_check_paths = {
  'files': [
    ('lib/myLib.so', 'lib64/myLib.so'),
    ('lib/myLib.a', 'lib64/myLib.a')
  ]
}
```

Wouldn't it be nice having this collapsing into something like

``` .py
sanity_check_paths = {
  'files': [
    LibraryPathBuilder('myLib', shared=True, static=True)
  ]
}
```

It's less error prone to typos and way less tedious.

**Comment by boegel** [comment]
EasyBuild will now (since v3.6.1) automatically consider `lib64/...` paths whenever a `lib/...` is specified (and vice versa), see #2477, thanks again for the idea @torbjoernk!
