### ISSUE TITLE
haskell packages 

### ISSUE THREAD

**Issue by ac427** [easybuilders/easybuild-framework#1406]
Is there any solution to install Haskell packages ( extensions? )

**Comment by boegel** [comment]
This question belongs in the easybuild-easyblocks repository, but I understand the confusion. :-)

Right now, no, not yet. Someone will have to look into a generic easyblock that derives from `ExtensionEasyBlock` to install Haskell packages, similar to the existing `PythonPackage`, `PerlModule` ones we have already (https://github.com/hpcugent/easybuild-easyblocks/tree/master/easybuild/easyblocks/generic), or the `OCamlPackage` one that is currently being worked on (see https://github.com/hpcugent/easybuild-easyblocks/pull/467).

**Comment by ac427** [comment]
thanks @boegel . Shall I create a new issue in easybuild-easyblocks?

**Comment by boegel** [comment]
@ac427: maybe yes. Or a pull request. ;-)

**Comment by ac427** [comment]
I will try PR :)

**Comment by boegel** [comment]
:+1:
