### ISSUE TITLE
GC3Pie backend submits jobs even if dependency build failed

### ISSUE THREAD

**Issue by geimer** [easybuilders/easybuild-framework#1441]
When robot-building a bunch of software via the GC3Pie job backend with SLURM, GC3Pie happily submits follow-up jobs even if building of one (or more) of the dependencies failed.  I am not entirely sure whether this is an issue in EasyBuild, in GC3Pie, or in the way the two are working together.  I also don't know whether this also happens with other job schedulers.

Steps to reproduce:
- Start with an empty installdir
- Edit `M4-1.4.17.eb` and add `preconfigopts='false && '`
- Run `eb GCC-5.1.0.eb -r --job` using GC3Pie with SLURM
- Both jobs will be submitted, both fail (the first for obvious reasons, the second because the M4 module can't be found)

**Comment by wpoely86** [comment]
@geimer pbs will submit all build jobs at once with a dependency between them. So in the PBS case, both jobs will also be submitted and fail.

**Comment by riccardomurri** [comment]
It would be rather simple to add this kind of checks to the EB->GC3Pie interface, *provided* `eb` always exits with a non-zero exit code when a build fails.

Is there (still) interest in this?

**Comment by boegel** [comment]
@riccardomurri `eb` does indeed exit with non-zero exit code in case a build fails, so you should be able to rely on that

**Comment by geimer** [comment]
@riccardomurri IMHO this feature would still be useful.  Why submit jobs that are already known to fail?

**Comment by boegel** [comment]
@riccardomurri ping on this? It was brought up again during today's EB conf call.

**Comment by riccardomurri** [comment]
Sorry, completely fell off my radar ... :-(

**Comment by riccardomurri** [comment]
Could anyone please test #2474 ?  That should fix this issue.

**Comment by akesandgren** [comment]
Fixed in #2474
