### ISSUE TITLE
string values for extensions are templated with wrong name/version when queried early

### ISSUE THREAD

**Issue by Caylo** [easybuilders/easybuild-framework#1445]
for example in [this easyconfig file](https://github.com/hpcugent/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/p/Python/Python-2.7.10-intel-2015b.eb#L77) the highlighted line will be templated like `python-Python-2.7.10.tar.gz` instead of `python-dateutil-2.4.2.tar.gz`

maybe use ext_name and ext_version in exts_list to avoid this (see
http://easybuild.readthedocs.org/en/latest/Removed-functionality.html#extension-filter-template)

**Comment by boegel** [comment]
fixed in #2852
