### ISSUE TITLE
add support for specifying number of cores to use per job for parallel build

### ISSUE THREAD

**Issue by JensTimmerman** [easybuilders/easybuild-framework#152]
parallelbuild is currently always submitting jobs with the max amount of cores requested.
Yet, some software has parallel=n in it's .eb file. So we should set this when starting a job, since it not going to benefit from all cores anyway, and we don't need to reserve unneeded resources.

**Comment by akesandgren** [comment]
@boegel Is this still valid?

**Comment by boegel** [comment]
@akesandgren We have support for `--job-cores` for a long time already (see e.g. #1547), I guess that covers it.
