### ISSUE TITLE
EasyBuild installation without `setuptools`

### ISSUE THREAD

**Issue by stolpeo** [easybuilders/easybuild-framework#1542]
I have two systems, both an `Ubuntu 14.04 LTS`, one without `setuptools` for `Python` and one with `setuptools` installed. I bootstrap an EasyBuild installation on both systems:

```
https://raw.githubusercontent.com/hpcugent/easybuild-framework/develop/easybuild/scripts/bootstrap_eb.py
python bootstrap_eb.py /X
```

After setting the install path and prefix in the config to X, I load EasyBuild and install version 2.4.0 (`eb EasyBuild-2.4.0.eb -r`).

For the installation without `setuptools` I get a different folder structure than with `setuptools`:

```
./EasyBuild/2.5.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.5.0-py2.7.egg/easybuild/easyconfigs/l/libreadline/libreadline-6.3-foss-2015a.eb
./EasyBuild/2.4.0/easybuild/easyconfigs/l/libreadline/libreadline-6.3-foss-2015a.eb
```

With `setuptools`:

```
./EasyBuild/2.5.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.5.0-py2.7.egg/easybuild/easyconfigs/l/libreadline/libreadline-6.3-foss-2015a.eb
./EasyBuild/2.4.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.4.0-py2.7.egg/easybuild/easyconfigs/l/libreadline/libreadline-6.3-foss-2015a.eb
```
1. I wonder why there is no problem for version 2.5.0
2. The logfile reports that it can't find `setuptools` and falls back to `distutils.setup`, but obviously this does not work entirely.

[easybuild_logfiles.zip](https://github.com/hpcugent/easybuild-framework/files/88745/easybuild_logfiles.zip)

My solution is that I install `python-setuptools` locally with the package manager, tested on Ubuntu 14.04, Debian 8 and CentOS 7. This solves the wrong directory structure as described above. But the `Cython` installation that I am doing using EasyBuild fails for Debian 8 and Ubuntu 14.04, I think because `setuptools` is installed (it works for CentOS 7, though). It worked beforehand with the "wrong" directory structure. The versions of `setuptools` differ a lot between the systems:

Ubuntu 14.04:

```
>>> print setuptools.__version__
3.3
```

Debian 8:

```
>>> print setuptools.__version__
5.5.1
```

CentOS 7:

```
>>> print setuptools.__version__
0.9.8
```

Cython installation logfile:
[easybuild-Cython-0.22.1-20160113.160152.QuDdv.log.zip](https://github.com/hpcugent/easybuild-framework/files/91884/easybuild-Cython-0.22.1-20160113.160152.QuDdv.log.zip)

**Comment by boegel** [comment]
@ocs7474505: installations that result in a `.egg` directory structure are done via `setuptools`; the fallback to `distutils` is there to try and get a working EasyBuild regardless of whether or not setuptools is available

Why are you worried about the directory structure of EasyBuild itself? Both installations should work just fine?

I'm not sure why you're getting a different directory structure when installing EasyBuild 2.5.0... There were no deliberate changes to make this happen, but it may be a side-effect of a change in the `PythonPackage` easyblock.

Maybe open a separate issue on that? Try pasting the relevant parts in the issue, in between triple backquotes ``` to make it render as a code block.

**Comment by ocs7474505** [comment]
@boegel : I have a script that uses EasyBuild to install software, but it is dependent on the structure since it has to make some modifications on the eb files. I noticed that my script does not work properly on every system I tested.

**Comment by ocs7474505** [comment]
I opened a new issue for this task #1549.

**Comment by boegel** [comment]
@stolpeo `setuptools` is now a runtime dependency of EasyBuild (as it already was for recent versions of `vsc-base` on which it depends), so this issue has become irrelevant?

**Comment by Flamefire** [comment]
Outdated as is #1549, see there
