### ISSUE TITLE
EasyBuild 2.5.0 installation with `distutils.setup` results in unexpected folder structure

### ISSUE THREAD

**Issue by stolpeo** [easybuilders/easybuild-framework#1549]
For the installation of EasyBuild without `setuptools` it falls back to `distutils.setup`. This is expected to install EasyBuild with a different directory structure like this one:

```
./EasyBuild/2.4.0/easybuild/easyconfigs/l/libreadline/libreadline-6.3-foss-2015a.eb
```

But installing the current version 2.5.0 from the bootstrap script, it does not result in the same structure:

```
./EasyBuild/2.5.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.5.0-py2.7.egg/easybuild/easyconfigs/l/libreadline/libreadline-6.3-foss-2015a.eb
```

Installing then version 2.4.0 from this 2.5.0 installation results in the above mentioned structure, i.e. it is not consistent among versions.

[easybuild_install_logs.zip](https://github.com/hpcugent/easybuild-framework/files/92130/easybuild_install_logs.zip)

**Comment by ocs7474505** [comment]
Apparently he uses setuptools for 2.5.0 that is brought with vsc:

From the log file:

```
INFO: using long_description vsc-install provides shared setuptools functions and classes for python libraries developed by UGent's HPC group
```

**Comment by boegel** [comment]
@stolpeo If different install tools are used, the install folder structure is going to differ too, there's no way around that...

Since `setuptools` is now a runtime dependency for both `vsc-base` and EasyBuild itself, things should be more consistent now however...

Please let us know if you feel it's OK to close this issue.

**Comment by Flamefire** [comment]
Seems to be (very) outdated by now and can be closed as setuptools is no longer a dependency of EB 4.x
