### ISSUE TITLE
Possible new feature (postinstallpatches)

### ISSUE THREAD

**Issue by damianam** [easybuilders/easybuild-framework#1612]
There are some software packages that require to change/create files once the installation is done. This can be currently handled by:
- Custom easyblocks
- postinstallcmds
- Patching the source so the install step accounts for the appropriate changes

A feature such as postinstallpatches could be convenient in these cases, to create/modify files that have been already installed. For instance, to create a wrapper or a script. In some cases it could help to minimize the amount of easyblocks.

Opinions? @boegel @ocaisa ?

**Comment by boegel** [comment]
makes sense to me, and shouldn't be too hard to implement support for

**Comment by AndiH** [comment]
I also think this would be useful. I certainly need it now :/.

**Comment by branfosj** [comment]
Done in #3974
