### ISSUE TITLE
provide a more portable way of specifying os dependencies

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#174]
We need a more portable way to specify OS dependencies, since package names can differ between OSs (e.g., `boost-devel` on RedHat vs `boost-dev` on Debian).

Support for running commands to check for specific functionality is already there, but is only used as a fallback (i.e. when a package that matches isn't found).

We should allow specifying that we want a particular header file, binary, version of a particular command, etc.
Checking for header files may result in reproducing a tool like `configure`, which actually tries to compile a small C program to check whether a header file is found.

Noted by @stdweird: we should rely on the package manager to figure out whether something we need is available (rpm/yum, dpkg, ...)/

Another option (suggested by @fgeorgatos) may be meta-modules. These could correspond to package names, or policies (e.g. http://eniac.cyi.ac.cy/display/UserDoc/HPC+Baseline+Configuration or http://www.ccac.hpc.mil/consolidated/bc/policy.php). 
Example: `tcsh` can be provided via `LS2_05-06` or `FY05-06`; names are fictional they can be anything; they could also correspond to rpm/deb packages.

**Comment by akesandgren** [comment]
@boegel Isn't this handled already?

**Comment by boegel** [comment]
Yes, see https://github.com/easybuilders/easybuild-framework/pull/846
