### ISSUE TITLE
Install easybuild with a custom installation of python

### ISSUE THREAD

**Issue by seasoulnk** [easybuilders/easybuild-framework#1859]
I do not have admin right on my hpc but want to install easybuild. I have a custom installation of python 2.7 using canopy and definitely set the path environment. When type "which python" I will get the path of canopy. But if I bootstrap easybuild it will complain "Easybuild requires python v2.6 or a more recent v2.x, found 2.4.3". Yes, that is the system python version. But my init bash setting  enforce a canopy python. So I use pip method to install easybuild. Yes, it succeeds. But every operation after installaiton gives the same error. 

So how to set the default python version to make easybuild work?
I stuck over here and am waiting for the solution.

**Comment by ocaisa** [comment]
This is because eb is hardchecking for `python2` before it checks for `python` (see https://github.com/hpcugent/easybuild-framework/blob/master/eb#L47). If you have appropriate permissions, the following should do the trick:
```
ln -s $(which python) $(which python)2
```

**Comment by ocaisa** [comment]
@boegel we probably want to check the version of `python` before we go with `python2`

**Comment by boegel** [comment]
@ocaisa I guess that's an option, but we switching to first considering `python2` quite a while ago (cfr. #1411), which was kind of a jump since it may have impacted several people where in their setup considering `python` first worked fine...

I guess this is worth considering with EasyBuild v3 in mind though, but then we need to revisit the reasoning that made us consider `python2` first.

**Comment by ocaisa** [comment]
Well, the way it stands we are defaulting to `python2` when we should be defaulting to `python` and falling back to `python2` iff `python` is major version 3.

**Comment by boegel** [comment]
@ocaisa I understand, but we opted differently in #1411, and we had a reason for it...

I think @wpoely86 was involved in that discussion...

**Comment by ocaisa** [comment]
Ok, I found the relevant quote:

> yes, and it seems to me like the proper thing to do. We want python 2.x. We shouldn't directly call python and assume it is 2.x. And if you have to different pythons (python and python2), then you're in a world of shit. We cannot account for every oddball case in the world? Most (if not all) distros have a python2 and a python3 these days.

That's fine and all but what about when the OS distro doesn't cut the mustard? Then that logic doesn't allow me to use  my own `python` without reading the `eb` script. I agree we shouldn't call `python` and assume it's 2.x...can't we just check though? TBH, having a different python than the OS for easybuild seems like a perfectly reasonable thing to do,  and if I was to make a feature request I'd say let's provide one in the bootstrap script (and create the `python2` symlink) ;)

**Comment by boegel** [comment]
@ocaisa I'm game for switching back to checking `python` first and checking the version before falling back to `python2`. We can make that switch with EasyBuild v3 easily without stepping on people's toes too much (if at all).

**Comment by Flamefire** [comment]
This is fixed, EB and bootstrap use "python" now

**Comment by boegel** [comment]
Or you can control which `python` should be used by defining `$EB_PYTHON`.
