### ISSUE TITLE
add a dynamic libraries section to sanityCheckPaths

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#196]
(old internal ticket 262)

Next to the obligatory `files` and `dirs` keys in the `sanityCheckPaths` dictionary, we should also support on optional `dynlibs` key.

This would support specifying the names on the dynamic libraries we expect to find (without extension), making it more portable. On Linux, dynamic libraries end in `.so`, on OS X they end in `.dylib`.

**Comment by Micket** [comment]
We deal with .so vs .dylib via the SHLIB_EXT variable now in lots of places, and rather than checking bits on binaries I think sanity_check_commands serves this purpose well, so I don't think there is anything more that needs solving here.
