### ISSUE TITLE
Alternative generic easyblocks are not picked up if they aren't in a generic subfolder

### ISSUE THREAD

**Issue by damianam** [easybuilders/easybuild-framework#1964]
The title is kind of self descriptive. If you have a folder where you have all your custom easyblocks, generic easyblocks are not picked up. You have to manually include them with `--include-easyblocks $SOME_PATH/generic/some_easyblock.py`, which is kind of counterintuitive given that all the other easyblocks work just fine.

**Comment by pescobar** [comment]
I have also hitted this one

**Comment by boegel** [comment]
proposed fix in #2432

**Comment by boegel** [comment]
follow-up in #2432
