### ISSUE TITLE
make EasyBuild check easyconfig repository

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#207]
EasyBuild should check the easyconfig repository it dumps easyconfig file to after building, when resolving dependencies for a build or when being run without a supplied easyconfig file.

**Comment by akesandgren** [comment]
@boegel Since this is basically configurable in the easyconfig file, this could be closed or?

**Comment by boegel** [comment]
This is about https://github.com/easybuilders/easybuild-framework/pull//1201, so good to close

**Comment by boegel** [comment]
Note: that change was first included in EasyBuild 2.0
