### ISSUE TITLE
Feature request: Backup of module files when using --module-only --force

### ISSUE THREAD

**Issue by damianam** [easybuilders/easybuild-framework#2093]
Background: We might need to add properties to modules after SW has been installed already. I'd like to have a backup of the old module to compare contents with the new and make sure that what is there is consistent, since it is not guaranteed that the module generated with `--module-only` is exactly the same as when going through the whole process.

There are workarounds like using `--installpath-modules`, but this is error prone, and once a file is overwritten it is gone.

**Comment by damianam** [comment]
See https://github.com/easybuilders/easybuild-framework/pull/2134

**Comment by boegel** [comment]
let's follow-up on this in #2134
