### ISSUE TITLE
RFF: dump a copy of --dump-env-script output in the %(installdir)/easybuild directory as an .env file for each build

### ISSUE THREAD

**Issue by JackPerdue** [easybuilders/easybuild-framework#2111]
I think the Subject: covers it.

But if it doesn't...... sometimes its nice to have a quick reference (especially for users) of what the environment was like when a certain package was built.  Especially if they want to use the EB version to build a custom version.  %(installdir)/easybuild already has a -devel file but its basically useless for users.  And teaching users how to use EB and run --dump-env-script is a bit much.   So lets just make a "easy build" copy for them.

More beer rewards available though given the picture boegel sent me of the beer stocks purchased for the EasyBuild user meeting, I imagine most of those at the hackathon on Friday will be drowning already.  Goodness gracious.   If y'all (those listed as being there) drink all of that, I'm going to have to work on your next trip to SC in Austin.

**Comment by JackPerdue** [comment]
and yes I forgot the ending 's' on both uses of %(installdir) like I usually do... pep8 or eb would not be happy

**Comment by boegel** [comment]
I've been meaning to get this covered in the documentation (https://github.com/hpcugent/easybuild/pull/263), but I think there's an approach already that' may satisfy your needs, see the use of the `BuildEnv` easyblock at https://github.com/hpcugent/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/b/buildenv/buildenv-default-intel-2016b.eb, which would give you a module like `buildenv/default-intel-2016b`.

The use case here is slightly different though, this is still a valid request that should be easy to implement and would be useful in many cases...

**Comment by vanzod** [comment]
It would be nice to hear Robert's opinion on having a native Lmod function to read such buildenv files and spit the information out accordingly. In this way the users will only have to interact with Lmod.

**Comment by Flamefire** [comment]
The request is actually good. In my case I wanted to work on TensorFlow which is already installed but with...different settings than I want. Knowing which env-vars were defined would be great. Maybe even to the point of actual invocations. Especially for TensorFlow there are a lot of `TF_NEED_<FOO>` env vars that define how TF is going to be build. In case of an updated EB/EC this information may be lost.

**Comment by JackPerdue** [comment]
...bump...
I have a user here who wants to add their own USER_MAEAM (not to be confused with USER_MEAMC) code to LAMMPS.  I'd love to just give them LAMMPS buildenv (and not the toolchain buildenv). Once again, in order to do that I'm going to have to use --force, destroy the current install and wait for it to complete.  It would be SO much nicer if that was already just in the installdir/easybuild directory (with the other useful files there).

**Comment by boegel** [comment]
@JackPerdue Alan has looked into dumping the build environment in the `reprod` dir of the installation, see #3376 

That won't help you with grabbing the build env for an existing LAMMPS installation though.

Maybe you can do this as a workaround:

```
eb --installpath /tmp/$USER/LAMMPS-build-env --dump-env-script
```

and then replace `/tmp/$USER/LAMMPS-build-env` in the resulting script with the correct installation path for the existing installation?

Long term dumping the build environment in the `reprod` dir of the installation is a better approach though, but that only helps with new installations of course.
