### ISSUE TITLE
pyshortver deferencing fails when Python is not a full dependency

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-framework#2114]
I was testing an easyconfig with `Python` as a builddependency, not a full dependency.

In `postinstallcmds`, I tried to use `pyshortver` but this wasn't resolved and instead was passed as a raw value, causing a crash.

This should be picked up earlier, because it's a somewhat problematic configuration anyway.

**Comment by verdurin** [comment]
The problem went away when I instead had `Python` as a full dependency.

**Comment by boegel** [comment]
@verdurin What do you think the best approach would be here? Try and scan easyconfigs for templates that we won't be able to resolve at all?

The tricky bit is that some templates can only be resolved as a certain point in time...

**Comment by boegel** [comment]
See also #3300, basically same issue (but there with a use case that shows that filtering out build dependencies probably doesn't make sense).
