### ISSUE TITLE
GitRepository help

### ISSUE THREAD

**Issue by jerowe** [easybuilders/easybuild-framework#2126]
@boegel, this is not so much an issue as it a cry for help. I'm trying to use the github repo option, and either it doesn't do what I think its supposed to do, or I'm doing things wrong. ;-)

```
eb --robot --dry-run -d  --repository=GitRepository --repositorypath=git@github.com:nyuad-cgsb/nyuad-hpc-module-configs.git  gencore_qiime-1.0.eb
```

`git@github.com:nyuad-cgsb/nyuad-hpc-module-configs.git` is a publically available github repo. `gencore_qiime-1.0.eb` is an eb in that repo.

The error I get is:

```
ERROR: Can't find path /scratch/gencore/.local/gencore_qiime-1.0.eb
```

Obviously I'm missing something. Help?

**Comment by boegel** [comment]
`--repository*` is for specifying the type & location of the easyconfigs repository/archive that EasyBuild maintains (the easyconfigs that are installed are copied to there for archiving purposes), see also http://easybuild.readthedocs.io/en/latest/Configuration.html#easyconfigs-repository-repository-repositorypath .

`eb` will not pick up easyconfigs from there automagically, but you can tell it too, see for example http://easybuild.readthedocs.io/en/latest/Using_the_EasyBuild_command_line.html#example-use-case .
