### ISSUE TITLE
Yet another lmod integration feature (userInGroup)

### ISSUE THREAD

**Issue by damianam** [easybuilders/easybuild-framework#2127]
In lmod it is possible to use the `userInGroup` function to restrict the loading of modules to certain user groups:

```
if (userInGroup("namd_group")) then
   something()
else
   LmodError(err_message,"\n")
end
```

I think this would be a nice thing to integrate together with the `group` key in easyconfigs.

I'll see if I can get to it soon[ish]

**Comment by mboisson** [comment]
Note that the error message and the name of the group must be site-customizable, i.e. in the easyconfig. 

Also, for LmodError, if we want to use localization, we'ld have to wrap the error message to get the right language.

**Comment by damianam** [comment]
The name of the group is already customizable.

Regarding the error message, I am not superconvinced about being it site customizable through another easyconfig parameter. As I see it there are three ways:

1. Set a standard error message in Lmod, that is localizable and that can be leveraged from EB.
2. Generate from EB a generic error message ("You are not part of the `group` group. Please consult with user support how to become a member of that group.").
3. Generate from EB a customizable error message.

1 has to be tackled in Lmod which makes it Lmod version dependent, which means we shouldn't probably consider it. 2 is the easiest. 3 will need a fallback if no customized error is provided. I am afraid that at the end nobody will use the custom message, since the fallback would be good enough for almost everyone. I am hesitant to spend time implementing a feature that I don't need and maybe nobody else will need.

**Comment by boegel** [comment]
I agree with @damianam here, 2 is exactly what I had in mind. 1 is fine too, depending on a particular version of Lmod for an optional feature isn't a huge problem imho.

I'm not planning to spend time on adding support on localisation in EasyBuild anytime soon, but if there are pull requests for it I'll certainly try and take a look at them if time allows for it.

**Comment by mboisson** [comment]
At the very least, if I were to enable this feature for Compute Canada, I would say something like "Please write to us at <email>@computecanada.ca with your NAMD username to become a member of that group", rather than "Please consult with user support...". I would probably make the message bilingual as well.

**Comment by boegel** [comment]
We don't have anything like that in EasyBuild yet, i.e. allow for customising EasyBuild error messages or statements that are included in module files. If we support this, it should be done as a part of a bigger effort, not as something for one specific feature...

**Comment by mboisson** [comment]
That's fine. I'll probably disable this feature and have it module-specific through the module footer in the EB recipe. Would there be a good place to document this alternative solution ?

**Comment by boegel** [comment]
@mboisson I never answered your last question...

Your alternative approach could be documented in a section that covers both `group` easyconfig parameter, which is yet to be written...

**Comment by damianam** [comment]
This has been added, so I am closing the issue.
