### ISSUE TITLE
TODO list for --check-style

### ISSUE THREAD

**Issue by migueldiascosta** [easybuilders/easybuild-framework#2133]
* [ ] check if filename is consistent with contents
* [ ] check order/grouping of parameters
* [ ] ...

**Comment by boegel** [comment]
@migueldiascosta The filename check is already done in the easyconfigs test suite, see https://github.com/hpcugent/easybuild-easyconfigs/blob/master/test/easyconfigs/easyconfigs.py#L207

For the order/grouping of parameters, there's a WIP PR: #2165

So, maybe this issue can be closed, to avoid having duplicates around?
