### ISSUE TITLE
Keeping an open search but restricting the robot

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-framework#2252]
To my understanding it's not possible to have an open search but restrict the robot. At the moment you can restrict the robot through `EASYBUILD_ROBOT` and `EASYBUILD_ROBOT_PATHS`, but once you set `EASYBUILD_ROBOT_PATHS` your search space is also restricted. It would be nice if these could be tweaked independently (say with a new setting `EASYBUILD_SEARCH_PATHS`).
This makes sense when you start thinking about looking into other people's repos.

**Comment by boegel** [comment]
@ocaisa Makes sense to me, and it should be fairly easy to do.

The `search_easyconfigs` function in `easybuild.tools.robot` now only considers `robot_path` (which is a combination of the paths specified in `--robot` and `--robot-paths`, according to the rules outlines at http://easybuild.readthedocs.io/en/latest/Using_the_EasyBuild_command_line.html#robot-search-path), but it can be easily extended to also consider (the new) `search_paths` if one or more paths were specified for it.

Are you up for taking a stab at this yourself?

**Comment by boegel** [comment]
follow up in #2255
