### ISSUE TITLE
Lua generator emits description verbatim into module source

### ISSUE THREAD

**Issue by zao** [easybuilders/easybuild-framework#2317]
A description like `description = "hi [there]"` will be emitted into a Lmod module as `whatis([[Description: hi [there]]])`.

There is no escaping inside of such "long brackets" and as such, the string will prematurely terminate on the first `]]` found.

The mechanism that Lua offers to have long brackets occur inside of long brackets is to add one or more `=` inside the left and right bracket pairs. This particular example would be mitigated if it was generated as `[=[hi [there]]=]`.

Other solutions would be to reformulate the output or to just not use obscene amounts of brackets in module descriptions, but this has occurred at least once in the wild in the `OTF` easyconfig.

**Comment by boegel** [comment]
PR to fix this is at #2320, let's follow up there...
