### ISSUE TITLE
--new/update-pr fails in extended dry run mode when adding a patch file

### ISSUE THREAD

**Issue by migueldiascosta** [easybuilders/easybuild-framework#2334]
When running `--update-pr -x` and adding a new patch file, it fails saying it cannot find the patch file, which should have been copied to the temp dir. But the actual `--update-pr` works, so `-x` must be disabling the copy?

Additionally, doing the same to submit changes to a patch, dry run mode doesn't show the changes to the patch file, although the actual `--update-pr` does submit them.

**Comment by migueldiascosta** [comment]
just ran into this issue again, this time with `--new-pr`

**Comment by migueldiascosta** [comment]
additionally, `--new-pr` with a patch file asks for a custom `pr-commit-message` even if the easyconfig is a new one, shouldn't the message be autogenerated also in this case?

**Comment by migueldiascosta** [comment]
I can submit a PR for this, but I see two alternatives:

1) skip staging the patch in `_easyconfigs_pr_common` (fixes the crash but will still not show the patch)

2) add `force_in_dry_run=True` to `copy_file` in `copy_patch_files` (not sure if it will affect anything else)

**Comment by boegel** [comment]
@migueldiascosta The latter is probably the best option... `force` sounds scary, but since we're copying to a temporary directory that is set up to prepare the branch to push to GitHub, that's OK imho

**Comment by migueldiascosta** [comment]
fixed by #2442

**Comment by boegel** [comment]
fixed with ~~#2442~~
