### ISSUE TITLE
bootstrap_eb.py fails to find Tcl Modules installation

### ISSUE THREAD

**Issue by ndusek** [easybuilders/easybuild-framework#2366]
When running **bootstrap_eb.py**, the script fails with the following error:

```
[[ERROR]] Could not find any module command, make sure one available in your $PATH.
Known module commands are checked in order, and include: lmod, modulecmd, modulecmd.tcl
Check the output of 'type module' to determine the location of the module command you are using.
```

I have the Tcl Modules system installed. Running **type module** yields

```
module is a function
module () 
{ 
    _moduleraw $* 2>&1
}
```

and running **module --version** gives

```
Modules Release 4.0.0 (2017-10-16)
```

So it seems that Tcl Modules is installed properly, although making the **module** command available by defining a function alias seems a bit hackish to me. But that is the default installation method according to the [Tcl Modules documentation](https://modules.readthedocs.io/en/stable/INSTALL.html). I have also tried running **bootstrap_eb.py** with the location to the **modulecmd.tcl** executable at the beginning of my PATH, but that does not seem to work either, even though the error message says that EasyBuild explicitly checks for the presence of this command. 

Not sure what I'm doing wrong here, but any help you could provide would be much appreciated.

**Comment by boegel** [comment]
@ndusek The version of the modules tool you are using is not supported yet by EasyBuild, but we're working on fixing that, see https://github.com/easybuilders/easybuild-framework/issues/2341 and https://github.com/easybuilders/easybuild-framework/pull/2365 .

**Comment by ndusek** [comment]
Great, thank you!

**Comment by ndusek** [comment]
@boegel What is the earliest version of the Tcl Modules software that EB supports? We have a cluster running 3.2.10 which should be compatible according to the docs, but it is not recognized by the bootstrap script. Here is the output of `module --version`

```
VERSION=3.2.10
DATE=2012-12-21

AUTOLOADPATH=undef
BASEPREFIX="/usr"
BEGINENV=99
CACHE_AVAIL=undef
DEF_COLLATE_BY_NUMBER=undef
DOT_EXT=""
EVAL_ALIAS=1
HAS_BOURNE_FUNCS=1
HAS_BOURNE_ALIAS=1
HAS_TCLXLIBS=undef
HAS_X11LIBS=1
LMSPLIT_SIZE=undef
MODULEPATH="/usr/Modules/modulefiles"
MODULES_INIT_DIR="/usr/Modules/3.2.10/init"
PREFIX="/usr/Modules/3.2.10"
TCL_VERSION="8.5"
TCL_PATCH_LEVEL="8.5.7"
TMP_DIR="/tmp"
USE_FREE=undef
VERSION_MAGIC=1
VERSIONPATH="/usr/Modules/versions"
WANTS_VERSIONING=1
WITH_DEBUG_INFO=undef
```

Let me know if I should file this under a new issue or not. I did look into #2341  and #2365 and it looks like 4.0 commits have been merged?

**Comment by boegel** [comment]
@ndusek 3.2.10 is supported, it should be auto-recognised by the bootstrap script as `EnvironmentModulesC`, are you saying it doesn't?
Note that you must have the actual `modulecmd` binary available via `$PATH`, which is non-standard...

You can also try bootstrapping after specifying which modules tool it should use, via:

```
export EASYBUILD_MODULES_TOOL=EnvironmentModulesC

**Comment by ndusek** [comment]
Correct, it does not auto-recognize it. But we did not have the `modulecmd` binary in `$PATH`. Adding that in did prompt it to recognize our version of Modules. Thank you!

**Comment by boegel** [comment]
@ndusek Having `modulecmd` available via `$PATH` is a strict requirement, see also http://easybuild.readthedocs.io/en/latest/Installation.html#requirements .

**Comment by ndusek** [comment]
Ok, I do see that now. Must have missed it. Thanks again.
