### ISSUE TITLE
combining multiple compiler wrappers may result in 'fork bomb'

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#2402]
When multiple compiler wrappers are being used together, e.g. when `--rpath` or `--use-ccache` are used when building `TensorFlow` with the `intel` toolchain (which involves a wrapper to ensure `icc` still works when being called by Bazel, cfr. https://github.com/easybuilders/easybuild-easyblocks/pull/1287/files#diff-925e7942309e22e4c64cb2d99b50c206R77, one wrapper ends up calling the other wrapper, with neither calling out to the actual compiler, basically resulting in a fork bomb.

This is largely due to too naive wrappers script, which simply assume that the next compiler command available through `$PATH` is the correct one.

One possible solution for this would be to let the wrappers created by EasyBuild check whether the command being called is the actual compiler, i.e. a binary, rather than a wrapper script.

I know that SURFsara has run into similar issues when combining their 'manual' wrappers with `eb --rpath`, so thoughts on this @jdonners, @casparvl?

**Comment by boegel** [comment]
Another option would be that the wrappers we generate filter their own location from `$PATH` before calling out to whichever compiler command is next in `$PATH`...

**Comment by jdonners** [comment]
the second option is the right one, IMHO. That is what our compiler wrappers do as well. One issue with this option is that the compiler and linker wrappers would have to be in separate paths, because the compiler usually calls the linker, which should call the linker wrapper first to add the RPATH.

**Comment by boegel** [comment]
Fix for wrapper used in `TensorFlow` easyblock when building with `icc` is in https://github.com/easybuilders/easybuild-easyblocks/pull/1361, fix for RPATH wrapper is in https://github.com/easybuilders/easybuild-framework/pull/2410

**Comment by fgeorgatos** [comment]
Apologies for arriving late for the show (but you see, reading your email backlog during a flight has its advantages!)

Couldn’t this need by treated somewhat by hacking together a solution around Lmod’s StackedVariables concept?!

Don’t get me wrong, that might impose a single modules back-end but it comes with the benefit of ability to control the ordering in the stack of wrappers, which might in turn have its own semantic, and therefor use-cases!

F.

Sent from my iPhone

**Comment by boegel** [comment]
@fgeorgatos The RPATH wrappers are put in place dynamically, as a part of setting up the build environment for the toolchain & dependencies. I don't think Lmod is of much help in that context.
