### ISSUE TITLE
Add hooks executed to the output

### ISSUE THREAD

**Issue by damianam** [easybuilders/easybuild-framework#2407]
Wouldn't it make sense to add something like `== running whatever_hook` to the output, so at least it's clear that a hook is being executed?

**Comment by fgeorgatos** [comment]
+1
-- 
echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Comment by boegel** [comment]
It's already mentioned in the log, but I guess it doesn't hurt to have it more prominent...

Easy to change in `run_hook` (https://github.com/easybuilders/easybuild-framework/blob/master/easybuild/tools/hooks.py#L160), just add a call to `print_msg` next to the `log.info` call...

**Comment by boegel** [comment]
fixed in #2427
