### ISSUE TITLE
Feature Req: custom root commands in %post section

### ISSUE THREAD

**Issue by shahzebsiddiqui** [easybuilders/easybuild-framework#2413]
eb should allow option to install packages into singularity container at build time. This would be useful when building MPI to install certain package deps prior to building container.

easybuild-framework should be able to add any root commands prior to build. Either this can be done with a custom easybuild base container or ability to do this generated recipe file. 

eb should be able to add custom repos in ``/etc/yum.repos.d/`` to install extra packages

**Comment by boegel** [comment]
I believe this is tackled now, since additional commands for the `post` section can be specified via the `post_commands` keyword through `--container-config`, see https://easybuild.readthedocs.io/en/latest/Containers.html#container-configuration-container-config .
