### ISSUE TITLE
GCCcore installed twice . Bug in --hide-deps ?

### ISSUE THREAD

**Issue by pescobar** [easybuilders/easybuild-framework#2453]
I just installed latest easybuild 3.5.3 and when trying this:

```
eb --hide-deps=GCCcore foss-2016b.eb -D
```

I get this list of apps to be built:

```
 * [ ] $CFGS/g/GCCcore/GCCcore-5.4.0.eb (module: GCCcore/.5.4.0)
 * [ ] $CFGS/g/GCCcore/GCCcore-5.4.0.eb (module: GCCcore/5.4.0)
```

I have double checked that GCCore is built twice if I try to build foss/2016b . Is this a bug in `--hide-deps` ?

**Comment by boegel** [comment]
@pescobar To hide toolchains, you need to use `--hide-toolchains` (too). Toolchains & dependencies are considered different things.

```
$ eb --hide-deps=GCCcore --hide-toolchains=GCCcore foss-2016b.eb -D | grep 'module: GCCcore'
 * [ ] $CFGS/g/GCCcore/GCCcore-5.4.0.eb (module: GCCcore/.5.4.0)
```

**Comment by pescobar** [comment]
ups, I forgot about that. Sorry for the noise

thanks @boegel !
