### ISSUE TITLE
Error with toolchain gimkl

### ISSUE THREAD

**Issue by sdesrozis** [easybuilders/easybuild-framework#2469]
(sorry for multiple post...)

Hello,
I would like to use a toolchain gimkl, meanning GCC + Intel MKL + Intel MPI. I have modified a HDF5 1.8.20 easybuild to enable gimkl-2017b toolchain (more or less equal to 2017a) and I have the following error during build step :`

```
error  "This Intel <math.h> is for use with only the Intel compilers!"
```

You can check that CPPFLAGS includes mkl headers (here math.h, but also intrinsics etc.) which are not compatible with GCC. These headers replace legacy ones but are for icc compilers. CPPFLAGS contains too much headers (ok with intel icc compiler but not gcc).

```
export CPPFLAGS="-I/tmp/install/software/MPI/GCC/6.4.0-2.28/impi/2017.3.196/imkl/2017.3.196/include -I/tmp/install/software/MPI/GCC/6.4.0-2.28/impi/2017.3.196/imkl/2017.3.196/mkl/include -I/tmp/install/software/MPI/GCC/6.4.0-2.28/impi/2017.3.196/imkl/2017.3.196/include -I/tmp/install/software/Compiler/GCCcore/6.4.0/zlib/1.2.11/include -I/tmp/install/software/Compiler/GCCcore/6.4.0/Szip/2.1.1/include"
```

The header /tmp/install/software/MPI/GCC/6.4.0-2.28/impi/2017.3.196/imkl/2017.3.196/include should not be included with GCC.

I tried prebuildopts and preconfigopts ('unset CPPFLAGS && ') but it doesn't work with python extensions...

Any idea to fix that issue ??

**Comment by akesandgren** [comment]
Has to be something else causing the problem. There is no math.h in mkl.

**Comment by boegel** [comment]
@sdesrozis As discussed in the EasyBuild Slack channel: please check whether your Intel MKL was installed with only MKL.

You can specify `components = ['intel-mkl']` in the easyconfig file in case you're tweaking the `sources` spec to use the tarball for the full Intel Parallel Studio (or whatever it's called these days)

**Comment by boegel** [comment]
We're making the `components = ['intel-mkl']` consistent in https://github.com/easybuilders/easybuild-easyconfigs/pull/6234

**Comment by guest1604** [comment]
@boegel Thanks for your help ! For my part, using `components = ['intel-mkl'] ` solved this issue.

However, we use "parallel_studio_xe_2017_update4.tgz" to provide "imkl 2017.3.196" and "impi 2017.3.196" (for "intel/2017b" and "gimkl/2017b" toolchains), and Intel installer asks a license, so we have to comment `kwargs['requires_runtime_license'] = False` in "impi.py" and "imkl.py" like below  :                                 
```
    def prepare_step(self, *args, **kwargs):
        if LooseVersion(self.version) >= LooseVersion('2017.2.174'):
            #kwargs['requires_runtime_license'] = False
            super(EB_impi, self).prepare_step(*args, **kwargs)
        else:
            super(EB_impi, self).prepare_step(*args, **kwargs)
```
```
    def prepare_step(self, *args, **kwargs):
        if LooseVersion(self.version) >= LooseVersion('2017.2.174'):
            #kwargs['requires_runtime_license'] = False
            super(EB_imkl, self).prepare_step(*args, **kwargs)
        else:
            super(EB_imkl, self).prepare_step(*args, **kwargs)
```

**Comment by boegel** [comment]
@guest1604: there's no need to change the easyblocks for this, you can do this in the easyconfig files as well, by including `requires_runtime_license = False`

```
$ eb -a -e IntelBase | grep requires
requires_runtime_license*   Boolean indicating whether or not a runtime license is required [default: True]
```

**Comment by guest1604** [comment]
@boegel Intel installer required an activation type so I have to use `requires_runtime_license = True` (I "use parallel_studio_xe_2017_update4.tgz" as source).

I tried this but I have the same error if I use `requires_runtime_license = True` or `requires_runtime_license = False` => `The product you are installing does not support  activation type. Use other\nactivation options.`

This easyconfig parameter is overrided by "impi.py" and "imkl.py" easyblocks since their version are greater than 2017.2.174. I put a print at the end of `prepare_step` to display the `requires_runtime_license` value :

```
(...)
     def prepare_step(self, *args, **kwargs):
        if LooseVersion(self.version) >= LooseVersion('2017.2.174'):
            kwargs['requires_runtime_license'] = False
            super(EB_imkl, self).prepare_step(*args, **kwargs)
        else:
            super(EB_imkl, self).prepare_step(*args, **kwargs)
        
        print("DEBUG: requires_runtime_license = %r") % kwargs['requires_runtime_license']
(...)
```
```
$ tail -1 imkl-2017.3.196-gimpi-2017b.eb
requires_runtime_license = True
```
```
$ eb imkl-2017.3.196-gimpi-2017b.eb
(...)
== preparing...
DEBUG: requires_runtime_license = False
== configuring...
(...)
```

**Comment by akesandgren** [comment]
@guest1604 Why aren't you just using the imkl/impi tar files as source for imkl/impi? It's much easier.

**Comment by boegel** [comment]
@guest1604 To change the override, we should:

* change the default value for `requires_runtime_license` in `IntelBase` to `None`
* set `requires_runtime_license` to `True` in `IntelBase` if it was left unspecified in the easyconfig file (to retain current behaviour)
* only set `requires_runtime_license` in `imkl.py` (& co) if it was left unspecified (i.e. if it's still set to `None`)

**Comment by guest1604** [comment]
Thanks @akesandgren and @boegel for your help.

Now I use the tar files specified by default in the easyconfig files and it works perfectly.
In the past, only the full parallel studio tar file was provided to me.

**Comment by boegel** [comment]
@guest1604 So, we can close this issue then?

**Comment by guest1604** [comment]
@boegel yes, you can close this issue. Thanks for your help !
