### ISSUE TITLE
Autogenerated EasyConfig overwrites existing file

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-framework#2503]
The autogenerated EasyConfig (by tweak.py) does not seem to check for existence of the file to generate. So if there is a (maybe not exactly matching) EasyConfig, then this gets overwritten.

This just happened to me:

- Create GPI2-1.3.0-GCCcore-6.4.0.eb in current directory
- Run eb --software=GPI2,1.3.0 --toolchain=GCCcore,6.4.0 -r
- EB fails with `Unable to find an easyconfig for the given specifications`
- GPI2-1.3.0-GCCcore-6.4.0.eb is missing !!!

Log output:

> 
> == 2018-05-17 16:38:53,732 tweak.py:410 INFO No easyconfig file for specified toolchain, but template is available.
> == 2018-05-17 16:38:53,735 tweak.py:176 WARNING Tweaking version: checksums cleared, verification disabled.
> == 2018-05-17 16:38:53,737 tweak.py:231 INFO Tweaked 'version' to '"1.3.0"'
> == 2018-05-17 16:38:53,738 tweak.py:231 INFO Tweaked 'toolchain' to '{'version': '6.4.0', 'name': 'GCCcore'}'
> == 2018-05-17 16:38:53,739 tweak.py:231 INFO Tweaked 'name' to '"GPI2"'
> == 2018-05-17 16:38:53,740 tweak.py:267 INFO Tweaked easyconfig file written to GPI2-1.3.0-GCCcore-6.4.0.eb
> == 2018-05-17 16:38:53,741 tweak.py:571 INFO Generated easyconfig file GPI2-1.3.0-GCCcore-6.4.0.eb, and using it to build the requested software.
> == 2018-05-17 16:38:53,798 build_log.py:158 ERROR EasyBuild crashed with an error (at ?:124 in __init__): Unable to find an easyconfig for the given specifications: {'toolchain': {'version': '6.4.0', 'nam    e': 'GCCcore'}, 'version': '1.3.0', 'toolchain_name': 'GCCcore', 'name': 'GPI2', 'toolchain_version': '6.4.0'}; to make EasyBuild try to generate a matching easyconfig, use the --try-X options  (at easybu    ild/main.py:104 in find_easyconfigs_by_specs)

I'd consider this bug as critical as it effectively deletes files from the user.

The bug seems to be here: https://github.com/easybuilders/easybuild-framework/blob/ca3bb3effaaa05a7de6515ed1e366a7b43decca7/easybuild/framework/easyconfig/tweak.py#L569

As no filename is passed `fp = None`, one is generated before calling `tweak_one`. As it is set there the check at https://github.com/easybuilders/easybuild-framework/blob/ca3bb3effaaa05a7de6515ed1e366a7b43decca7/easybuild/framework/easyconfig/tweak.py#L260 is not executed writing to the current directory instead of the temporary one.

Proposed solution: Delete the filename generation at https://github.com/easybuilders/easybuild-framework/blob/ca3bb3effaaa05a7de6515ed1e366a7b43decca7/easybuild/framework/easyconfig/tweak.py#L558 or also prefix it with tempdir.

**Comment by boegel** [comment]
@Flamefire How about adding making the `write_file` at https://github.com/easybuilders/easybuild-framework/blob/develop/easybuild/framework/easyconfig/tweak.py#L265 conditional on the target file not existing yet?
If it does exist we can either fall back to write to a temporary location, or fail with a clear error message.

In any case: you're absolutely right, blindly overwriting an existing file is pretty bad, we'll get this fixed in the next EasyBuild release, thanks a lot for reporting this.

**Comment by boegel** [comment]
@Flamefire proposed fix in https://github.com/easybuilders/easybuild-framework/pull/2504

**Comment by migueldiascosta** [comment]
fixed by #2504
