### ISSUE TITLE
CentOS 6 / Python 2.6 support

### ISSUE THREAD

**Issue by jbd** [easybuilders/easybuild-framework#2522]
Hello,

Im' trying to use easybuild on CentOS 6, and it looks like I've got some problem regarding https source download using SNI. Maybe it is a known issue for some time, or I've missed something in the documentation. Sorry if that's the case.  

From my understanding, the problem is around the ssl implementation. For example:

`
$ eb --debug hwloc-1.6.2-GCC-4.7.2.eb
[....]
== 2018-06-21 09:41:53,061 filetools.py:488 INFO Attempt 1 of downloading http://www.open-mpi.org/software/hwloc/v1.6/downloads/hwloc-1.6.2.tar.gz to /soft/adm/easybuild/sources/h/hwloc/hwloc-1.6.2.tar.gz failed, trying again...
== 2018-06-21 09:41:53,894 filetools.py:482 WARNING IOError occurred while trying to download http://www.open-mpi.org/software/hwloc/v1.6/downloads/hwloc-1.6.2.tar.gz to /soft/adm/easybuild/sources/h/hwloc/hwloc-1.6.2.tar.gz: <urlopen error [Errno 1] _ssl.c:492: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
[....]
`

Here is a simple reproducer:
```
#!/usr/bin/env python
# generates urllib2.URLError: <urlopen error [Errno 1] _ssl.c:492: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
# on CentOS 6.9 with python 2.6.6
import urllib2

url = "https://www.open-mpi.org/software/hwloc/v1.6/downloads/hwloc-1.6.2.tar.gz"
url_req = urllib2.Request(url, headers={'User-Agent': 'EasyBuild',  "Accept" : "*/*"})
urllib2.urlopen(url_req)
```

(https://gist.github.com/jbd/4db3e4c4b2eb74c466b9fc2585b1afa2)

Is there a way around this in the context of EasyBuild ? 

Further details below.

For example, 
```
$ cat /etc/centos-release 
CentOS release 6.9 (Final)
$ python --version
Python 2.6.6
``` 

```
$ eb --version
This is EasyBuild 3.6.1 (framework: 3.6.1, easyblocks: 3.6.1) on host brucciu.itcrowd
```

```
$ eb --show-config
#
# Current EasyBuild configuration
# (C: command line argument, D: default value, E: environment variable, F: configuration file)
#
buildpath      (E) = /soft/adm/easybuild/build
configfiles    (E) = /soft/adm/easybuild/conf/config.cfg
containerpath  (E) = /soft/adm/easybuild/containers
installpath    (E) = /soft/adm/easybuild
packagepath    (E) = /soft/adm/easybuild/packages
prefix         (E) = /soft/adm/easybuild
repositorypath (E) = /soft/adm/easybuild/ebfiles_repo
robot-paths    (D) = /soft/adm/easybuild/software/EasyBuild/3.6.1/lib/python2.6/site-packages/easybuild_easyconfigs-3.6.1-py2.6.egg/easybuild/easyconfigs
sourcepath     (E) = /soft/adm/easybuild/sources
```

```
$ eb --debug hwloc-1.6.2-GCC-4.7.2.eb
== temporary log file in case of crash /home/eb/eb-zqnIyY/easybuild-QfVm7N.log
== processing EasyBuild easyconfig /soft/adm/easybuild/software/EasyBuild/3.6.1/lib/python2.6/site-packages/easybuild_easyconfigs-3.6.1-py2.6.egg/easybuild/easyconfigs/h/hwloc/hwloc-1.6.2-GCC-4.7.2.eb
== building and installing hwloc/1.6.2-GCC-4.7.2...
== fetching files...
== FAILED: Installation ended unsuccessfully (build directory: /soft/adm/easybuild/build/hwloc/1.6.2/GCC-4.7.2): build failed (first 300 chars): Couldn't find file hwloc-1.6.2.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order): /soft/adm/easybuild/software/EasyBuild/3.6.1/lib/python2.6/site-packages/easybuild_easyconfigs-3.6.1-py2.6.egg/easybuild/easyconfigs/h/hwloc/h/hwloc/hwloc-1.6.2.tar.gz, /soft/adm/easy
== Results of the build can be found in the log file(s) /home/eb/eb-zqnIyY/easybuild-hwloc-1.6.2-20180621.094152.PxciI.log
ERROR: Build of /soft/adm/easybuild/software/EasyBuild/3.6.1/lib/python2.6/site-packages/easybuild_easyconfigs-3.6.1-py2.6.egg/easybuild/easyconfigs/h/hwloc/hwloc-1.6.2-GCC-4.7.2.eb failed (err: "build failed (first 300 chars): Couldn't find file hwloc-1.6.2.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order): /soft/adm/easybuild/software/EasyBuild/3.6.1/lib/python2.6/site-packages/easybuild_easyconfigs-3.6.1-py2.6.egg/easybuild/easyconfigs/h/hwloc/h/hwloc/hwloc-1.6.2.tar.gz, /soft/adm/easy")
```

Output log: https://gist.github.com/jbd/7e0a07b9b2c8295989d65bca5ababd51

**Comment by boegel** [comment]
@jbd Can you check whether `export PYTHONHTTPSVERIFY=0` (*exactly* that) fixes your problem?

See for https://www.python.org/dev/peps/pep-0493/ (extensive) context...

This is a breaking change in Python 2.7.12, but it may have been backported to the Python 2.6.x in CentOS 6...

**Comment by jbd** [comment]
@boegel Thank you for the pep link.

Looks the same with `export PYTHONHTTPSVERIFY=0`:

`
$ export PYTHONHTTPSVERIFY=0
$ eb --debug hwloc-1.6.2-GCC-4.7.2.eb
== temporary log file in case of crash /home/eb/eb-Cvdx4V/easybuild-C8jsEA.log
== processing EasyBuild easyconfig /soft/adm/easybuild/software/EasyBuild/3.6.1/lib/python2.6/site-packages/easybuild_easyconfigs-3.6.1-py2.6.egg/easybuild/easyconfigs/h/hwloc/hwloc-1.6.2-GCC-4.7.2.eb
== building and installing hwloc/1.6.2-GCC-4.7.2...
== fetching files...
== FAILED: Installation ended unsuccessfully (build directory: /soft/adm/easybuild/build/hwloc/1.6.2/GCC-4.7.2): build failed (first 300 chars): Couldn't find file hwloc-1.6.2.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order): /soft/adm/easybuild/software/EasyBuild/3.6.1/lib/python2.6/site-packages/easybuild_easyconfigs-3.6.1-py2.6.egg/easybuild/easyconfigs/h/hwloc/h/hwloc/hwloc-1.6.2.tar.gz, /soft/adm/easy
== Results of the build can be found in the log file(s) /home/eb/eb-Cvdx4V/easybuild-hwloc-1.6.2-20180621.134320.Jywti.log
ERROR: Build of /soft/adm/easybuild/software/EasyBuild/3.6.1/lib/python2.6/site-packages/easybuild_easyconfigs-3.6.1-py2.6.egg/easybuild/easyconfigs/h/hwloc/hwloc-1.6.2-GCC-4.7.2.eb failed (err: "build failed (first 300 chars): Couldn't find file hwloc-1.6.2.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order): /soft/adm/easybuild/software/EasyBuild/3.6.1/lib/python2.6/site-packages/easybuild_easyconfigs-3.6.1-py2.6.egg/easybuild/easyconfigs/h/hwloc/h/hwloc/hwloc-1.6.2.tar.gz, /soft/adm/easy")

Full output: https://gist.github.com/jbd/7fa7d99b9be45d4a6a6fea11a3bb2e3a

I'll try to find if the CentOS 6 python 2.6 include the change.

**Comment by jbd** [comment]
Update: a `grep -R PYTHONHTTPSVERIFY` inside the last python SRPM (http://vault.centos.org/6.9/os/Source/SPackages/python-2.6.6-66.el6_8.src.rpm) returns nothing.

**Comment by jbd** [comment]
Just an update to give additional info:
```
$ rpm -qa|grep python
python-setuptools-0.6.10-4el6_9.noarch
python-devel-2.6.6-66.el6_8.x86_64
python-libs-2.6.6-66.el6_8.x86_64
python-urlgrabber-3.9.1-11.el6.noarch
libproxy-python-0.3.0-10.el6.x86_64
python-virtualenv-12.0.7-1.el6.noarch
python-2.6.6-66.el6_8.x86_64
rpm-python-4.8.0-55.el6.x86_64
python-pycurl-7.19.0-9.el6.x86_64
python-iniparse-0.3.1-2.1.el6.noarch
```

I'm using a CentOS 6 singularity container to perform my tests (as mentioned in https://github.com/easybuilders/easybuild-framework/issues/2389#issuecomment-398760388). I'll try to reproduce it on a vanilla CentOS 6.9 up-to-date installation.

**Comment by sanjutimsina** [comment]
Hello,

I am facing the same issue when trying to build R on Centos 7/ Python 2.7.5. 

`$ eb R-4.0.0-foss-2020a.eb --robot
== temporary log file in case of crash /tmp/eb-bui9fttf/easybuild-719uaowr.log
== found valid index for /opt/software/EasyBuild/4.3.2/easybuild/easyconfigs, so using it...
== found valid index for /opt/software/EasyBuild/4.3.2/easybuild/easyconfigs, so using it...
== resolving dependencies ...
== processing EasyBuild easyconfig /opt/software/EasyBuild/4.3.2/easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-foss-2020a.eb
== building and installing UDUNITS/2.2.26-foss-2020a...
== fetching files...
== FAILED: Installation ended unsuccessfully (build directory: /application/ezbuildSoftware/build/UDUNITS/2.2.26/foss-2020a): build failed (first 300 chars): SSL issues with urllib2. If you are using RHEL/CentOS 6.x please install the python-requests and pyOpenSSL RPM packages and try again. (took 0 sec)
== Results of the build can be found in the log file(s) /tmp/eb-bui9fttf/easybuild-UDUNITS-2.2.26-20210315.094349.HSCru.log
ERROR: Build of /opt/software/EasyBuild/4.3.2/easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-foss-2020a.eb failed (err: 'build failed (first 300 chars): SSL issues with urllib2. If you are using RHEL/CentOS 6.x please install the python-requests and pyOpenSSL RPM packages and try again.')`

` eb --show-config
#
# Current EasyBuild configuration
# (C: command line argument, D: default value, E: environment variable, F: configuration file)
#
buildpath      (E) = /application/ezbuildSoftware/build
containerpath  (E) = /application/ezbuildSoftware/containers
installpath    (E) = /application/ezbuildSoftware
repositorypath (E) = /application/ezbuildSoftware/ebfiles_repo
robot-paths    (D) = /opt/software/EasyBuild/4.3.2/easybuild/easyconfigs
sourcepath     (E) = /application/ezbuildSoftware/sources`

`$ eb R-4.0.0-foss-2020a.eb -Dr
== temporary log file in case of crash /tmp/eb-q_vrry8s/easybuild-1rq97r9b.log
== found valid index for /opt/software/EasyBuild/4.3.2/easybuild/easyconfigs, so using it...
== found valid index for /opt/software/EasyBuild/4.3.2/easybuild/easyconfigs, so using it...
Dry run: printing build status of easyconfigs and dependencies
CFGS=/opt/software/EasyBuild/4.3.2/easybuild/easyconfigs
 * [x] $CFGS/m/M4/M4-1.4.18.eb (module: M4/1.4.18)
 * [x] $CFGS/b/Bison/Bison-3.5.3.eb (module: Bison/3.5.3)
 * [x] $CFGS/b/Bison/Bison-3.3.2.eb (module: Bison/3.3.2)
 * [x] $CFGS/z/zlib/zlib-1.2.11.eb (module: zlib/1.2.11)
 * [x] $CFGS/h/help2man/help2man-1.47.4.eb (module: help2man/1.47.4)
 * [x] $CFGS/f/flex/flex-2.6.4.eb (module: flex/2.6.4)
 * [x] $CFGS/b/binutils/binutils-2.34.eb (module: binutils/2.34)
 * [x] $CFGS/g/GCCcore/GCCcore-9.3.0.eb (module: GCCcore/9.3.0)
 * [x] $CFGS/h/help2man/help2man-1.47.12-GCCcore-9.3.0.eb (module: help2man/1.47.12-GCCcore-9.3.0)
 * [x] $CFGS/m/M4/M4-1.4.18-GCCcore-9.3.0.eb (module: M4/1.4.18-GCCcore-9.3.0)
 * [x] $CFGS/z/zlib/zlib-1.2.11-GCCcore-9.3.0.eb (module: zlib/1.2.11-GCCcore-9.3.0)
 * [x] $CFGS/b/Bison/Bison-3.5.3-GCCcore-9.3.0.eb (module: Bison/3.5.3-GCCcore-9.3.0)
 * [x] $CFGS/f/flex/flex-2.6.4-GCCcore-9.3.0.eb (module: flex/2.6.4-GCCcore-9.3.0)
 * [x] $CFGS/b/binutils/binutils-2.34-GCCcore-9.3.0.eb (module: binutils/2.34-GCCcore-9.3.0)
 * [x] $CFGS/p/pixman/pixman-0.38.4-GCCcore-9.3.0.eb (module: pixman/0.38.4-GCCcore-9.3.0)
 * [x] $CFGS/b/bzip2/bzip2-1.0.8-GCCcore-9.3.0.eb (module: bzip2/1.0.8-GCCcore-9.3.0)
 * [x] $CFGS/l/libtool/libtool-2.4.6-GCCcore-9.3.0.eb (module: libtool/2.4.6-GCCcore-9.3.0)
 * [x] $CFGS/n/ncurses/ncurses-6.2-GCCcore-9.3.0.eb (module: ncurses/6.2-GCCcore-9.3.0)
 * [x] $CFGS/l/libpng/libpng-1.6.37-GCCcore-9.3.0.eb (module: libpng/1.6.37-GCCcore-9.3.0)
 * [x] $CFGS/f/freetype/freetype-2.10.1-GCCcore-9.3.0.eb (module: freetype/2.10.1-GCCcore-9.3.0)
 * [x] $CFGS/e/expat/expat-2.2.9-GCCcore-9.3.0.eb (module: expat/2.2.9-GCCcore-9.3.0)
 * [x] $CFGS/g/gperf/gperf-3.1-GCCcore-9.3.0.eb (module: gperf/3.1-GCCcore-9.3.0)
 * [x] $CFGS/m/makeinfo/makeinfo-6.7-GCCcore-9.3.0.eb (module: makeinfo/6.7-GCCcore-9.3.0)
 * [x] $CFGS/p/pkg-config/pkg-config-0.29.2-GCCcore-9.3.0.eb (module: pkg-config/0.29.2-GCCcore-9.3.0)
 * [x] $CFGS/u/UnZip/UnZip-6.0-GCCcore-9.3.0.eb (module: UnZip/6.0-GCCcore-9.3.0)
 * [x] $CFGS/l/libreadline/libreadline-8.0-GCCcore-9.3.0.eb (module: libreadline/8.0-GCCcore-9.3.0)
 * [x] $CFGS/g/groff/groff-1.22.4-GCCcore-9.3.0.eb (module: groff/1.22.4-GCCcore-9.3.0)
 * [x] $CFGS/p/PCRE2/PCRE2-10.34-GCCcore-9.3.0.eb (module: PCRE2/10.34-GCCcore-9.3.0)
 * [x] $CFGS/l/libffi/libffi-3.3-GCCcore-9.3.0.eb (module: libffi/3.3-GCCcore-9.3.0)
 * [x] $CFGS/d/DB/DB-18.1.32-GCCcore-9.3.0.eb (module: DB/18.1.32-GCCcore-9.3.0)
 * [x] $CFGS/u/util-linux/util-linux-2.35-GCCcore-9.3.0.eb (module: util-linux/2.35-GCCcore-9.3.0)
 * [x] $CFGS/t/Tcl/Tcl-8.6.10-GCCcore-9.3.0.eb (module: Tcl/8.6.10-GCCcore-9.3.0)
 * [x] $CFGS/n/ncurses/ncurses-6.1.eb (module: ncurses/6.1)
 * [x] $CFGS/p/Perl/Perl-5.30.2-GCCcore-9.3.0.eb (module: Perl/5.30.2-GCCcore-9.3.0)
 * [x] $CFGS/f/fontconfig/fontconfig-2.13.92-GCCcore-9.3.0.eb (module: fontconfig/2.13.92-GCCcore-9.3.0)
 * [x] $CFGS/s/SQLite/SQLite-3.31.1-GCCcore-9.3.0.eb (module: SQLite/3.31.1-GCCcore-9.3.0)
 * [x] $CFGS/g/gettext/gettext-0.20.1.eb (module: gettext/0.20.1)
 * [x] $CFGS/a/Autoconf/Autoconf-2.69-GCCcore-9.3.0.eb (module: Autoconf/2.69-GCCcore-9.3.0)
 * [x] $CFGS/i/intltool/intltool-0.51.0-GCCcore-9.3.0.eb (module: intltool/0.51.0-GCCcore-9.3.0)
 * [x] $CFGS/a/Automake/Automake-1.16.1-GCCcore-9.3.0.eb (module: Automake/1.16.1-GCCcore-9.3.0)
 * [x] $CFGS/x/XZ/XZ-5.2.5-GCCcore-9.3.0.eb (module: XZ/5.2.5-GCCcore-9.3.0)
 * [x] $CFGS/a/Autotools/Autotools-20180311-GCCcore-9.3.0.eb (module: Autotools/20180311-GCCcore-9.3.0)
 * [x] $CFGS/l/libxml2/libxml2-2.9.10-GCCcore-9.3.0.eb (module: libxml2/2.9.10-GCCcore-9.3.0)
 * [x] $CFGS/l/libunwind/libunwind-1.3.1-GCCcore-9.3.0.eb (module: libunwind/1.3.1-GCCcore-9.3.0)
 * [x] $CFGS/g/GMP/GMP-6.2.0-GCCcore-9.3.0.eb (module: GMP/6.2.0-GCCcore-9.3.0)
 * [x] $CFGS/p/Python/Python-2.7.18-GCCcore-9.3.0.eb (module: Python/2.7.18-GCCcore-9.3.0)
 * [x] $CFGS/x/xorg-macros/xorg-macros-1.19.2-GCCcore-9.3.0.eb (module: xorg-macros/1.19.2-GCCcore-9.3.0)
 * [x] $CFGS/p/Python/Python-3.8.2-GCCcore-9.3.0.eb (module: Python/3.8.2-GCCcore-9.3.0)
 * [x] $CFGS/g/gettext/gettext-0.20.1-GCCcore-9.3.0.eb (module: gettext/0.20.1-GCCcore-9.3.0)
 * [x] $CFGS/n/nettle/nettle-3.6-GCCcore-9.3.0.eb (module: nettle/3.6-GCCcore-9.3.0)
 * [x] $CFGS/n/Ninja/Ninja-1.10.0-GCCcore-9.3.0.eb (module: Ninja/1.10.0-GCCcore-9.3.0)
 * [x] $CFGS/m/Mako/Mako-1.1.2-GCCcore-9.3.0.eb (module: Mako/1.1.2-GCCcore-9.3.0)
 * [x] $CFGS/m/Meson/Meson-0.55.1-GCCcore-9.3.0-Python-3.8.2.eb (module: Meson/0.55.1-GCCcore-9.3.0-Python-3.8.2)
 * [x] $CFGS/l/libpciaccess/libpciaccess-0.16-GCCcore-9.3.0.eb (module: libpciaccess/0.16-GCCcore-9.3.0)
 * [x] $CFGS/g/gzip/gzip-1.10-GCCcore-9.3.0.eb (module: gzip/1.10-GCCcore-9.3.0)
 * [x] $CFGS/p/PCRE/PCRE-8.44-GCCcore-9.3.0.eb (module: PCRE/8.44-GCCcore-9.3.0)
 * [x] $CFGS/x/X11/X11-20200222-GCCcore-9.3.0.eb (module: X11/20200222-GCCcore-9.3.0)
 * [x] $CFGS/l/libdrm/libdrm-2.4.100-GCCcore-9.3.0.eb (module: libdrm/2.4.100-GCCcore-9.3.0)
 * [x] $CFGS/g/GLib/GLib-2.64.1-GCCcore-9.3.0.eb (module: GLib/2.64.1-GCCcore-9.3.0)
 * [x] $CFGS/l/libglvnd/libglvnd-1.2.0-GCCcore-9.3.0.eb (module: libglvnd/1.2.0-GCCcore-9.3.0)
 * [x] $CFGS/c/cairo/cairo-1.16.0-GCCcore-9.3.0.eb (module: cairo/1.16.0-GCCcore-9.3.0)
 * [x] $CFGS/l/lz4/lz4-1.9.2-GCCcore-9.3.0.eb (module: lz4/1.9.2-GCCcore-9.3.0)
 * [x] $CFGS/z/zstd/zstd-1.4.4-GCCcore-9.3.0.eb (module: zstd/1.4.4-GCCcore-9.3.0)
 * [x] $CFGS/n/NASM/NASM-2.14.02-GCCcore-9.3.0.eb (module: NASM/2.14.02-GCCcore-9.3.0)
 * [x] $CFGS/c/cURL/cURL-7.69.1-GCCcore-9.3.0.eb (module: cURL/7.69.1-GCCcore-9.3.0)
 * [x] $CFGS/c/CMake/CMake-3.16.4-GCCcore-9.3.0.eb (module: CMake/3.16.4-GCCcore-9.3.0)
 * [x] $CFGS/l/libjpeg-turbo/libjpeg-turbo-2.0.4-GCCcore-9.3.0.eb (module: libjpeg-turbo/2.0.4-GCCcore-9.3.0)
 * [x] $CFGS/l/LibTIFF/LibTIFF-4.1.0-GCCcore-9.3.0.eb (module: LibTIFF/4.1.0-GCCcore-9.3.0)
 * [x] $CFGS/l/LLVM/LLVM-9.0.1-GCCcore-9.3.0.eb (module: LLVM/9.0.1-GCCcore-9.3.0)
 * [x] $CFGS/m/Mesa/Mesa-20.0.2-GCCcore-9.3.0.eb (module: Mesa/20.0.2-GCCcore-9.3.0)
 * [x] $CFGS/l/libGLU/libGLU-9.0.1-GCCcore-9.3.0.eb (module: libGLU/9.0.1-GCCcore-9.3.0)
 * [x] $CFGS/x/Xvfb/Xvfb-1.20.9-GCCcore-9.3.0.eb (module: Xvfb/1.20.9-GCCcore-9.3.0)
 * [x] $CFGS/t/Tk/Tk-8.6.10-GCCcore-9.3.0.eb (module: Tk/8.6.10-GCCcore-9.3.0)
 * [x] $CFGS/j/Java/Java-11.0.2.eb (module: Java/11.0.2)
 * [x] $CFGS/j/Java/Java-11.eb (module: Java/11)
 * [x] $CFGS/n/NLopt/NLopt-2.6.1-GCCcore-9.3.0.eb (module: NLopt/2.6.1-GCCcore-9.3.0)
 * [x] $CFGS/l/libsndfile/libsndfile-1.0.28-GCCcore-9.3.0.eb (module: libsndfile/1.0.28-GCCcore-9.3.0)
 * [x] $CFGS/i/ICU/ICU-66.1-GCCcore-9.3.0.eb (module: ICU/66.1-GCCcore-9.3.0)
 * [x] $CFGS/g/GCC/GCC-9.3.0.eb (module: GCC/9.3.0)
 * [x] $CFGS/s/Szip/Szip-2.1.1-GCCcore-9.3.0.eb (module: Szip/2.1.1-GCCcore-9.3.0)
 * [x] $CFGS/g/GSL/GSL-2.6-GCC-9.3.0.eb (module: GSL/2.6-GCC-9.3.0)
 * [x] $CFGS/l/libevent/libevent-2.1.11-GCCcore-9.3.0.eb (module: libevent/2.1.11-GCCcore-9.3.0)
 * [x] $CFGS/n/numactl/numactl-2.0.13-GCCcore-9.3.0.eb (module: numactl/2.0.13-GCCcore-9.3.0)
 * [x] $CFGS/h/hwloc/hwloc-2.2.0-GCCcore-9.3.0.eb (module: hwloc/2.2.0-GCCcore-9.3.0)
 * [x] $CFGS/u/UCX/UCX-1.8.0-GCCcore-9.3.0.eb (module: UCX/1.8.0-GCCcore-9.3.0)
 * [x] $CFGS/o/OpenBLAS/OpenBLAS-0.3.9-GCC-9.3.0.eb (module: OpenBLAS/0.3.9-GCC-9.3.0)
 * [x] $CFGS/g/GLPK/GLPK-4.65-GCCcore-9.3.0.eb (module: GLPK/4.65-GCCcore-9.3.0)
 * [x] $CFGS/l/libfabric/libfabric-1.11.0-GCCcore-9.3.0.eb (module: libfabric/1.11.0-GCCcore-9.3.0)
 * [x] $CFGS/g/Ghostscript/Ghostscript-9.52-GCCcore-9.3.0.eb (module: Ghostscript/9.52-GCCcore-9.3.0)
 * [x] $CFGS/p/PMIx/PMIx-3.1.5-GCCcore-9.3.0.eb (module: PMIx/3.1.5-GCCcore-9.3.0)
 * [x] $CFGS/j/JasPer/JasPer-2.0.14-GCCcore-9.3.0.eb (module: JasPer/2.0.14-GCCcore-9.3.0)
 * [x] $CFGS/o/OpenMPI/OpenMPI-4.0.3-GCC-9.3.0.eb (module: OpenMPI/4.0.3-GCC-9.3.0)
 * [x] $CFGS/g/gompi/gompi-2020a.eb (module: gompi/2020a)
 * [x] $CFGS/h/HDF5/HDF5-1.10.6-gompi-2020a.eb (module: HDF5/1.10.6-gompi-2020a)
 * [x] $CFGS/s/ScaLAPACK/ScaLAPACK-2.1.0-gompi-2020a.eb (module: ScaLAPACK/2.1.0-gompi-2020a)
 * [x] $CFGS/f/FFTW/FFTW-3.3.8-gompi-2020a.eb (module: FFTW/3.3.8-gompi-2020a)
 * [x] $CFGS/f/foss/foss-2020a.eb (module: foss/2020a)
 * [ ] $CFGS/u/UDUNITS/UDUNITS-2.2.26-foss-2020a.eb (module: UDUNITS/2.2.26-foss-2020a)
 * [ ] $CFGS/l/LittleCMS/LittleCMS-2.9-GCCcore-9.3.0.eb (module: LittleCMS/2.9-GCCcore-9.3.0)
 * [ ] $CFGS/i/ImageMagick/ImageMagick-7.0.10-1-GCCcore-9.3.0.eb (module: ImageMagick/7.0.10-1-GCCcore-9.3.0)
 * [ ] $CFGS/r/R/R-4.0.0-foss-2020a.eb (module: R/4.0.0-foss-2020a)
== Temporary log file(s) /tmp/eb-q_vrry8s/easybuild-1rq97r9b.log* have been removed.
== Temporary directory /tmp/eb-q_vrry8s has been removed.`
