### ISSUE TITLE
Failed to obtain class for EB_EasyBuildMeta easyblock for running eb as root

### ISSUE THREAD

**Issue by davidliu-CAS** [easybuilders/easybuild-framework#2531]
I ran into the "Failed to obtain class for EB_EasyBuildMeta easyblock" error on RHEL 7.2 with EasyBuild 3.6.1 (installed under root) and Lmod 6.5.1. The system was freshly installed. The last successfully built modules were ESMF/7.0.2-intel-2017b and Trilinos/12.4.2-intel-2015b-python-2.7.11 as root . eb suddenly stopped working no matter what package I have tried to install. the debug log was attached.  
The problem looked similar to #2383,  but the eb file and easybuildmeta.py in /public/software/easybuild/software/EasyBuild/3.6.1 were good. Thanks!

My configuration is:
allow-use-as-root-and-accept-consequences (C) = True
buildpath (D) = /root/.local/easybuild/build
containerpath (D) = /root/.local/easybuild/containers
installpath (D) = /root/.local/easybuild
repositorypath (D) = /root/.local/easybuild/ebfiles_repo
robot-paths (D) = /public/software/easybuild/software/EasyBuild/3.6.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.6.1-py2.7.egg/easybuild/easyconfigs
sourcepath (D) = /root/.local/easybuild/sources

Command
python -c "import easybuild.easyblocks.easybuildmeta; print easybuild.easyblocks.easybuildmeta.file" returns:

Traceback (most recent call last):
File "", line 1, in 
ImportError: No module named easybuildmeta

[easybuild-NHObwD.log](https://github.com/easybuilders/easybuild-framework/files/2183290/easybuild-NHObwD.log)

**Comment by boegel** [comment]
@davidliu-CAS What does `python -c "import easybuild.easyblocks; print easybuild.easyblocks.__path__"` print?

How are you running `eb`? While logged in as root, or via `sudo`? Do you load the `EasyBuild` module as root?

**Comment by davidliu-CAS** [comment]
logged in as root, and EasyBuild was loaded as root.
python -c "import easybuild.easyblocks; print easybuild.easyblocks.__path__" returns:
['/public/software/easybuild/software/EasyBuild/3.6.1/lib/python2.7/site-packages/easybuild_easyblocks-3.6.1-py2.7.egg/easybuild/easyblocks', '/public/software/easybuild/software/EasyBuild/3.6.1/lib/python2.7/site-packages/easybuild_easyblocks-3.6.1-py2.7.egg/easybuild/easyblocks/r']

**Comment by boegel** [comment]
@davidliu-CAS That's not what it's supposed to be... You should see an entry for the top-level + every letter `a-z`, while you are only getting one for `r` + the top-level...

What does this return?

```
ls -l /public/software/easybuild/software/EasyBuild/3.6.1/lib/python2.7/site-packages/easybuild_easyblocks-3.6.1-py2.7.egg/easybuild/easyblocks
```
and
```
ls -l /public/software/easybuild/software/EasyBuild/3.6.1/lib/python2.7/site-packages/easybuild_easyblocks-3.6.1-py2.7.egg/easybuild/easyblocks/e
```

**Comment by davidliu-CAS** [comment]
@boegel Thank you!  it seems like the zero size file \_\_init\_\_.py in the a-z folders except r is missing, which caused the problem. I ran touch \_\_init\_\_.py in each folder and eb runs ok now. Thank you very much!

>ls -l /public/software/easybuild/software/EasyBuild/3.6.1/lib/python2.7/site-packages/easybuild_easyblocks-3.6.1-py2.7.egg/easybuild/easyblocks
total 108
drwxr-xr-x. 2 root root   33 Jun 28 10:05 0
drwxr-xr-x. 2 root root 4096 Jun 28 10:05 a
drwxr-xr-x. 2 root root 4096 Jun 28 10:05 b
drwxr-xr-x. 2 root root 4096 Jun 28 10:05 c
drwxr-xr-x. 2 root root 4096 Jun 28 10:05 d
drwxr-xr-x. 2 root root 4096 Jun 29 14:39 e
drwxr-xr-x. 2 root root 4096 Jun 28 10:05 f
drwxr-xr-x. 2 root root 4096 Jun 28 10:05 g
drwxr-xr-x. 2 root root 8192 Jun 27 21:05 generic
drwxr-xr-x. 2 root root 4096 Jun 28 10:05 h
drwxr-xr-x. 2 root root 4096 Jun 28 10:05 i
-rw-r--r--. 1 root root 3169 Jun 16 03:56 __init__.py
-rw-r--r--. 1 root root 1897 Jun 16 03:56 __init__.pyc
-rw-r--r--. 1 root root 1897 Jun 16 03:56 __init__.pyo
drwxr-xr-x. 2 root root   89 Jun 28 10:05 j
drwxr-xr-x. 2 root root   33 Jun 28 10:05 k
drwxr-xr-x. 2 root root 4096 Jun 28 10:05 l
drwxr-xr-x. 2 root root 4096 Jun 28 10:05 m
drwxr-xr-x. 2 root root 4096 Jun 28 10:05 n
drwxr-xr-x. 2 root root 4096 Jun 28 10:05 o
drwxr-xr-x. 2 root root 4096 Jun 28 10:05 p
drwxr-xr-x. 2 root root 4096 Jun 28 10:05 q
drwxr-xr-x. 2 root root 4096 Jun 20 06:38 r
drwxr-xr-x. 2 root root 4096 Jun 28 10:05 s
drwxr-xr-x. 2 root root 4096 Jun 28 10:05 t
drwxr-xr-x. 2 root root   68 Jun 28 10:05 u
drwxr-xr-x. 2 root root 4096 Jun 28 10:05 v
drwxr-xr-x. 2 root root 4096 Jun 28 10:05 w
drwxr-xr-x. 2 root root 4096 Jun 28 10:05 x
drwxr-xr-x. 2 root root   33 Jun 28 10:05 y
drwxr-xr-x. 2 root root   33 Jun 28 10:05 z

before touch
> ll z
total 4
-rw-r--r--. 1 root root 238 Jun 16 03:56 \_\_init\_\_.pyc

after touch
>ll z
total 4
-rw-r--r--  1 root root   0 Jul 12 10:32 \_\_init\_\_.py
-rw-r--r--. 1 root root 238 Jun 16 03:56 \_\_init\_\_.pyc
