### ISSUE TITLE
get_software_root software root for binutils was not found in environment

### ISSUE THREAD

**Issue by scroogie** [easybuilders/easybuild-framework#2537]
I was evaluating a new installation stack using EASYBUILD_MINIMAL_TOOLCHAINS=1, but I always receivee this error when installing intel-2018a:

== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/M4/1.4.18/GCCcore-6.4.0): build failed (first 300 chars): get_software_root software root for binutils was not found in environment

The installation of 2018b before worked, though. Any idea what I might be doing wrong?

**Comment by ocaisa** [comment]
Can you provide a debug log? I don't understand why `get_software_root` is even being called, it doesn't appear in the `ConfigureMake` easyblock used by `M4`

**Comment by ocaisa** [comment]
Hmm, I can't reproduce this with the default naming scheme. What naming scheme are you using? If you do an extended dry run with `-x` and then load the modules as described there does your module tool complain?

**Comment by ocaisa** [comment]
I just tried it with `HierarchicalMNS` and also failed to reproduce your problem there. Do you use `filter-deps` for `binutils` by any chance?

**Comment by scroogie** [comment]
We are not using filter-deps, but indeed we are trying the CategorizedModuleNamingScheme in this prefix. I'll try the dry-run in a minute.

**Comment by scroogie** [comment]
Okay, thanks to your pointers, I have found the problem! It was picking up an external module for binutils which obviously doesn't set the EBROOTBINUTILS variable! Sorry for the noise and thanks again for your help!
