### ISSUE TITLE
Bootstrapping for EasyBuild doesn't work

### ISSUE THREAD

**Issue by grind3** [easybuilders/easybuild-framework#2541]
Hello,

I try to install EasyBuild by bootstrapping it, but I get the following the error.

[sv@headnode ~]$ curl -O https://raw.githubusercontent.com/easybuilders/easybuild-framework/develop/easybuild/scripts/bootstrap_eb.py

[sv@headnode ~]$ python bootstrap_eb.py EasyBuild

[[ERROR]] Failed to determine PyPI package URL for vsc-install:

Can someone help me?

Best regards

**Comment by ocaisa** [comment]
`vsc-install` is a requirement before running the bootstrapping process. Please take a look at 
https://easybuild.readthedocs.io/en/latest/Installation.html
and in particular
https://easybuild.readthedocs.io/en/latest/Installation.html#requirements

**Comment by boegel** [comment]
Actually, @grind3's expectation was correct, `vsc-install` should be installed as a part of the bootstrapping process...

I can't reproduce the problem in an environment where `vsc-install` is not available yet though. Maybe this was a temporary problem with PyPI?
