### ISSUE TITLE
Feature request: --hide-all-deps

### ISSUE THREAD

**Issue by casparvl** [easybuilders/easybuild-framework#2543]
I'd like to hide ALL dependencies (I'll probably come up with a pull request for a '--hide-all-deps' option), as I only want my users to see the software I have in a build list (all of this software is built one by one with eb [software] -r). 

Providing --hide-deps with an exhaustive list of all possible software that might be in the dependency lists is both unfeasible and ugly. I already implemented a --hide-all-deps in a local copy, it only requires 3 or 4 lines of code... I'll come up with a pull request, this issue is just for 'documenting' the feature request :)

**Comment by akesandgren** [comment]
You are likely going to shoot yourself in the foot by using this.

Take for example TensorFlow and Keras (there are multiple other examples too, I just picked one).
You want to install TensorFlow as a user visible module since users are going to use it directly.
Then installing Keras, a top level user visible module, which depends on TensorFlow, Theano (also user visible) and a couple of other things that you, as per your description above, would have installed as hidden deps. Here you can't use --hide-all-deps.
There are likely more complex cases too, and you would probably end up being able to use it only very infrequently except, perhaps, at the very initial stages of software installation.

I can see the allure of having it, but I strongly think it will be mostly unused even for you.

**Comment by casparvl** [comment]
> Here you can't use --hide-all-deps.
You mean because, when installing Keras, EasyBuild will fail to find that TensorFlow is already present as non-hidden modules? https://github.com/easybuilders/easybuild-framework/issues/2542

I think we may first need to agree on what EasyBuild should do in that case. In my view, it should just pick up on the fact that TensorFlow is already present as a non-hidden module, and simply pick up that non-hidden module as a dependency. In that case, there is no problem installing everything with --hide-all-deps. The only (minor) thing is that if you then build TensorFlow explicitly (i.e. eb Tensorflow-*.eb), EasyBuild will reinstall it and create a non-hidden module, next to the hidden module. A bit of a waste of time to reinstall, but no real issue.

Current behaviour is that EasyBuild will say "A hidden module for Tensorflow is missing, hence I will install Tensorflow, and create a hidden module". It will install TensorFlow in the same software directory it was already present in when it was installed as non-hidden. In the end, you will end up with 1 software installation, with 2 modules (a hidden & a non-hidden) referring to it. Again, no real issue (it will work), but this seems a bit silly.

**Comment by casparvl** [comment]
Maybe I should take the argument one step back: what is the intended usage of hide-deps?

I think it is to stop cluttering of your environment with e.g. 5 versions of zlib, just because your robot installations install these. So, you set hide-deps=zlib. Now, you probably also want to offer your users one visible version of zlib that they can link against when building their own software. So, you install zlib-1.2.11 for that, as a visible module, so that all your users nicely link to one version (and all you HPC advisors writing EasyConfigs as well btw :)). Currently, EasyBuild will recompile that zlib-1.2.11, install in the same software directory as where it was installed as a hidden dependency (waste of time for the recompilation, but not a huge problem) and create an unhidden zlib/1.2.11 module next to the zlib/.1.2.11 module.

Do you agree this would be the 'intended' use of --hide-deps? And do you think that EasyBuild behavious the way it should in this scenario? (ideally, I'd say it leaves the recompilation and simply creates an unhidden module, next to the hidden one. I.e. as if you do a --module-only. But, that's a 'nice to have')

**Comment by jose-d** [comment]
I like this idea too. For example, software I am working on now, https://cadabra.science, has in total 72 dependencies. (GTK+.. ). That's obfuscating the list of modules a lot..

I'd consider to add additional option `--show-deps [list of software to be not hidden]`, to white-list modules from being hidden by `--hide-all-deps`.

Is there any consensus if such a PR @casparvl proposed above would be merged? If yes, I could take a look and write it. I'm just too lazy to maintain site-specific fork of EB.

**Comment by boegel** [comment]
If someone else implements support for this in a clean way, I don't think there would be strong opposition for merging it in, we have other features supported where you can easily shoot yourself in the foot.

One question is what to do with the `toolchain`, which is sort of a depedency too: does that get hidden when using `--hide-all-deps`? What about with dependencies that are already installed (non-hidden)?

Note that Lmod has an easy way of making installed modules invisible (i.e. have them not show up in `module avail`), without having to rename the actual module files as hidden files (and thus without affecting existing `module load` statements in other modules or job scripts).

**Comment by thiagoabdo** [comment]
For me this feature would be very useful, right now we are hiding all possible easyconfigs with help of find and cut, but this is sub optimal.

Answering your question, I think that if the module is already installed as visible it should use the visible one. And if you are installing something that is installed as hidden it should only create the new link to the hidden(but that was being discussed in #2542) (but that is just my opinion, I can live with the idea of performing two installations for now).

Don't really have a opinion to what to do with toolchain, I believe that they should be hidden as well.

Casparvl implementation is only missing testcases(and update to the last version)?

**Comment by casparvl** [comment]
Hm, I kind of abandoned this approach since the 'need' for it became a lot less with more recent toolchains where the community stuck to the 'one version per dependency per toolchain generation' approach. I guess it could still be useful in casese where you would _never_ want dependencies to be visible.

I must admit I don't really remember in which stage I 'left' this PR. I vaguely remember 'worked' in the sense that it created all deps as hidden modules, but there was some quirky behaviour if a module was already installed as hidden dependency (e.g.  module `.A` ), and was then install it explicitely (i.e. `eb A.eb`). I think EasyBuild right now will conclude that software `A` is not installed yet and redo the installation or something. I don't know, make sure you check both scenarios.

I.e.
1. `.A` is already installed, and run an `eb A.eb`, or `A` is already installed
2.  Run a `eb B.eb` where `B` has a dep on `A` so that it will 'try' to install a `.A`).

The behaviour you would _want_ is probably that in the first case the existing module is simply copied or symlinked from `.A` to `A`, so that both exist. In the second case, you probably simply want to link against the _non-hidden_ module `A`, i.e. don't duplicate/symlink it as `.A`. But... that's just my opinion.

**Comment by thiagoabdo** [comment]
1. I do think that it should happen that way, I would be interested to pickup that issue(do not think that this one exists now) after I am done with this one, for now I can live with easybuild rebuild it.

2. Yes, I agree with you. 
But then how to handle if the user uses --force with --hide-all-deps? Should we just rebuild everything as hidden? Or rebuild everything and keep what is hidden hidden and what is visible visible.

It would be probably easier to do the behavior that is done now, if I asked to build something with a hidden module just build it as hidden(even if it exist as visible). And then we could continue the discussion about using the visible module when I ask for the hidden one in this #2542 . 

What you think?

**Comment by casparvl** [comment]
> But then how to handle if the user uses --force with --hide-all-deps? Should we just rebuild everything as hidden? Or rebuild everything and keep what is hidden hidden and what is visible visible.

I'm not sure I see this issue: a `--force` will never rebuild _dependencies_, right? Only the module itself. I.e. if `A` is a dependency for `B`, an `eb B.eb --force --hide-all-deps` should rebuild `B` and recreate `B`'s modulefile, but NOT touch `A` or `.A`, regardless of which of the two existed.

Anyway, I think you are right. Probably, we should have the discussion on completing the `--hide-all-deps` PR here https://github.com/easybuilders/easybuild-framework/pull/2544 and just have a separate discussion on how EB should behave / be changed in order to handle cases where a non-hidden module already exists, but a hidden module is asked for in https://github.com/easybuilders/easybuild-framework/issues/2542

I'll close this issue :)
