### ISSUE TITLE
EasyBuild installs FFTW/.3.3.7-gompi-2018a more times

### ISSUE THREAD

**Issue by grind3** [easybuilders/easybuild-framework#2545]
Hello,

I'm new to EasyBuild and I'm trying to install OpeFOAM using EasyBuild.
I used the following command to install it. 

[sw@cluster ~]$ eb --hide-deps=OpenMPI,Autotools,GMP,MPFR,OpenBLAS,LLVM,Eigen,pkg-config,ScaLAPACK,nettle,Mako,Mesa,libGLU,CGAL,GCCcore,Python,FFTW,libffi --hide-toolchains=GCCcore,gompi --filter-deps='M4,zlib,help2man,M4,Bison,flex,binutils,ncurses,libreadline,CMake,METIS,bzip2,Tcl,expat,HDF5,SQLite,X11,SCOTCH,libpng,Autoconf,Automake,libtool,gettext,util-linux,GLib,PCRE,Boost,XZ,libxml2,libdrm,hwloc,numactl' -D OpenFOAM-5.0-20180108-foss-2018a.eb

Every thing was ok till EasyBuild has tried to install FFTW/.3.3.7-gompi-2018a. EasyBuild installed it more times and is still trying to install it again and again without changing to the next software.
And it give me no errors, that help me to find the problem.

== building and installing gompi/.2018a...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully
== Results of the build can be found in the log file(s) /home/centos/EasyBuild/software/gompi/2018a/easybuild/easybuild-gompi-2018a-20180802.100945.log
== processing EasyBuild easyconfig /home/sw/EasyBuild/software/EasyBuild/3.6.2/lib/python2.7/site-packages/easybuild-easyconfigs/easybuild/easyconfigs/f/FFTW/FFTW-3.3.7-gompi-2018a.eb
== building and installing FFTW/.3.3.7-gompi-2018a...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...

Can some one help me.
thanks in advance

Best Regards

**Comment by migueldiascosta** [comment]
@grind3 this is correct, it's building for different precisions (single, double, long double, quad), see https://github.com/easybuilders/easybuild-easyblocks/blob/4f827319b8d1aaef40d832f346260a851a9bcd00/easybuild/easyblocks/f/fftw.py#L148

did it finish after the fourth?

**Comment by grind3** [comment]
It takes time I'll let you know when it finished.

Thanks for your help

**Comment by migueldiascosta** [comment]
if you look at the temporary log file you can get a clearer picture of what is happening, but I suppose the output to stdout could be made clearer...

**Comment by grind3** [comment]
do you mean this file?
temporary log file in case of crash /tmp/eb-3Xdl9f/easybuild-ag1rRQ.log
It tells me about the crash cases, but in this case EasyBuild didn't crashed.
I'm waiting till the fourth testing of fftw is finished und tell you if it change to the next software or not.

**Comment by grind3** [comment]
It changed to the next software. I was just impatient to wait and thought easybuild trying to install fftw more times thanks for your help

Best Regards

**Comment by migueldiascosta** [comment]
closing and following up the output clarification on the easyblocks issue
