### ISSUE TITLE
Support for buildininstalldir=True and multiple compilations

### ISSUE THREAD

**Issue by victorusu** [easybuilders/easybuild-framework#2556]
Easybuild always deletes the install dir, if one attempts to combine several compilations and buildinstalldir = True inside the same easyconfig.

Example
```
buildininstalldir=True
configopts = [
    " configopts1 ",
    " configopts2",
    " configopts3",
]
```

The installation process will perform the installation using `configopts1`, then using`configopts2`, then `configopts3`. But the `installdir` will only contain the build that used `configopts3`. 

Even if I set to the easyblock
```
def install_step(self):
    ...
    self.cfg["keeppreviousinstall"] = True
    self.cfg["cleanupoldbuild"] = False
    self.cfg["cleanupoldinstall"] = False
```

**Comment by boegel** [comment]
fixed in #2724, thanks for reporting this @victorusu!
