### ISSUE TITLE
Add OpenMP flags to LDFLAGS

### ISSUE THREAD

**Issue by wpoely86** [easybuilders/easybuild-framework#2558]
Currenty we only add openmp flags to `CFLAGS` but we also need it in `LDFLAGS` to link with `libgomp`/`libiomp`/...

**Comment by boegel** [comment]
@wpoely86 Did you have a particular use case in mind for this?

Why hasn't this popped up earlier yet?

**Comment by wpoely86** [comment]
in principle you need to link to `libgomp` or `libiomp` or it will fail to build. I had some software were I had to do this manually. 

I'm not sure why this isn't popping up everywhere? It leaks through from `CFLAGS` or the compiler is something smart enough?

**Comment by boegel** [comment]
@wpoely86 Do you remember for which specific packages you needed this?

Probably `-fopenmp` in `$CFLAGS` helps to dance around this in most cases...

**Comment by wpoely86** [comment]
No longer relevant?
