### ISSUE TITLE
Set enable_templating false before calling run_hook

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-framework#2563]
At the moment, any hook that need to change anything more complicated than a pure string need to do
self.cfg.enable_templating = False
make change
self.cfg.enable_templating = True (or actually reset it to it's previous value)

This is not something the hooks should have to deal with.

**Comment by akesandgren** [comment]
As @boegel commented in slack, that might break existing hooks that want to grab templated values

**Comment by akesandgren** [comment]
Already dealt with in the upcoming EB 3.7.0 by only doing this for parse_hook

**Comment by boegel** [comment]
@akesandgren This should still probably be documented clearly for the other hooks, since it's quite confusing to write code that makes a change only to notice the change seems to be disappearing in thin air... I'll look into that.

**Comment by boegel** [comment]
PR for docs update opened, see https://github.com/easybuilders/easybuild/pull/449

**Comment by boegel** [comment]
docs update merged, so closing this...
