### ISSUE TITLE
Dumping parsed easyconfig files

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-framework#2565]
With #2562 we introduce the capability of making modifications to the easyconfig file that is read from disk in a (potentially) non-reproducible way.

At https://github.com/easybuilders/easybuild-framework/blob/develop/easybuild/framework/easyblock.py#L2869 there is already a feature that dumps the final parsed easyconfig to the installation directory (in a `reprod` subdir).  This was originally introduced for minimal toolchains but since (some level of) subtoolchain resolution is now the default, and because of the new hook, this should be done more widely.

**Comment by akesandgren** [comment]
FYI, the file in the reprod contains an easyconfig with the changes in place. I just checked.

**Comment by ocaisa** [comment]
I expected so, the issue is just then in what cases do we trigger that dump, currently it's only done if you use minimal toolchains but given that subtoolchain resolution is now the default, I don't really see a good reason not to do it in all cases...especially since it does zero harm and saves us from having to create complicated logic.

**Comment by boegel** [comment]
fixed in #2574, thanks @ocaisa!
