### ISSUE TITLE
GC3Pie deprecation warning for use of Engine.stats

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#2572]
```
/tmp/426290700/lib/python2.6/site-packages/easybuild_framework-3.7.0.dev0-py2.6.egg/easybuild/tools/job/gc3pie.py:269: DeprecationWarning: Deprecated method `Engine.stats()` called -- please use `Engine.counts()` instead
  stats = self._engine.stats(only=Application)
```

Thoughts on this @riccardomurri?

**Comment by riccardomurri** [comment]
It's what the message says: a method changed name from 2.4 and 2.5, and EB's code is using the old method name, which is compatible with both GC3Pie 2.4 and 2.5.

It's easy to switch that line to use `self._engine.counts(only=Application)` but that would no longer work with GC3Pie 2.4.

**Comment by boegel** [comment]
@riccardomurri We increased the minimal version to 2.5.0 in https://github.com/easybuilders/easybuild-framework/pull/2554, so we should switch to `.counts()`.

Is that just a drop-in replacement? (yes, I'm lazy, it's Sunday, I'm allowed to be ;-))

**Comment by riccardomurri** [comment]
Yes, just replace `.stats` with `.counts` :-)  I can do a PR but tomorrow ;-)

**Comment by boegel** [comment]
@riccardomurri How does `.counts()` relate to `init_counts_for`?

EasyBuild now does a call to `init_stats_for` (which doesn't exist), and just ignores it when the method doesn't exist. That's probably not wise, should be changed to `init_counts_for` to ensure that `counts()` works?

**Comment by boegel** [comment]
@riccardomurri see #2573

**Comment by boegel** [comment]
let's follow up in the PR... :)
