### ISSUE TITLE
Bootstrap install fails

### ISSUE THREAD

**Issue by mwaldron104** [easybuilders/easybuild-framework#2598]
I get the following error when I try to bootstrap install EasyBuild.

$ ▶ python bootstrap_eb.py $EASYBUILD_PREFIX
[[INFO]] EasyBuild bootstrap script (version 20180925.01, MD5: 4e568883f293f94ade46a14d25cb6b94)
[[INFO]] Found Python 2.7.12 (default, Aug 16 2016, 13:23:44) ; [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

[[INFO]] Installation prefix /nas/longleaf/home/mwaldron/.local/easybuild
[[INFO]] Found module command '/nas/longleaf/apps/lmod/lmod/libexec/lmod' via $LMOD_CMD (Lmod), so using it.
[[INFO]] Suitable setuptools installation already found, skipping stage 0...

[[INFO]] +++ STAGE 1: installing EasyBuild in temporary dir with easy_install...

[[INFO]] installing EasyBuild with 'easy_install --quiet --upgrade --prefix=/tmp/tmpbtsWIs/eb_stage1 easybuild'
[[INFO]] running post install command 'easy_install --upgrade --prefix=/tmp/tmpbtsWIs/eb_stage1 vsc-base'
Traceback (most recent call last):
  File "bootstrap_eb.py", line 1080, in <module>
    main()
  File "bootstrap_eb.py", line 872, in main
    templates = stage1(tmpdir, sourcepath, distribute_egg_dir, forcedversion)
  File "bootstrap_eb.py", line 614, in stage1
    import vsc.utils.fancylogger
  File "/nas/longleaf/apps/python/2.7.12/lib/python2.7/site-packages/vsc/utils/__init__.py", line 30, in <module>
    pkg_resources.declare_namespace(__name__)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2082, in declare_namespace
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2098, in declare_namespace
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2048, in _handle_ns
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2067, in _rebuild_mod_path
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2065, in position_in_sys_path
ValueError: '/nas/longleaf/apps/python/2.7.12/lib/python2.7/site-packages' is not in list

The above path is to the python installation I am using.

$ ▶ python -V
Python 2.7.12

$ ▶ type module
module is a function
module () 
{ 
    eval $($LMOD_CMD bash "$@");
    [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}

$ ▶ type -f module
-bash: type: module: not found

$ ▶ module --version

Modules based on Lua: Version 6.0.24 (6.0.24-15-g371d96f) 2015-11-30 08:17
    by Robert McLay mclay@tacc.utexas.edu

$ ▶ module av EasyBuild

Use "module spider" to find all possible modules.
Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".

 $ ▶ which -a eb
/usr/bin/which: no eb in (/nas/longleaf/apps/python/2.7.12/bin:/nas/longleaf/apps/python/2.7.12/llvm/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/nas/longleaf/apps/afni/16.3.09/abin:/nas/longleaf/home/mwaldron/.local/bin:/nas/longleaf/home/mwaldron/bin)

**Comment by boegel** [comment]
@mwaldron104 Do you mind collecting the output of the bootstrap script after setting `$EASYBUILD_BOOTSTRAP_DEBUG`? As follows:

```
export EASYBUILD_BOOTSTRAP_DEBUG=1
python bootstrap_eb.py $EASYBUILD_PREFIX 2>&1 | tee log.txt
```

And then provide the contents of `log.txt`, preferably via a gist (see https://gist.github.com/)

**Comment by mwaldron104** [comment]
@boegel Actually I just got past this error by uninstalling vsc-install and vsc-base from the python installation I was using and letting the bootstrap script install its own. I've gotten further, but it's now complaining that my Lmod version is too old, 6.0.24 vs. 6.6.3 required. I'll have to see if I can update that. Thanks.

**Comment by boegel** [comment]
@mwaldron104 That indeed explains the problem you were seeing.

We have increased the required Lmod version significantly in the EasyBuild v3.7.0 release, indeed. (and we're lower it slightly to only require 6.5.1 soon, but that's not going to help you)

I highly recommend updating your Lmod installation. If that's not an option on the short term, you can install the previous EasyBuild version, by bootstrapping after running `export EASYBUILD_BOOTSTRAP_FORCE_VERSION=3.6.2`.
