### ISSUE TITLE
Installation directory creation with parallel build

### ISSUE THREAD

**Issue by vanzod** [easybuilders/easybuild-framework#2628]
In our cluster the software stack is read-only mounted on all gateways and compute nodes with the exception of the build nodes. When submitting a parallel build with `--job` from a gateway, EasyBuild attempts to create the build directory on the gateway in order to prevent a race condition [1]. However in our setup this fails with a `Read-only file system` error, preventing us from submitting a parallel build to Slurm.

It would be useful for us to either demote the error to a warning or having an option for not creating the directory in the submitting EasyBuild process.

[1] https://github.com/easybuilders/easybuild-framework/blob/master/easybuild/framework/easyblock.py#L1665

**Comment by boegel** [comment]
fixed in #2629, thanks @vanzod!
