### ISSUE TITLE
Add ability to archive easyblocks

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-framework#2633]
Based on a question that came up at the workshop in Birmingham 2018-10-22.

**Comment by boegel** [comment]
This should go into the `easybuild/reprod` dir then that we already have now? Thoughts @ocaisa?

We should probably also have some dedicated documentation on how to reproduce installations done with EasyBuild?

Or maybe even drop a script into `easybuild/reprod` that specifies everything that's needed (`--include-easyblocks=...` for example)?

**Comment by ocaisa** [comment]
Definitely should go in the `easybuild/reprod` dir. Since the inheritance implies there will typically be a few, I'd suggest we put all the necessary easyblocks in a subdir there so that someone can just use `--include-easyblocks=/.../easybuild/reprod/reprod_easyblocks/*`

**Comment by ocaisa** [comment]
Hmm, I can't find any way of doing this fully. It's straightforward to get the source file for the easyblock (using `inspect.getsourcefile()` and `get_easyblock_class()`) but that is incomplete unless you follow the inheritance all the way back to the base `easyblock` class.

**Comment by ocaisa** [comment]
Ok, I found out how to do it:
```
        app_class = get_easyblock_class(easyblock, name=name)
        for easyblock_class in inspect.getmro(app_class):
            easyblock_path = inspect.getsourcefile(easyblock_class)
            if os.path.split(easyblock_path)[0].endswith(os.path.join('easybuild-framework', 'easybuild', 'framework')):
                break
            else:
                print easyblock_path
```
PR is in the works.

**Comment by boegel** [comment]
easyblocks are now also archived in the `easybuild/reprod` subdir of the installation directory thanks to @ocaisa's PR #2653
