### ISSUE TITLE
Wrong COMPILER_F90 for PGI

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-framework#2646]
The correct setting of COMPILER_F90 in toolchains/compiler/pgi.py is "pgf90" not "pgfortran".
At least from v16 an onwards

**Comment by boegel** [comment]
@akesandgren I'm happy to change this, but does it matter much? From the `pgfortran` man page:

```
pgfortran is an alias for pgf90 and pgf95.
```

**Comment by akesandgren** [comment]
Well, strickly speaking, if you invoke a compiler called xxxf90 it should strictly adhere to the F90 standard, same with xxxf95, whild pgfortran is free to follow whatever is the latest standard they implement.

And some codes may actually care...

**Comment by akesandgren** [comment]
Solved in 2650
