### ISSUE TITLE
ARCH constant for use in easyconfigs and easyblocks

### ISSUE THREAD

**Issue by edmondac** [easybuilders/easybuild-framework#2654]
I'm building various easyconfigs on ppc64le, and there are several situations where we need to specify things differently based on the architecture.

Examples:

1) PyTorch 0.4.1 includes this: `export PYTHONPATH=%(builddir)s/%(namelower)s-%(version)s/build/lib.linux-x86_64-%(pyshortver)s:$PYTHONPATH` - and may other easyconfigs include x86_64. For other architectures this needs to be something else, and an ARCH constant could be used. Should it be expanded to %(arch)s or just included as %s with % (ARCH, ) at the end? I don't know...

2) The TensorFlow easyblock should not enable mkl_dnn if the ARCH isn't x86_64. See "Enabling use of mkl-dnn since cuDNN is not listed as dependency" in tensorflow.py

**Comment by boegel** [comment]
@edmondac For both of these, you can leverage the `get_cpu_architecture` function that is available in `easybuild.tools.systemtools`.

For 1, I think a constant `ARCH` makes more sense than a template `%(arch)s`. Adding support for an `ARCH` constant should be pretty straight forward, see `easybuild/framework/easyconfig/constants.py`.

For 2, you can use `get_cpu_architecture()` similar to how we already do in existing easyblocks, see for example FFTW, GROMACS or Clang.

**Comment by edmondac** [comment]
ok - thanks

**Comment by edmondac** [comment]
After #2728 I'm not sure how much we need this one. I'll try working without it and see...

**Comment by boegel** [comment]
@edmondac I think the support for `%(arch)s` added in #2728 is exactly what was requested here, no?

**Comment by damianam** [comment]
I am closing the issue, since this has been fixed.
