### ISSUE TITLE
toolchains/fft/intelfftw.py need to correctly set FFT_LIB_MT to use threaded mkl

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-framework#2672]
Current behavior is that FFT_LIB_MT is unset and in tools/toolchain/fft.py then gets set to FFT_LIB

**Comment by boegel** [comment]
@akesandgren What would be the correct value for `$FFT_LIB_MT`, and does it depend on the Intel MKL version being used?

**Comment by akesandgren** [comment]
Correct value is (probably) to use the threaded mkl libraries, just like BLAS_LIB_MT from linalg,
it should be all it needs.
I.e. the line 
        fftw_libs.extend(self.variables['LIBBLAS'].flatten())  # add BLAS libs (contains dft)
need to be extended for FFT_LIB_MT
But I'm not quite sure how to do this one

**Comment by akesandgren** [comment]
Solved in https://github.com/easybuilders/easybuild-framework/pull/2688
