### ISSUE TITLE
CUDA stubs directory must not be added to rpath/runpath

### ISSUE THREAD

**Issue by mboisson** [easybuilders/easybuild-framework#2683]
This is a follow up on https://github.com/easybuilders/easybuild-easyblocks/pull/1464 

 adding stubs to LIBRARY_PATH is causing us problems, because it ends up in our binaries RUNPATH.

If this happens and you don't use LD_LIBRARY_PATH (because you are using RUNPATH), you will have problems at runtime.

This is probably something you need to check when you are using runpath/rpath with easybuild (for Compute Canada, @bartoldeman had to adjust our linker wrapper to exclude these paths)

```
A stub object is a shared object, built entirely from mapfiles, that supplies the same linking interface as the real object, while containing no code or data. Stub objects cannot be used at runtime.
```

**Comment by boegel** [comment]
@mboisson How are these paths excluded in your linker wrapper exactly? Just based on directory name?

**Comment by mboisson** [comment]
@bartoldeman would be best to answer that question.

**Comment by bartoldeman** [comment]
yes, as follows:
```
        # also exclude stub libraries like for CUDA
        if [ "${1%%/stubs}" != "$1" ]; then
            return 0
        fi
```
it's not beautiful, but it's unlikely that  a directory named "stubs" contains non-stub libraries I would think.

**Comment by boegel** [comment]
Are there any other cases known besides `CUDA`? If not, we can consider making the check a bit more strict to also check on `CUDA` in the path name...

**Comment by boegel** [comment]
How does #2725 look by means of a fix?

**Comment by boegel** [comment]
fixed via #2725

**Comment by bartoldeman** [comment]
Note that this issue has resurfaced since https://github.com/easybuilders/easybuild-easyblocks/pull/2373 since the stubs libs are now in `$EBROOTCUDA/stubs/lib64`.

**Comment by boegel** [comment]
@bartoldeman So we need to extend the filtering done in #2725 to `CUDA/.*/stubs/lib64` or something?

**Comment by bartoldeman** [comment]
@boegel exactly
