### ISSUE TITLE
+moduleclass "astro"?

### ISSUE THREAD

**Issue by jose-d** [easybuilders/easybuild-framework#2689]
https://github.com/easybuilders/easybuild-framework/blob/da3f86fd7fc213d4bbeca5b2668dfb25938ee4c7/easybuild/tools/config.py#L281

RFC: 
would it make sense to add category like "astro - Astronomy, Astrophysics and Cosmology"?

I just submitted PR for `pyfits` - https://github.com/easybuilders/easybuild-easyconfigs/pull/7273,
and there are others in my workqueue or watchlist:
* PLC/clik - Planck likelihood  code - https://cosmologist.info/cosmomc/readme_planck.html
* CLASS - Cosmic Linear Anisotropy Solving System
 https://github.com/lesgourg/class_public
* cosmoMC
* _others, depending on the demand from our team here_

which are IMO too specific to be categorized as "phys" or "lib".

**Comment by boegel** [comment]
@jose-d Makes sense to me. While you're at it, please also add `quantum` as a separate module class, see https://github.com/desireevl/awesome-quantum-computing#development-tools

**Comment by boegel** [comment]
@jose-d fixed in #2693

**Comment by jose-d** [comment]
oh so fast. 
closing this one.
