### ISSUE TITLE
get rid of global errorsFoundInLog in filetools

### ISSUE THREAD

**Issue by JensTimmerman** [easybuilders/easybuild-framework#273]
filetools has a global errorsFoundInLog = 0

which keeps track of the amount of errors found.

this get's set to 0 and checked in build.py

This is not the best way to check state. 
We should have an object keeping track of state, or reporting errors in a different way.

**Comment by Micket** [comment]
I checked and we certainly don't have this global errorsFoundInLog anymore. Closing.
