### ISSUE TITLE
Easybuild creates .modulerc.lua only in modules/all but not in subcategories e.g. modules/lang

### ISSUE THREAD

**Issue by SethosII** [easybuilders/easybuild-framework#2733]
I saw that the Java build creates a `.modulerc.lua` in the subdirectory `modules/all` but not in `modules/lang`. Therefore when the various subcategories are included in `MODULEPATH` individually instead of `all` `Java 1.8` can't be found:

```
# MODULEPATH includes all subcategories
> ml avail Java
Java/1.8.0_181 # Java 1.8 alias not found
unset MODULEPATH; module use /easybuild/modules/all/
> ml avail Java
Java/1.8.0_181 (1.8) # correct
```

Shouldn't Easybuild create a link to `modules/all/<software>/.modulerc.lua` in the subcategories as it does for the modulefiles?

**Comment by boegel** [comment]
@SethosII You're right, it should, this was overlooked...

I'll look into how this can be fixed.

**Comment by pescobar** [comment]
I am also hitting this problem. I had to manually create the symlink

**Comment by boegel** [comment]
fixed in https://github.com/easybuilders/easybuild-easyblocks/pull/1636
