### ISSUE TITLE
Incorrect definition of FFTW_STATIC_LIBS_MT and other FFT(W) related vars

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-framework#2797]
With foss toolchain I can see:
environment.py:97 INFO Environment variable FFTW_STATIC_LIBS_MT set to -fftw3_omp -fftw3 -pthread (previously undefined)
and with intel:
environment.py:97 INFO Environment variable FFTW_STATIC_LIBS_MT set to -fftw3xc_intel -fftw3x_cdft_lp64 -mkl_cdft_core -mkl_blacs_intelmpi_lp64 -mkl_intel_lp64 -mkl_intel_thread -mkl_core -iomp5 -pthread (previously undefined)

Scalapack on the other hand produces:
environment.py:97 INFO Environment variable LIBSCALAPACK_MT set to -Wl,-Bstatic -Wl,--start-group -lmkl_scalapack_lp64 -lmkl_blacs_intelmpi_lp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -Wl,--end-group -Wl,-Bdynamic -liomp5 -lpthread (previously undefined)
and
environment.py:97 INFO Environment variable EBVARLIBSCALAPACK_MT set to -lscalapack -lopenblas -lpthread -lgfortran (previously undefined)

Note the missing "l" (-l) for FFT libs.

**Comment by boegel** [comment]
fixed in #2822
