### ISSUE TITLE
support for .yeb not compatible with PyYAML 5.x

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#2808]
see https://github.com/easybuilders/easybuild-framework/pull/2807#issuecomment-473085856

@ocaisa If you want to keep support for `.yeb` alive (sort of), here's your chance... ;)

**Comment by ocaisa** [comment]
Solved in #2809

**Comment by boegel** [comment]
fixed with #2809, thanks a lot @ocaisa!
