### ISSUE TITLE
EasyBuild doesn't respect EASYBUILD_FILE_FORMAT variable

### ISSUE THREAD

**Issue by casparvl** [easybuilders/easybuild-framework#2814]
**Issue**
EasyBuild seems to listen to the --logfile-format command, but not to the EASYBUILD_LOGFILE_FORMAT environment variable:

```
[casparl@int1 logs]$ export EASYBUILD_LOGFILE_FORMAT="easybuild,easybuild-%(name)s.log"
[casparl@int1 logs]$ eb --show-full-config | grep logfile
logfile-format            (D) = ('easybuild', 'easybuild-%(name)s-%(version)s-%(date)s.%(time)s.log')
[casparl@int1 logs]$ eb --show-full-config --logfile-format="easybuild,easybuild-%(name)s.log" | grep logfile
logfile-format            (C) = ('easybuild', 'easybuild-%(name)s.log')
```

**Comment by ocaisa** [comment]
Hmm, what version of eb is this? If I run the same commands with the devel branches I get:
```
alanc@alanc-VirtualBox:~$ export EASYBUILD_LOGFILE_FORMAT="easybuild,easybuild-%(name)s.log"
alanc@alanc-VirtualBox:~$ eb --show-full-config | grep logfile
logfile-format                            (E) = ('easybuild', 'easybuild-%(name)s.log')

```

**Comment by casparvl** [comment]
Good point, should have added that. It is version 3.8.1.

**Comment by casparvl** [comment]
Never mind, closing issue. I'm not sure why/what went wrong before, but something in the environment must have somehow been corrupted. Now that I saw it working for Ocasia, I tried it again (after a fresh login, maybe that helped), and even though I seem to be exectuing the same commands, in now works:

```
[casparl@int2 ~]$ export EASYBUILD_LOGFILE_FORMAT="easybuild,easybuild-%(name)s.log"
[casparl@int2 ~]$ eb --show-full-config | grep logfile
logfile-format                            (E) = ('easybuild', 'easybuild-%(name)s.log')
```

**Comment by boegel** [comment]
@casparvl The only thing I can think of is that you had a typo in the name of the environment variable, so its name somehow didn't start with `EASYBUILD_`.

Any environment variable starting with `EASYBUILD_` is picked up by EasyBuild, and if no corresponding configuration option is found, it results in a clear error.

**Comment by casparvl** [comment]
@boegel That could have been the reason, _except_ that my post was a copy-paste of the actual commands I used to show the problem - and then the next day I copy-pasted the commands from this issue in a fresh terminal and it just worked. Ow well, no use breaking our heads about it, it turns out not to be a bug in EasyBuild, so that's good news :)
