### ISSUE TITLE
EasyBuild rpath wrappers don't seem to properly filter --enable-new-dtags when building Qt5-5.10.1-foss-2018b.eb

### ISSUE THREAD

**Issue by casparvl** [easybuilders/easybuild-framework#2820]
**Issue**

Installation of Qt5-5.10.1-foss-2018b.eb fails in the sanity check step, when performing the rpath sanity check:

**EasyBuild log**
```
No '(RPATH)' found in 'readelf -d' output for /home/casparl/.local/EB_regression/RedHatEnterpriseServer7/software/Qt5/5.10.1-foss-2018b/lib/libQt5WebEngineCore.so.5.10.1: 
Dynamic section at offset 0x6407d90 contains 74 entries:
  Tag        Type                         Name/Value
...
 0x000000000000000e (SONAME)             Library soname: [libQt5WebEngineCore.so.5]
 0x000000000000000c (INIT)               0x6f7530
 0x000000000000000d (FINI)               0x4a1c510
 0x000000000000001a (FINI_ARRAY)         0x6276918
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x0000000000000019 (INIT_ARRAY)         0x6276920
 0x000000000000001b (INIT_ARRAYSZ)       168 (bytes)
 0x000000000000001d (RUNPATH)            Library runpath: [/home/casparl/.local/EB_regression/RedHatEnterpriseServer7/software/Qt5/5.10.1-foss-2018b/lib:/home/casparl/.local/EB_regression/RedHatEnterpriseServer7/software/Qt5/5.10.1-foss-2018b/lib64:$ORIGIN:$ORIGIN/../lib:$ORIGIN/../lib64:<and_many_more...>]
...
```

The runpath is set, instead of the rpath. Usually, this happens when `--enable-new-dtags` is passed. The EasyBuild documentation suggests however that `--enable-new-dtags` should be filtered by the rpath wrappers (https://easybuild.readthedocs.io/en/latest/RPATH-support.html?highlight=rpath). The code for this functionality is here: https://github.com/easybuilders/easybuild-framework/blob/master/easybuild/scripts/rpath_args.py#L100

I ran the installation with `--debug` to get a log for the rpath wrappers. Relevant sections from the g++ wrapper log:

**rpath_wrapper_g++.log**
```
(24176) [2019-03-25 16:32:17] rpath_args_out:
CMD_ARGS=('-Wl,-rpath=/home/casparl/.local/EB_regression/RedHatEnterpriseServer7/software/Qt5/5.10.1-foss-2018b/lib' '-Wl,-rpath=/home/casparl/.local/EB_regression/RedHatEnterpriseServer7/software/Qt5/5.10.1-foss-2018b/lib64' '-Wl,-rpath=$ORIGIN' '-Wl,-rpath=$ORIGIN/../lib' '-Wl,-rpath=$ORIGIN/../lib64' '-Wl,--disable-new-dtags' 
...
'-Wl,--version-script,QtWebEngineCore.version' '-Wl,--gc-sections' '-Wl,-O1' '-Wl,-z,now' '-Wl,-z,defs' '-Wl,-O1' '-fuse-ld=gold' '-Wl,--enable-new-dtags' '-Wl,-z,origin' '-Wl,-rpath,$ORIGIN' '-shared' '-Wl,-soname,libQt5WebEngineCore.so.5' '-o' 'libQt5WebEngineCore.so.5.10.1' '-L/usr/X11R6/lib64' '-L/tmp/casparl/Qt5/5.10.1/foss-2018b/qt-everywhere-src-5.10.1/qtdeclarative/lib
``` 
Thus, in the rpath_args_out, there is still the `-Wl,--enable-new-dtags`, and it is after EasyBuilds `-Wl,--disable-new-dtags`.

**rpath_wrapper_ld.gold.log**
Shows no entry of libQt5WebEngineCore.so.5.

Searching for `--enable-new-dtags` I do find some hits in the original command:
```
(26719) [2019-03-25 16:32:52] found CMD: ld.gold | original command:
...
-O1 --enable-new-dtags -z origin -rpath $ORIGIN/../..
/../lib -rpath-link /tmp/casparl/Qt5/5.10.1/foss-2018b/qt-everywhere-src-5.10.1/qtquickcontrols2/lib
...
```
That are replaced by `--disable-new-dtags` in the rpath_args_out:
```
CMD_ARGS=('-rpath=/home/casparl/.local/EB_regression/RedHatEnterpriseServer7/software/Qt5/5.10.1-foss-2018b/lib' '-rpath=/home/casparl/.local/EB_regression/RedHatEnterpriseServer7/software/Qt5/5.10.1-foss-2018b/lib64' '-rpath=$ORIGIN' '-rpath=$ORIGIN/../lib' '-rpath=$ORIGIN/../lib64' '--disable-new-dtags'
...
```

**Possible solution**
It seems the `--enable-new-dtags` is only replaced by `--disable-new-dtags` when the linker wrapper is invoked (i.e. when the argument is `--enable-new-dtags`). When the compiler wrapper is invoked the `Wl,--enable-new-dtags` is not replaced by `Wl,--disable-new-dtags`.

My guess is we need to replace 
```
elif arg == '--enable-new-dtags':
cmd_args.append('--disable-new-dtags')
```
with
```
elif arg == flag_prefix + '--enable-new-dtags':
cmd_args.append(flag_prefix + '--disable-new-dtags')
```
to make things work.

**Comment by boegel** [comment]
@casparvl The proposed fix makes a lot of sense to me.

Did you test it to verify that it effectively fixes the problem you're seeing?

**Comment by damianam** [comment]
With https://github.com/easybuilders/easybuild-framework/pull/2821 in place we can close the issue.

**Comment by casparvl** [comment]
Shows some promising results in the rpath logs:
**rpath_wrapper_g++.log**
```
(29223) [2019-03-25 18:32:20] found CMD: g++ | original command: /hpc/sw_test/EB_regression/2019/software/GCCcore/7.3.0/bin/g++ | orig args: '"-fuse-ld=gold -Wl,--enable-new-dtags -o conftest-out conftest.cpp"'
(29223) [2019-03-25 18:32:20] /usr/bin/python2 -O /nfs/home4/casparl/.local/easybuild/RedHatEnterpriseServer7/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_framework-3.8.1-py2.7.egg/easybuild/scripts/rpath_args.py g++ '/lib.*,/usr.*,/tmp/casparl/eb-n5hxOF.*,/tmp/casparl/Qt5/5.10.1/foss-2018b.*,.*/lib(64)?/stubs/?.*' '/home/casparl/.local/EB_regression/RedHatEnterpriseServer7/software/Qt5/5.10.1-foss-2018b/lib,/home/casparl/.local/EB_regression/RedHatEnterpriseServer7/software/Qt5/5.10.1-foss-2018b/lib64,,/../lib,/../lib64' "-fuse-ld=gold -Wl,--enable-new-dtags -o conftest-out conftest.cpp"'
(29223) [2019-03-25 18:32:20] rpath_args_out:
CMD_ARGS=('-Wl,-rpath=/home/casparl/.local/EB_regression/RedHatEnterpriseServer7/software/Qt5/5.10.1-foss-2018b/lib' '-Wl,-rpath=/home/casparl/.local/EB_regression/RedHatEnterpriseServer7/software/Qt5/5.10.1-foss-2018b/lib64' '-Wl,-rpath=$ORIGIN' '-Wl,-rpath=$ORIGIN/../lib' '-Wl,-rpath=$ORIGIN/../lib64' '-Wl,--disable-new-dtags' '-fuse-ld=gold' '-Wl,--disable-new-dtags' '-o' 'conftest-out' 'conftest.cpp')
```
No more --enable-new-dtags in the rpath_args_out!

However, my Qt5-5.10.1-foss-2018b.eb still fails during the sanity check step... It shows RPATHs now in the readelf outputs, but somehow still produces 'GLIBCXX not found' errors since it is still not picking up the toolchain libstdc++...

I'll get back to this later...

**Comment by casparvl** [comment]
I checked a bit further. All of the .so's now have their RPATH set, the problem is _what_ it is set to. Some (but not all) .so's only get an RPATH to a limited set of library locations, e.g. libQtWebEngineCore.so.5.10.1 gets:

```
0x000000000000000f (RPATH)              Library rpath: [/home/casparl/.local/EB_regression/RedHatEnterpriseServer7/software/Qt5/5.10.1-foss-2018b/lib:/home/casparl/.local/EB_regression/RedHatEnterpriseServer7/software/Qt5/5.10.1-foss-2018b/lib64:$ORIGIN:$ORIGIN/../lib:$ORIGIN/../lib64:/hpc/sw_test/EB_regression/2019/software/Mesa/18.1.1-foss-2018b/lib:/hpc/sw_test/EB_regression/2019/software/NSS/3.39-GCCcore-7.3.0/lib:/hpc/sw_test/EB_regression/2019/software/NSPR/4.20-GCCcore-7.3.0/lib:/hpc/sw_test/EB_regression/2019/software/freetype/2.9.1-GCCcore-7.3.0/lib:/hpc/sw_test/EB_regression/2019/software/libpng/1.6.34-GCCcore-7.3.0/lib:/hpc/sw_test/EB_regression/2019/software/zlib/1.2.11-GCCcore-7.3.0/lib:/hpc/sw_test/EB_regression/2019/software/DBus/1.13.6-GCCcore-7.3.0/lib]
```
One of the crucial things lacking here is 

```
/hpc/sw_test/EB_regression/2019/software/GCCcore/7.3.0/lib64
```
where it should pick up on the `libstdc++.so.6`. Since the above line is not included in the RPATH, the runtime linker picks up on the `libstdc++.so.6` in /usr/lib, which lacks the required GLIBCXX versions.

Looking at the RPATH logs, there is no
```
-L/hpc/sw_test/EB_regression/2019/software/GCCcore/7.3.0/lib64
```
in the original command (i.e. before it is passed by the rpath wrappers). As a result there is also no
```
-Wl,rpath=/hpc/sw_test/EB_regression/2019/software/GCCcore/7.3.0/lib64
```
in the output args of the `rpath_args.py` script. Why the -L line is missing from the input, I don't know: it seems that this part of the compilation is not respecting the LDFLAGS set by EasyBuild (?). 

I am 95% sure that this problem is unrelated to the initial problem addressed in this issue. Thus, I think the proposed - and merged - fix is fine, since I now at least get an RPATH set. The next quesion to resolve is why I don't get the correct/full

**Comment by donners-atos** [comment]
Hmm, I'm surprised that it wouldn't work in the first place. In the end, the compiler will call the linker. That should then go through the linker wrapper and the flag should be replaced. Does it maybe use another linker for that particular library, for which we do not have a wrapper in place? It seems there is a new linker called `ld.lld` (apparently the LLVM linker) in RHEL7.4, for which there is no wrapper built yet. Is that one being used here by any chance?

**Comment by casparvl** [comment]
@donners-atos Yeah, the first part of the conversation here kind of happened on the EasyBuild Slack, and indeed we concluded that - somehow - the linker wrapper seems to be bypassed. It is weird, since the link line for this library does contain `'-fuse-ld=gold'` explicitely, so one would assume `ld.gold` would be invoked - but the rpath wrapper logs for ld.gold show no sign of QtWebEngineCore.

For now, I have 'fixed' it with a patchelf as postinstallcmd. Since this issue has already taken up way too much of my time, I'm not really inclined to dive into it and figure out what linker is actually invoked and why... but you might be right about it being the LLVM linker. This was part of the path:

```
/hpc/sw_test/EB_regression/2019/software/LLVM/6.0.0-GCCcore-7.3.0/bin
```
And that directory contains 

```
[casparl@tcn900 Qt5]$ /hpc/sw_test/EB_regression/2019/software/LLVM/6.0.0-GCCcore-7.3.0/bin/llvm-link --help
OVERVIEW: llvm linker

USAGE: llvm-link [options] <input bitcode files>
...
````

**Comment by boegel** [comment]
@casparvl So that would mean we should also wrap `llvm-link`?

Should we open a new issue on that to follow-up (or re-open this one)?

**Comment by jdonners** [comment]
I'll have a look at it, but it takes a while to build everything up to Qt5
on my laptop. Could take several weeks before I find enough time to get
there. I guess it's better to to create a separate pull request for this. I
expect that the command is llvm-ld, not llvm-link.

Cheers,
John
