### ISSUE TITLE
Instructions for Downloading source files

### ISSUE THREAD

**Issue by crphilipp** [easybuilders/easybuild-framework#2846]
In the case that source files are not directly downloadable, because logins are required or such, some instructions should be provided. Additionally, some easyconfig files require additional manipulation after the file is downloaded. Again, these instructions should be printed on a failed build. Examples of modules:

- **cuDNN-7.1.4.18-fosscuda-2018b.eb** - This requires an NVidia login to download the source files, as well as renaming the source file after it is downloaded.

- **NCCL-2.3.7-fosscuda-2018b.eb** - Again, this requires a login with NVidia

**Comment by boegel** [comment]
The idea here would be basically to produce a better error message when the required sources are missing, and to add support for producing a custom message that provides instructions on how to obtain the missing sources (either by manually downloading, or some other way).

**Comment by PetrKralCZ** [comment]
Easybuild now uses `download_instructions` for this purpose. So this issue should be closed.

**Comment by ocaisa** [comment]
Thanks for the tip @PetrKralCZ
