### ISSUE TITLE
Change of path when extracting files

### ISSUE THREAD

**Issue by espenfl** [easybuilders/easybuild-framework#2858]
Upon execution of `extract_files` the current working directory changes. That makes sense from inspecting the source code. However, is this what we should expect upon calling such a method? I would suggest to factorize this such that `extract_file` does precisely that. In my case I only wanted to do this (and then set an environmental path in front of make to the destination path). 

Now I either have to store and reset the working directory, or try to comply to the patching regime (but here I am not seeing the granularity that I would want, I would love pointers on this, e.g. how I can from a custom easyblock file select which patches I want to apply given an entry in my build matrix). Maybe, in the end, the patch route is the way to go.

**Comment by boegel** [comment]
Changing the behavior of `extract_file` now is difficult (since whatever is calling it may rely on the fact that it changes to the target directory).
On the other hand, I agree that this is counter-intuitive, and with the upcoming EasyBuild 4.0 we have a window of opportunity to make "breaking" changes (this is a pretty minor one imho).

Can you clarify what your question w.r.t. patching? What are you trying to do exactly, do you have an example easyblock/script for us to look at?

**Comment by espenfl** [comment]
Thanks for the quick response. Greatly appreciated. 

What I try to do is to fetch an archive (an add on to another software) and go from there (given a file name that indicates version). And this is not in a patch form from the supplier. We could do this with an additional script etc. but that introduces work for each version. In fact I am not yet sure what the best strategy is at this point. Most likely a combination of patch (to update the included objects etc.) and then `extract_file` etc. for the additional files that is to be included. The frequency of changes of the former is probably low, while it is higher on the latter. Trying to minimize the manual labor. I will post on the mailing list as I also have a few other questions. Thanks again.

**Comment by akesandgren** [comment]
And that thing you're fetching can't be built outside of the target software and used from there?
This is the preferred way of doing things.

Also note that there is no problem having multiple sources that get unpacked in various ways using the extract_cmd part of a source specification, see OpenBLAS-0.2.19-gompi-2016.09-LAPACK-3.6.1.eb for an example. Not sure this is what your're trying to do though.

**Comment by espenfl** [comment]
Thanks. For some parts, this is what we do. e.g. utilize `dependencies`. That works nicely. However, there is also a rather wide set of auxiliary functionality to the source code that needs to be done by patches and additions of new files.

**Comment by boegel** [comment]
@espenfl How about if we provide a way to disable the automatic `change_dir` that `extract_file` does, for example using something like:

```python
extract_file('example.tar.gz', target_dir, change_to=False)
```

We could then dig up all locations where `extract_file` is being used, and explicitly use `change_to=True`, which allows us to change the default behavior of `extract_file` later on...

**Comment by espenfl** [comment]
Yes, this sounds great. Thanks.

**Comment by boegel** [comment]
`extract_file` now has an additional named argument `change_into_dir`, see #3292

When it is left unspecified, a deprecation warning is produced unless you explicitly opt-in or opt-out (with `change_into_dir=True` or `change_into_dir=False` explicitly).

So, closing this...

**Comment by espenfl** [comment]
Forgot to give credits for fixing this. Indeed this made it easier for our use cases. Thanks a lot @boegel and the EB team!
