### ISSUE TITLE
multi_dep support complicated as packages no longer support Python2

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-framework#2859]
Our SciPy bundle at JSC includes matplotlib, we hit the issue that `matplotlib` stopped supporting Python2 as of version 3.x. There is currently no elegant way of dealing with this when using `multi_deps`, it would be good to be able to select the extension version based on the Python version, and have the ability to not install a particular extension (like `backports`) for a Python version.

**Comment by ocaisa** [comment]
Not really. A first thought might be:
```
    ('matplotlib', '2.2.4', {
        'restrict_python_version: '2.7',
        'source_urls': ['https://pypi.python.org/packages/source/m/matplotlib'],
    }),
    ('matplotlib', '3.0.3', {
        'restrict_python_version: '3.6',
        'source_urls': ['https://pypi.python.org/packages/source/m/matplotlib'],
    }),
```
and then we do version check about whether the module show be installed or not based on the active python version

**Comment by ocaisa** [comment]
The idea would be that the python version would have to version match whatever version is in `restrict_python_version`

**Comment by ocaisa** [comment]
It would make things a little messy but at least it removes the current restriction (which is only going to get worse)

**Comment by Flamefire** [comment]
Then why not drop using multi-dep for those cases? Have a Python 3.x and a Python 2.x version. 

As Python 2 is dropping out of support soon I'd even expect the issue to be gone by itself as Python 2 will no longer be needed/used for newer ECs hence no need for multi-deps

**Comment by ocaisa** [comment]
I think that is what is starting to happen in practice already, see the [SciPy-bundle](https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/s/SciPy-bundle).
Don't expect Python2 to disappear from your HPC stack anytime soon though, people were still asking for FFTW2 (last updated in 1999) at JSC up until we refused to install it any more (a couple of years ago).

**Comment by Flamefire** [comment]
> Don't expect Python2 to disappear from your HPC stack anytime soon though, people were still asking for FFTW2 (last updated in 1999) at JSC up until we refused to install it any more (a couple of years ago).

Not expecting it to disappear. Just refusing to create anything new for it, just as you did ;) Make it painful to use (the bad alternative) and people will start using the (better) alternative.
