### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mboisson** [easybuilders/easybuild-framework#2862]
We are having some issues when our installers misname an EasyConfig by not following the convention

`<software name>-<software version>-<toolchain name>-<toolchain version>-<version suffix>.eb` 

There should be an option in EasyBuild to refuse the build if the EasyConfig filename does not match the EasyConfig content.

**Comment by mboisson** [comment]
@bartoldeman @boegel 

I am not sure how easy/hard this is to implement. If you have an idea and pointers, please post them here.

**Comment by akesandgren** [comment]
You mean something like the existing verify-easyconfig-filenames=True

**Comment by ocaisa** [comment]
Yup, support for that was added in https://github.com/easybuilders/easybuild-framework/pull/2185

**Comment by mboisson** [comment]
Ah, I guess I was not aware of that :)   We can test and enable that by default I guess. 

Thanks @akesandgren and @ocaisa
