### ISSUE TITLE
Fail to detect software version of ScaLAPACK when using LowerCaseMNS naming schema

### ISSUE THREAD

**Issue by timeu** [easybuilders/easybuild-framework#2866]
When using lower case module naming, installation of software modules that depend on ScaLAPACK will fail with following error:
```
[adm_seren@dev-c2-0 ~]$ eb --hidden SWIG-3.0.12-foss-2018b-Python-2.7.15.eb -r --debug
== temporary log file in case of crash /tmp/eb-tdsnvE/easybuild-PiUi6N.log
== resolving dependencies ...
== processing EasyBuild easyconfig /software/system/easyconfigs/easybuild/easyconfigs/s/SWIG/SWIG-3.0.12-foss-2018b-Python-2.7.15.eb
== building and installing swig/.3.0.12-foss-2018b-python-2.7.15...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== FAILED: Installation ended unsuccessfully (build directory: /software/build-tmp/SWIG/3.0.12/foss-2018b-Python-2.7.15): build failed (first 300 chars): get_software_version software version for ScaLAPACK was not found in environment
== Results of the build can be found in the log file(s) /tmp/eb-tdsnvE/easybuild-SWIG-3.0.12-20190507.152913.AwuFN.log
ERROR: Build of /software/system/easyconfigs/easybuild/easyconfigs/s/SWIG/SWIG-3.0.12-foss-2018b-Python-2.7.15.eb failed (err: 'build failed (first 300 chars): get_software_version software version for ScaLAPACK was not found in environment')
```
The problem seems to be in https://github.com/easybuilders/easybuild-framework/blob/master/easybuild/toolchains/linalg/scalapack.py#L46 which is case sensitive. 

Attached log is here: https://gist.github.com/timeu/9f1cbc6c23de2cea6f34b059cac733ce

**Comment by boegel** [comment]
@timeu After closer inspection of the code, I'm not convinced that the lower-case module naming scheme you are using is the problem here...

What seems to be failing here is grabbing the value of `$EBVERSIONSCALAPACK`, even though the debug log clearly shows that it is being set.

Can you try this manually, and let me know what it spits out?

```python
$ module load foss/2018b
$ echo $EBROOTSCALAPACK
$ echo $EBVERSIONSCALAPACK
$ python -c "from easybuild.tools.modules import get_software_version; print get_software_version('ScaLAPACK')"
```

**Comment by akesandgren** [comment]
Doesn't that last one require a ml EasyBuild first?

**Comment by boegel** [comment]
@akesandgren Well, yeah, I'm assume `EasyBuild` is available in the environment already, of course. :)

**Comment by timeu** [comment]
@boegel this is the output:
```
[adm_seren@dev-login-1 ~]$ ml easybuild/3.9.0
[adm_seren@dev-login-1 ~]$ module load foss/2018b
[adm_seren@dev-login-1 ~]$ echo $EBROOTSCALAPACK
/software/2019/software/scalapack/2.0.2-gompi-2018b-openblas-0.3.1
[adm_seren@dev-login-1 ~]$ echo $EBVERSIONSCALAPACK
2.0.2
[adm_seren@dev-login-1 ~]$ python -c "from easybuild.tools.modules import get_software_version; print get_software_version('ScaLAPACK')"
2.0.2
```

**Comment by boegel** [comment]
That's exactly what is expected... This is strange.

Did you make any local modifications to the EasyBuild framework perhaps?

**Comment by boegel** [comment]
@timeu I'll try and reproduce this on my end first. Do you mind sharing your module naming scheme implementation?
I can probably easily reproduce it myself, but I might as well try and get as close as possible to your setup...

**Comment by timeu** [comment]
I updated the previous gist with the naming scheme implementation: 
https://gist.github.com/timeu/9f1cbc6c23de2cea6f34b059cac733ce

**Comment by boegel** [comment]
@timeu I just tried to reproduce the problem you are seeing using EasyBuild v3.9.0 (without any changes made it it) and using your `LowercaseMNS`, but I didn't run into the problem you're reporting:

```
$ export EASYBUILD_INSTALLPATH=/tmp
$ eb --include-module-naming-schemes lowercasemns.py --module-naming-scheme LowerCaseMNS SWIG-3.0.12-foss-2018b-Python-2.7.15.eb -dr
$ module use /tmp/modules/all/
$ module avail swig/

---------------------------------------------------------------------------------------- /tmp/modules/all -----------------------------------------------------------------------------------------
   swig/3.0.12-foss-2018b-python-2.7.15
```

So I'm a bit lost on how to deal with this further... This really smells like some local changes have been made to the EasyBuild installation.

Maybe try re-installing EasyBuild 3.9.0?

**Comment by timeu** [comment]
will try one more thing: 
SWIG is in the list of a hidden dependency (not sure if this makes a difference)

**Comment by boegel** [comment]
@timeu I doubt that makes a difference, since `SWIG` is not a dependency here (yet), it's the software you're installing...

**Comment by timeu** [comment]
I reinstalled EB 3.9.0 with EB 3.8.1 but I am running into the same issue again :-(
Is there any way I can step through the code and maybe see why it fails ? 

This is btw the env variables that we set for EB:

```
[adm_seren@stg-c1-0 ~]$ env | grep EASY
EASYBUILD_MODULES_TOOL=Lmod
EASYBUILD_RECURSIVE_MODULE_UNLOAD=True
EASYBUILD_GROUP_WRITABLE_INSTALLDIR=dlg.impimba.fso.ii2.software-tree
EASYBUILD_BUILDPATH=/software/build-tmp
EASYBUILD_INSTALLPATH=/tmp
EASYBUILD_PREFIX=/software/2019
EASYBUILD_INCLUDE_MODULE_NAMING_SCHEMES=/software/system/easybuild-MNS/*.py
EASYBUILD_MODULE_SYNTAX=Lua
EASYBUILD_MODULE_NAMING_SCHEME=LowerCaseMNS
EASYBUILD_ADD_DUMMY_TO_MINIMAL_TOOLCHAINS=False
EASYBUILD_GIT_WORKING_DIRS_PATH=/software/system
EASYBUILD_HIDE_DEPS=FTGL,libdrm,libsndfile,GMP,Mesa,pixman,fontconfig,Bison,Doxygen,JasPer,NASM,SQLite,Szip,Tcl,bzip2,cURL,flex,freetype,libjpeg-turbo,libpng,libreadline,libtool,libxml2,ncurses,zlib,M4,Serf,APR,APR-util,expat,SCons,binutils,Coreutils,GLib,Qt,SCOTCH,Tk,hwloc,libffi,libunwind,make,numactl,pkg-config,gettext,Autotools,Automake,Autoconf,OPARI2,OTF2,UDUNITS,ZeroMQ,OpenPGM,util-linux,libsodium,libQGLViewer,Eigen,GTS,GL2PS,PyGTS,PyQt,IPython,Python-Xlib,LOKI,SIP,NASM,PIL,libjpeg-turbo,libxcb,libX11,libXau,xproto,kbproto,inputproto,libpthread-stubs,xextproto,libXdmcp,xcb-proto,xtrans,LibTIFF,byacc,guile,libunistring,CMake,PCRE,PROJ,libutempter,libevent,GDAL,GEOS,SWIG,libGLU,NLopt,nettle,protobuf-python,protobuf,libgtextutils,cairo,pyyaml,pyflakes,networkx,libyaml,OpenJPEG,pyzmq,file,libharu,libmaus2
EASYBUILD_ROBOT_PATHS=/software/2019/ebfiles_repo:/software/system/easyconfigs/easybuild/easyconfigs
__LMOD_REF_COUNT_EASYBUILD_ROBOT_PATHS=/software/2019/ebfiles_repo:1;/software/system/easyconfigs/easybuild/easyconfigs:1
EASYBUILD_MINIMAL_TOOLCHAINS=False
EASYBUILD_HIDE_TOOLCHAINS=gompi
EBROOTEASYBUILD=/software/2019/software/easybuild/3.9.0
EBDEVELEASYBUILD=/software/2019/software/easybuild/3.9.0/easybuild/easybuild-3.9.0-easybuild-devel
EBVERSIONEASYBUILD=3.9.0
EASYBUILD_JOB_BACKEND=Slurm
```

**Comment by boegel** [comment]
@timeu Please try again with the just released EasyBuild v3.9.1 (you can use `eb --install-latest-eb-release` with 3.9.0 or 3.8.1 to get it installed).
I doubt that will make a difference, but it rules out a couple of things.

Stepping through the code is a bit difficult to do, but if the problem remains consider me interested...

One possible culprit could be the `$EASYBUILD_RECURSIVE_MODULE_UNLOAD` you have, but that's just a wild unsubstantiated guess.

Can you show the contents of your `ScaLAPACK` module file?

**Comment by timeu** [comment]
same error with EB 3.9.1 unfortunately :-(

I added the SWIG module content to the previous gist (https://gist.github.com/timeu/9f1cbc6c23de2cea6f34b059cac733ce)

**Comment by boegel** [comment]
@timeu Is there an easy way you can try with a default configuration, only using `LowerCaseMNS` as module naming scheme
I'd like to figure out whether this is tied to a configuration setting or not (which may explain why I can't easily reproduce this).

An easy way to do this could be:
* unset all `$EASYBUILD_*` environment variables
* use `eb --ignoreconfigfiles --include-module-naming-schemes /software/system/easybuild-MNS/*.py --module-naming-scheme LowerCaseMNS`

Can you also show the contents of your `pcre/.8.41-gcccore-7.3.0` module file?
The log seems to show that `$EBVERSIONSCALAPACK` is unset when that module is being loaded, basically because a whole bunch of modules are being unloaded?!

**Comment by timeu** [comment]
I uploaded the contents of the `pcre` module to the previous gist. 
I unset all `$EASYBUILD_*` variables but when I try to run it with `--ignoreconfigfiles-- it asks me to specify an option for it. However we are only customizing easybuild with env variables and not with files. 
I did run it the following way: 
```
[adm_seren@stg-c1-0 SWIG]$  export EASYBUILD_INSTALLPATH=/tmp
[adm_seren@stg-c1-0 SWIG]$  eb --include-module-naming-schemes /software/system/easybuild-MNS/*.py --module-naming-scheme LowerCaseMNS SWIG-3.0.12-foss-2018b-Python-2.7.15.eb -dr

== COMPLETED: Installation ended successfully
== Results of the build can be found in the log file(s) /tmp/software/bzip2/1.0.6-gcccore-7.3.0/easybuild/easybuild-bzip2-1.0.6-20190521.135236.log
== processing EasyBuild easyconfig /software/2019/software/easybuild/3.9.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.9.1-py2.7.egg/easybuild/easyconfigs/p/PCRE/PCRE-8.41-GCCcore-7.3.0.eb
== building and installing pcre/8.41-gcccore-7.3.0...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== restore after iterating...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully
== Results of the build can be found in the log file(s) /tmp/software/pcre/8.41-gcccore-7.3.0/easybuild/easybuild-PCRE-8.41-20190521.135320.log
== processing EasyBuild easyconfig /software/system/easyconfigs/easybuild/easyconfigs/s/SWIG/SWIG-3.0.12-foss-2018b-Python-2.7.15.eb
== building and installing swig/3.0.12-foss-2018b-python-2.7.15...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== FAILED: Installation ended unsuccessfully (build directory: /users/adm_seren/.local/easybuild/build/SWIG/3.0.12/foss-2018b-Python-2.7.15): build failed (first 300 chars): get_software_version software version for ScaLAPACK was not found in environment
== Results of the build can be found in the log file(s) /tmp/eb-5CL5Re/easybuild-SWIG-3.0.12-20190521.135320.RzrTp.log
ERROR: Build of /software/system/easyconfigs/easybuild/easyconfigs/s/SWIG/SWIG-3.0.12-foss-2018b-Python-2.7.15.eb failed (err: 'build failed (first 300 chars): get_software_version software version for ScaLAPACK was not found in environment')
```
Here is the the list of env variables: 
```
[adm_seren@stg-c1-0 SWIG]$ env | grep EASYBUILD
EASYBUILD_INSTALLPATH=/tmp
__LMOD_REF_COUNT_EASYBUILD_ROBOT_PATHS=/software/2019/ebfiles_repo:1;/software/system/easyconfigs/easybuild/easyconfigs:1
EBROOTEASYBUILD=/software/2019/software/easybuild/3.9.1
EBDEVELEASYBUILD=/software/2019/software/easybuild/3.9.1/easybuild/easybuild-3.9.1-easybuild-devel
EBVERSIONEASYBUILD=3.9.1
```
and this is the config: 
```
[adm_seren@stg-c1-0 SWIG]$ eb --show-config
#
# Current EasyBuild configuration
# (C: command line argument, D: default value, E: environment variable, F: configuration file)
#
buildpath      (D) = /users/adm_seren/.local/easybuild/build
containerpath  (D) = /users/adm_seren/.local/easybuild/containers
installpath    (E) = /tmp
repositorypath (D) = /users/adm_seren/.local/easybuild/ebfiles_repo
robot-paths    (D) = /software/2019/software/easybuild/3.9.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.9.1-py2.7.egg/easybuild/easyconfigs
sourcepath     (D) = /users/adm_seren/.local/easybuild/sources
```

**Comment by boegel** [comment]
@timeu We're closing in I think...

One more question: which version of Lmod are you using, and how is it configured (please share the output of `ml --config`)?

**Comment by timeu** [comment]
We are using OpenHPC's Lmod package 
```
[adm_seren@clip-login-0 ~]$ rpm -qa | grep lmod
lmod-ohpc-7.8.15-4.1.ohpc.1.3.67.x86_64
```
I added the output of `ml --config` to the previous gists: https://gist.github.com/timeu/9f1cbc6c23de2cea6f34b059cac733ce#file-lmod-conf

**Comment by boegel** [comment]
@timeu It seems like the problem is the use of `$EASYBUILD_RECURSIVE_MODULE_UNLOAD`, or of mixing modules that were built with different configurations.

When the `pcre/.8.41-gcccore-7.3.0` module is loaded, all modules for the toolchain components are being unloaded, which results in `$EBVERSIONSCALAPACK` getting unset.

Were all modules generated using the same EasyBuild configuration?

**Comment by timeu** [comment]
We used the same EasyBuild configuration for all modules. This is actualy part of a fresh new software tree for a new HPC system. I started from the bootstrap script, installed the 2019a and 2018b toolchain with EB 3.8.1 and later I swichted to EB 3.9.0 for the rest of the modules. But everything was buult with the same EB configuration.

**Comment by ocaisa** [comment]
If you are configuring your system with HMNS then you will need to disable recursive unloading for any toolchains or compilers. Since toolchains (and usually compilers) sit at dummy level, whenever you recursively unload them you unload your entire hierarchy.

**Comment by ocaisa** [comment]
Sorry, I took a look in the repos with https://github.com/search?q=org%3Aeasybuilders+recursive_module_unload&type=Code and I realised that at JSC we actually switch that on only for compilers. It's toolchains where you cannot have it enabled.

**Comment by ocaisa** [comment]
Sorry, forget all that, you are not using HMNS!

**Comment by akesandgren** [comment]
And there is no problem having it on for everything with HMNS. It's just a matter of opinion on what you expect.

**Comment by boegel** [comment]
Still a bit stumped by this one... Any updates on this @timeu?

**Comment by timeu** [comment]
@boegel  We didn't have much time to look into this one as we were busy to get the infra finished. But now this will become a priority as we need to work on the software tree. 
I can try to re-generate the `pcre/.8.41-gcccore-7.3.0` module and see if this changes anything ? 
I can also try to start from a fresh empty modules environment and just try to build R from scratch

**Comment by timeu** [comment]
@boegel I treid to build pcre again from scratch with EB 3.9.3 and it shows the same behavior. 
Is it related to the the section
```
if mode() == "unload" or not ( isloaded("gcccore/7.3.0") ) then
    load("gcccore/7.3.0")
end
```
in the module file ? I am not sure how to best debug this. 
I can try to start from scratch.

**Comment by timeu** [comment]
Ok small update. After starting from a fresh bootstraped EB 3.9.3 and empty software tree, the SWIG installation went through with recursive unload enabled. I will try to build some more software versions and see if the fresh installation is really working without issues

**Comment by boegel** [comment]
@timeu Any updates?

**Comment by timeu** [comment]
So it seems that a fresh installation on an empty software tree, fixed the issue. 
The ticket can be closed.
