### ISSUE TITLE
`vsc-base` cannot be installed in virtualenv. It tries to copy files to central python installation

### ISSUE THREAD

**Issue by pescobar** [easybuilders/easybuild-framework#2867]
While trying to install easybuild in a virtualenv I got this error:

```
 INFO: copying vsc/install/testing.py -> /scicore/soft/apps/Python/2.7.15-foss-2018b/lib/python2.7/site-packages/vsc/install
 error: [Errno 13] Permission denied: '/scicore/soft/apps/Python/2.7.15-foss-2018b/lib/python2.7/site-packages/vsc'
```

`vsc-base`  tries to copy files to the central python installation. It can be reproduced like this:

```
virtualenv ~/venv-test
source ~/venv-test/bin/activate
pip install vsc-base==2.8.4
```

**Comment by boegel** [comment]
@pescobar This problem will mostly likely disappear with EasyBuild 4.0, since we have ingested `vsc-base` and `vsc-install`, see #2708

We should re-evaluate this when EasyBuild 4.0 is released...

**Comment by boegel** [comment]
Closing this since `vsc-base` is no longer a dependency for EasyBuild v4.0 (already the case in current `develop` branch).
