### ISSUE TITLE
self.iter_idx is bumped early

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-framework#2885]
While working on https://github.com/easybuilders/easybuild-easyblocks/pull/1718 I noticed that `self.iter_idx` is bumped before the iteration is actually fully complete (see https://github.com/easybuilders/easybuild-framework/blob/706a40b77087952f3a61a200ca6f7ddf16b1525d/easybuild/framework/easyblock.py#L1556).

Can we add another variable that gets set at the beginning of the same function? This would make leveraging the value more consistent in easyblocks. For example:
```
self.curr_idx = self.iter_idx
```
done anywhere before the bump.

**Comment by ocaisa** [comment]
I'll open a PR and we can debate there I guess

**Comment by boegel** [comment]
fixed via #2886, so closing this...
