### ISSUE TITLE
add singularity version check to container integration

### ISSUE THREAD

**Issue by migueldiascosta** [easybuilders/easybuild-framework#2925]
i.e., for me it works with singularity 3.2.1 but not with 3.0.1 (for some reason, it fails to switch to the easybuild user...)

**Comment by boegel** [comment]
@migueldiascosta The issue with switching to the `easybuild` user has been fixed in #3347 .

Also, we already have a version check, any Singularity version >= 2.4 should (still) work.

So, OK to close this issue?

**Comment by migueldiascosta** [comment]
Sure
