### ISSUE TITLE
Consider updating defaults for 4.0

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-framework#2927]
There are probably quite a few option defaults that are non-optimal only to maintain backwards compatability. We should take the opportunity to reevaluate these. 

One that made me write this issue is `--fixed-installdir-naming-scheme`, this should be on by default (there is no reason not to).

**Comment by boegel** [comment]
Makes sense.

Anything else?

We should probably discuss this during the next conf call...

**Comment by boegel** [comment]
I've walked through all configuration settings, and I don't think there are any other defaults we should change.

``--fixed-installdir-naming-scheme` is handled via #2999 

``--read-only-installdir`` was also considered, but that needs more time/testing, cfr. #123
