### ISSUE TITLE
FR: Template value for number of available threads

### ISSUE THREAD

**Issue by orbsmiv** [easybuilders/easybuild-framework#2929]
Please can a template value be provided to give the number of available threads for e.g. the `make` command? Currently this value is automatically passed to the first make target invoked by _buildopts_ but if one were to e.g.

`buildopts = "foo && make bar"`
... then the following example command would be issued: `make -j 8 foo && make bar`

Instead, the following would be convenient:

`buildopts = "foo && make -j %(parallel)s bar"`
... which would render: `make -j 8 foo && make -j 8 bar`

**Comment by boegel** [comment]
Support for a `%(parallel)s` template value was added in #3036, will be included in next EasyBuild release (v4.0.1)
