### ISSUE TITLE
Add option to put $CFGS1, $CFGS2 in front of *.eb files during `-S` output

### ISSUE THREAD

**Issue by runiq** [easybuilders/easybuild-framework#2936]
Currently, if there are multiple easyconfigs with the same name and toolchain in different `$CGFS` directories, I have to do two copy&paste operations. I'm pretty lazy—is there a way to put the `$CGFS` variablies directly into the easyconfig listings?

So, instead of

```
$ eb -S zlib
CFGS1=/software/easybuild/ebfiles_repo/zlib
CFGS2=/software/easybuild/software/EasyBuild/3.9.2/lib/python2.7/site-packages/easybuild_easyconfigs-3.9.2-py2.7.egg/easybuild/easyconfigs
 * $CFGS1/zlib-1.2.8.eb
 * $CFGS2/zlib-1.2.8.eb
```

We'd have (for example)

```
$ eb -S zlib --full-search-output
 * /software/easybuild/ebfiles_repo/zlib/zlib-1.2.8.eb
 * /software/easybuild/software/EasyBuild/3.9.2/lib/python2.7/site-packages/easybuild_easyconfigs-3.9.2-py2.7.egg/easybuild/easyconfigs/zlib-1.2.8.eb
```

**Comment by boegel** [comment]
@runiq That's exactly what `eb --search` does (`eb -S` is a shorthand for `eb --search-short`).

**Comment by runiq** [comment]
Oh, didn't notice. Sorry for the noise!

**Comment by ocaisa** [comment]
I did not know this!
