### ISSUE TITLE
building python fail during sanity check with: 'Absolute path /app/easybuild/logs/python passed to update_paths which only expects relative paths.' 

### ISSUE THREAD

**Issue by fizwit** [easybuilders/easybuild-framework#2953]
This error happens with every type of Python build, direct Python builds and PythonBundles. The error started with EasyBuild 3.9.x.  The error goes away if I downgrade to EasyBuild 3.8.x
I must be doing something wrong?

[Error.zip](https://github.com/easybuilders/easybuild-framework/files/3453902/Error.zip)

```
eb Python-3.6.9-foss-2016b.eb --module-only
== temporary log file in case of crash /tmp/eb-jhVoND/easybuild-aceEAG.log
== processing EasyBuild easyconfig /home/jfdey/git/easybuild-life-sciences/fh_easyconfigs/p/Python/Python-3.6.9-foss-2016b.eb
== building and installing Python/3.6.9-foss-2016b...
== fetching files [skipped]
== creating build dir, resetting environment...
== unpacking [skipped]
== patching [skipped]
== preparing...
== configuring [skipped]
== building [skipped]
== testing [skipped]
== installing [skipped]
== taking care of extensions [skipped]
== restore after iterating...
== postprocessing [skipped]
== sanity checking...
== FAILED: Installation ended unsuccessfully (build directory: /app/easybuild/build/Python/3.6.9/foss-2016b): build failed (first 300 chars): Loading fake module failed: 'Absolute path /app/easybuild/logs/python passed to update_paths which only expects relative paths.'
== Results of the build can be found in the log file(s) /tmp/eb-jhVoND/easybuild-Python-3.6.9-20190731.132344.caEVw.log
ERROR: Build of /home/jfdey/git/easybuild-life-sciences/fh_easyconfigs/p/Python/Python-3.6.9-foss-2016b.eb failed (err: "build failed (first 300 chars): Loading fake module failed: 'Absolute path /app/easybuild/logs/python passed to update_paths which only expects relative paths.'")
```

**Comment by damianam** [comment]
Any chance to get the log after running the command with `--debug`? The attached zip doesn't contain anything useful. Having the easyconfig could potentially be useful as well.

**Comment by boegel** [comment]
@fizwit In addition to what @damianam requested, can you share the output of `eb --show-config`?
Do you have any hooks in place?

It's possible we introduced a bug that broke `--module-only` when Python packages are involved, but the path being reported (`/app/easybuild/logs/python`) makes this look a bit fishy...

**Comment by fizwit** [comment]
```
scicomp@6fddd313878d:/ls2$ eb --show-config
#
# Current EasyBuild configuration
# (C: command line argument, D: default value, E: environment variable, F: configuration file)
#
buildpath                 (E) = /app/build
containerpath             (D) = /home/scicomp/.local/easybuild/containers
group-writable-installdir (E) = True
installpath               (D) = /home/scicomp/.local/easybuild
installpath-modules       (E) = /app/modules
installpath-software      (E) = /app/software
logfile-format            (E) = ('/app/logs', 'easybuild-%(name)s-%(version)s-%(date)s.%(time)s.log')
repositorypath            (E) = /app/ebfiles_repo
robot-paths               (E) = /app/fh_easyconfigs, /app/software/EasyBuild/3.9.0/lib/python2.7/site-packages/easybuild_easyconfigs-3.9.0-py2.7.egg/easybuild/easyconfigs
sourcepath                (E) = /app/sources
umask                     (E) = 002
```

**Comment by fizwit** [comment]
platform Ubuntu 18.04, EasyBuild 3.9.0, Module: Python-3.7.4-foss-2018b.eb
eb --debug Python-3.7.4-foss-2018b.eb --module-only
logfile: https://gist.github.com/fizwit/c63654cb3104e5478f399827f54e3c6b
easyconfig: https://github.com/FredHutch/easybuild-life-sciences/blob/master/fh_easyconfigs/p/Python/Python-3.7.4-foss-2018b.eb

**Comment by boegel** [comment]
@fizwit The problem is caused by the changes that were made in the `Python` easyblock to support installation of Python packages for multiple Python versions in a single installation prefix (via `multi_deps`).

At https://github.com/easybuilders/easybuild-easyblocks/blob/master/easybuild/easyblocks/p/python.py#L122, we assume that the directory returned by `log_path()` is a relative path (representing a subdirectory of the installation directory), while in your setup it's an absolute path `/app/logs` (see `logfile-format` in the output of `eb --show-config`).

Can you clarify that setting? Do you want keep all installation logs in a separate locations (`/app/logs`), or in an `app/logs` subdirectory under the software installation prefix?

We should probably verify that a *relative* path is specified there.

I think you should be able to fix your configuration by simply using `app/logs` rather than `/app/logs`, it should have the same effect and it should fix the problem you're observing...

**Comment by fizwit** [comment]
Solved
We do all our EasyBuild configuration in Lua module file for EasyBuild.  All environment variables are set when EasyBuild is loaded.

I have changed the value of **EASYBUILD_LOGFILE_FORMAT**, to not have an absolute path. 
```
# New LOGFILE
setenv("EASYBUILD_LOGFILE_FORMAT", "logs,easybuild-%(name)s-%(version)s-%(date)s.%(time)s.log")

# Old LOGFILE
etenv("EASYBUILD_LOGFILE_FORMAT", ebDir .. "/logs,easybuild-%(name)s-%(version)s-%(date)s.%(time)s.log")
```
