### ISSUE TITLE
`multi_deps` should be considered build dependencies

### ISSUE THREAD

**Issue by mboisson** [easybuilders/easybuild-framework#2959]
I just installed my first `multi_deps` package, and I now realize that the module is broken. The recipe I used is 
https://github.com/ComputeCanada/easybuild-easyconfigs/blob/computecanada-master/easybuild/easyconfigs/g/GEOS/GEOS-3.7.2-GCC-7.3.0.eb

The result is the following : 
```
whatis("Compatible modules: python/2.7.14 (default), python/3.5.4, python/3.6.3, python/3.7.4")
conflict("geos")
depends_on("python/2.7.14")
prepend_path("CPATH","/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc7.3/geos/3.7.2/include")
prepend_path("LIBRARY_PATH","/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc7.3/geos/3.7.2/lib")
prepend_path("PATH","/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc7.3/geos/3.7.2/bin")
setenv("EBROOTGEOS","/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc7.3/geos/3.7.2")
setenv("EBVERSIONGEOS","3.7.2")
setenv("EBDEVELGEOS","/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc7.3/geos/3.7.2/easybuild/avx2-Compiler-gcc7.3-geos-3.7.2-easybuild-devel")
prepend_path("EBPYTHONPREFIXES","/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc7.3/geos/3.7.2")

[mboisson@build-node ~]$ module load python/3.7
[mboisson@build-node ~]$ module load geos/3.7.2

The following have been reloaded with a version change:
  1) python/3.7.0 => python/2.7.14
``` 

Now, obviously, since a build with `multi_deps` is, by designed, building for various conflicting versions of a dependency, they *can not* be a run time dependency. The module does not depend on any specific version, it depends on *a* version. It may also not even depend on having a version loaded for runtime. May of the use-cases we have is to install python bindings to otherwise non-python packages. Those should not even depend on python, it only depends on it if users want to use the python binding. It should not mess with python loaded by the user.

**Comment by mboisson** [comment]
This seems to have been implemented in https://github.com/easybuilders/easybuild-framework/pull/2828

Can we disable that through a flag ? I would argue that this is fundamentally broken.

**Comment by mboisson** [comment]
I see in the code `multi_deps_load_default`. I'll try that.

**Comment by boegel** [comment]
@mboisson The idea here was to avoid that people were forced to load a `Python` module as well before getting a *working* environment.

We load the first listed `Python` version by default unless a `Python` is already loaded, and construct the module such that you can swap to another compatible `Python` version if you need that instead...

**Comment by mboisson** [comment]
You can’t know whether an environment is working for the user or not unless you know what the user wants to do. I looked at the code that checks the loaded version, loads the default, and allows to swap.   
  

  
On one side, the code can yields a non working environment for the user. For example, we have python/3.7.0 and 3.7.4. Both work with the same build, so there is no reason to rebuild for both. Yet, the module code, as written, will simply break if the user has a different version than the very specific version that you installed it with. This applies to any and all future minor versions of python that you might install.
  

  
On the other side, there are plenty of cases in which loading python is simply not required to get a working environment. For example, why would you load python by default when loading Qt (we install PyQt as part of Qt), or why would you load python as part of OpenMPI (we have considered installing mpi4py as part of the OpenMPI module).
  

  
  

  
  
>
