### ISSUE TITLE
Undocumented hard requirement for the `which` command

### ISSUE THREAD

**Issue by zao** [easybuilders/easybuild-framework#2976]
The `eb` wrapper script has a hard requirement on the `which` command to figure out what Python to run, but the command is not present on my container installation of CentOS 7.6 pulled from Docker.

This results in `ERROR: python not available in $PATH?` errors during sanity check when installing EasyBuild itself, or at run-time for EasyBuild-develop.

This should probably be documented in the guide as mandatory.

**Comment by boegel** [comment]
I'm aware of this, and it's actually a silly requirement, since we can actually replace the use of `which` with the shell builtin `command -v`, no need for relying on `which` at all...

**Comment by boegel** [comment]
@zao Should be fixed with #2979...

**Comment by akesandgren** [comment]
And are you sure your running under a sh like shell and not csh?

**Comment by boegel** [comment]
@akesandgren The `eb` script has `/bin/bash` in the shebang

**Comment by akesandgren** [comment]
Ah yes, i forgot about that.

**Comment by boegel** [comment]
fixed with #2979
