### ISSUE TITLE
using "eb --skip --force" to install additional extensions fails if original installation was done with "--read-only-installdir"

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#3033]
For example, when installing additional extensions for `R-bundle-Bioconductor:

```
Error: ERROR: no permission to install to directory /software/R-bundle-Bioconductor/3.9-foss-2019a-R-3.6.0
```

**Comment by damianam** [comment]
Mmmh, is this really a bug? I see that as the owner of the installation you might not want to be bothered with these pesky things. But in shared environments, if I use `--read-only-installdir` maybe I don't want others to add things to my setup. The current behaviour acts at least as a measure to disuade them.

**Comment by boegel** [comment]
@damianam As long as the account used to run `eb` has the permissions to enable write permissions on the installation directory, EasyBuild should temporarily re-enable write permissions when `--skip --force` is used, so additional extensions can be installed.

The read-only permissions are mostly set to prevent easyconfig A (for example a Python package) installing stuff in the installation directory of B (for example the `Python` installation itself).
