### ISSUE TITLE
EASYBUILD_FIXED_INSTALLDIR_NAMING_SCHEME variable not taken in account

### ISSUE THREAD

**Issue by guest1604** [easybuilders/easybuild-framework#3043]
Hello. I notice EASYBUILD_FIXED_INSTALLDIR_NAMING_SCHEME variable is not taken in account.

```
$ export EASYBUILD_FIXED_INSTALLDIR_NAMING_SCHEME=False 
$ eb --show-full-config | grep fixed
fixed-installdir-naming-scheme            (D) = True

```

Thanks for your help.

**Comment by boegel** [comment]
@guest1604 This is a bit confusing, but you need to define `$EASYBUILD_FIXED_INSTALLDIR_NAMING_SCHEME` to a value that evaluates to `False`, not literally to (the string value) `'False'`, since:

```shell
$ python
>>> bool('False')
True
```

This works (because `0` is recognized as a special value):

```
$ export EASYBUILD_FIXED_INSTALLDIR_NAMING_SCHEME=0
$ eb --show-full-config | grep fixed
fixed-installdir-naming-scheme            (F) = False
```

As documented at https://easybuild.readthedocs.io/en/develop/EasyBuild4-overview-of-changes.html#disabling-fixed-installdir-naming-scheme, you can also define `$EASYBUILD_DISABLE_FIXED_INSTALLDIR_NAMING_SCHEME` (not the `_DISABLE_` part).

**Comment by guest1604** [comment]
It's a little bit confusing since False/True works in the configuration file, but I understand, thanks for your explanation. However I still have this problem using `export EASYBUILD_FIXED_INSTALLDIR_NAMING_SCHEME=0`. 

**I notice this issue with all boolean variables set to True by default**. 
I have the same issue with EasyBuild 3.4.1 (tested with EASYBUILD_MPI_TESTS) so this not related to the version of EasyBuild.

```
$ eb --version
>> Considering 'python'...
>> 'python' version: 2.7.5, which matches Python 2 version requirement (>= 2.6)
>> Selected Python command: python (/usr/bin/python)
>> python -m easybuild.main --version
This is EasyBuild 4.0.0 (framework: 4.0.0, easyblocks: 4.0.0) on host irlin361609.ifp.fr.

$ env | grep FIXED_INSTALLDIR_NAMING_SCHEME

$ export EASYBUILD_FIXED_INSTALLDIR_NAMING_SCHEME=0
$ eb --show-full-config | grep fixed
fixed-installdir-naming-scheme            (D) = True

$ export EASYBUILD_FIXED_INSTALLDIR_NAMING_SCHEME=1
$ eb --show-full-config | grep fixed
fixed-installdir-naming-scheme            (D) = True
```

But EASYBUILD_DISABLE_FIXED_INSTALLDIR_NAMING_SCHEME=1 works fine :

```
$ export EASYBUILD_DISABLE_FIXED_INSTALLDIR_NAMING_SCHEME=0
$ eb --show-full-config | grep fixed
fixed-installdir-naming-scheme            (D) = True

$ export EASYBUILD_DISABLE_FIXED_INSTALLDIR_NAMING_SCHEME=1
$ eb --show-full-config | grep fixed
fixed-installdir-naming-scheme            (E) = False
```

**Comment by boegel** [comment]
@guest1604 My apologies, I overlooked that I had a configuration file with `fixed-installdir-naming-scheme = 0` in it (as indicated by the `F` in the output of `--show-full-config` I showed above.

You indeed need to use `$EASYBUILD_DISABLE_*` to disable boolean settings via an environment variable (or `--disable-*` on the command line).
