### ISSUE TITLE
Upgrade to 4.0.1 fails during sanity_check with vsc-base error

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-framework#3057]
On a CentOS 7 system that is running EB `3.9.0`, I find that using `eb --install-latest-eb-release` fails:
```
== 2019-10-22 08:15:17,867 easyblock.py:2766 INFO Running method sanity_check_step part of step sanitycheck
== 2019-10-22 08:15:17,900 build_log.py:163 ERROR EasyBuild crashed with an error (at ?:124 in __init__): Failed to isolate installed egg dir for vsc-base (at easybuild/easyblocks/e/easybuildmeta.py:178 in sanity_check_step)
== 2019-10-22 08:15:17,900 easyblock.py:3010 WARNING build failed (first 300 chars): Failed to isolate installed egg dir for vsc-base
== 2019-10-22 08:15:17,900 easyblock.py:293 INFO Closing log for application name EasyBuild version 4.0.1
```

**Comment by verdurin** [comment]
Anything I can provide to help debug this one?

**Comment by boegel** [comment]
@verdurin Please try updating to EasyBuild v3.9.4 first, EasyBuild v3.9.0 doesn't have the required fixes yet in the `EasyBuildMeta` easyblock (see https://github.com/easybuilders/easybuild-easyblocks/pull/1757).

So, using EasyBuild v3.9.0: `eb --from-pr 8821` (see https://github.com/easybuilders/easybuild-easyconfigs/pull/8821).
Then `module swap EasyBuild/3.9.4` + `eb --install-latest-eb-release`.

That should do the trick...

**Comment by boegel** [comment]
confirmed via IRC that jumping to v3.9.4 works as expected, so closing...
