### ISSUE TITLE
Error building toolchains with --module-depends-on and maybe also --module-syntax=Tcl

### ISSUE THREAD

**Issue by douglasgscofield** [easybuilders/easybuild-framework#3058]
We're a centre new to EasyBuild.  We are trying to install the foss-2018b toolchain but it keeps failing attempting to install FFTW-3.3.8-gompi-2018b with what seems to be a straightforward config mismatch, but with our *very* limited experience we can't see anything obvious.  It doesn't install with EasyBuild 3.8.1 either.

I emailed the EasyBuild mailing list and Bart Oldeman suggested opening an issue.  He wrote it might be a framework bug associated with using `--module-depends-on` perhaps together with `--module-syntax=Tcl`.

> this smells like a framework bug in the parsing of depends_on in Tcl module files to figure out the dependencies.

```
$ eb --module-depends-on --robot --module-syntax=Tcl foss-2018b.eb
== temporary log file in case of crash /scratch/eb-dFaRLw/easybuild-eFncBe.log
== resolving dependencies ...
== processing EasyBuild easyconfig /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-gompi-2018b.eb
== building and installing FFTW/3.3.8-gompi-2018b...
== fetching files...
== creating build dir, resetting environment...
== starting iteration #0 ...
== unpacking...
== patching...
== preparing...
== FAILED: Installation ended unsuccessfully (build directory: /sw/EasyBuild/build/FFTW/3.3.8/gompi-2018b): build failed (first 300 chars): List of toolchain dependency modules and toolchain definition do not match (found [] vs expected set(['GCC', 'OpenMPI'])) (took 17 sec)
== Results of the build can be found in the log file(s) /scratch/eb-dFaRLw/easybuild-FFTW-3.3.8-20191023.101730.GDYpv.log
ERROR: Build of /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-gompi-2018b.eb failed (err: "build failed (first 300 chars): List of toolchain dependency modules and toolchain definition do not match (found [] vs expected set(['GCC', 'OpenMPI']))")
```

At the suggestion of Alan O'Cais, here is `eb --dry-run gompi-2018b.eb`:
```
$ eb  --dry-run gompi-2018b.eb
== temporary log file in case of crash /scratch/eb-qUHeQG/easybuild-8PK2Hu.log
Dry run: printing build status of easyconfigs and dependencies
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/m/M4/M4-1.4.18.eb (module: M4/1.4.18)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/z/zlib/zlib-1.2.11.eb (module: zlib/1.2.11)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/h/help2man/help2man-1.47.4.eb (module: help2man/1.47.4)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/m/M4/M4-1.4.17.eb (module: M4/1.4.17)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/b/Bison/Bison-3.0.4.eb (module: Bison/3.0.4)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/f/flex/flex-2.6.4.eb (module: flex/2.6.4)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/b/binutils/binutils-2.30.eb (module: binutils/2.30)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/g/GCCcore/GCCcore-7.3.0.eb (module: GCCcore/7.3.0)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/z/zlib/zlib-1.2.11-GCCcore-7.3.0.eb (module: zlib/1.2.11-GCCcore-7.3.0)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/h/help2man/help2man-1.47.4-GCCcore-7.3.0.eb (module: help2man/1.47.4-GCCcore-7.3.0)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-7.3.0.eb (module: M4/1.4.18-GCCcore-7.3.0)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-7.3.0.eb (module: Bison/3.0.4-GCCcore-7.3.0)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/b/Bison/Bison-3.0.5-GCCcore-7.3.0.eb (module: Bison/3.0.5-GCCcore-7.3.0)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-7.3.0.eb (module: flex/2.6.4-GCCcore-7.3.0)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/b/binutils/binutils-2.30-GCCcore-7.3.0.eb (module: binutils/2.30-GCCcore-7.3.0)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-GCCcore-7.3.0.eb (module: Autoconf/2.69-GCCcore-7.3.0)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/g/GCC/GCC-7.3.0-2.30.eb (module: GCC/7.3.0-2.30)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/a/Automake/Automake-1.16.1-GCCcore-7.3.0.eb (module: Automake/1.16.1-GCCcore-7.3.0)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/l/libtool/libtool-2.4.6-GCCcore-7.3.0.eb (module: libtool/2.4.6-GCCcore-7.3.0)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/n/ncurses/ncurses-6.0.eb (module: ncurses/6.0)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/a/Autotools/Autotools-20180311-GCCcore-7.3.0.eb (module: Autotools/20180311-GCCcore-7.3.0)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.2-GCCcore-7.3.0.eb (module: xorg-macros/1.19.2-GCCcore-7.3.0)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/g/gettext/gettext-0.19.8.1.eb (module: gettext/0.19.8.1)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCCcore-7.3.0.eb (module: numactl/2.0.11-GCCcore-7.3.0)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.14-GCCcore-7.3.0.eb (module: libpciaccess/0.14-GCCcore-7.3.0)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/x/XZ/XZ-5.2.4-GCCcore-7.3.0.eb (module: XZ/5.2.4-GCCcore-7.3.0)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/l/libxml2/libxml2-2.9.8-GCCcore-7.3.0.eb (module: libxml2/2.9.8-GCCcore-7.3.0)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/h/hwloc/hwloc-1.11.10-GCCcore-7.3.0.eb (module: hwloc/1.11.10-GCCcore-7.3.0)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.1-GCC-7.3.0-2.30.eb (module: OpenMPI/3.1.1-GCC-7.3.0-2.30)
 * [x] /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/g/gompi/gompi-2018b.eb (module: gompi/2018b)
== Temporary log file(s) /scratch/eb-qUHeQG/easybuild-8PK2Hu.log* have been removed.
== Temporary directory /scratch/eb-qUHeQG has been removed.
```

Since my original report to the mailing list this popped up again attempting to install `iomkl-2018b.eb` with these same options.  `eb --module-depends-on --robot intel-2018b.eb` installed successfully. Doing `eb --module-depends-on --robot --module-syntax=Tcl iomkl-2018b.eb` after this generates the following error.

<pre>
$ eb --module-depends-on --robot --module-syntax=Tcl iomkl-2018b.eb
== temporary log file in case of crash /scratch/eb-WuJ95g/easybuild-6948qh.log
== resolving dependencies ...
== processing EasyBuild easyconfig /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.1-iccifort-2018.3.222-GCC-7.3.0-2.30.eb
== building and installing OpenMPI/3.1.1-iccifort-2018.3.222-GCC-7.3.0-2.30...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== restore after iterating...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully (took 19 min 20 sec)
== Results of the build can be found in the log file(s) /sw/EasyBuild/software/OpenMPI/3.1.1-iccifort-2018.3.222-GCC-7.3.0-2.30/easybuild/easybuild-OpenMPI-3.1.1-20191023.134630.log
== processing EasyBuild easyconfig /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/i/iompi/iompi-2018b.eb
== building and installing iompi/2018b...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== restore after iterating...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully (took 6 sec)
== Results of the build can be found in the log file(s) /sw/EasyBuild/software/iompi/2018b/easybuild/easybuild-iompi-2018b-20191023.134637.log
== processing EasyBuild easyconfig /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/i/imkl/imkl-2018.3.222-iompi-2018b.eb
== building and installing imkl/2018.3.222-iompi-2018b...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== FAILED: Installation ended unsuccessfully (build directory: /sw/EasyBuild/build/imkl/2018.3.222/iompi-2018b): build failed (first 300 chars): List of toolchain dependency modules and toolchain definition do not match (found [] vs expected set(['icc', 'OpenMPI', 'ifort'])) (took 23 sec)
== Results of the build can be found in the log file(s) /scratch/eb-WuJ95g/easybuild-imkl-2018.3.222-20191023.134637.OoadV.log
ERROR: Build of /sw/EasyBuild/software/EasyBuild/4.0.1/easybuild/easyconfigs/i/imkl/imkl-2018.3.222-iompi-2018b.eb failed (err: "build failed (first 300 chars): List of toolchain dependency modules and toolchain definition do not match (found [] vs expected set(['icc', 'OpenMPI', 'ifort']))")
</pre>

**Comment by boegel** [comment]
@douglasgscofield Thanks for the bug report (and my apologies for not picking up on this sooner).

You've indeed hit a bug, the regular expression for module files in Tcl syntax to extract `depends-on` statements is incorrect, I'll look into fixing that...
