### ISSUE TITLE
Fix usage of 'exts_filter'

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-framework#3124]
When building Python 3.7.4 there are 148 warning messages like:

`WARNING Unable to resolve template value python -c "import %(ext_name)s" with dict {'bitbucket_account': 'python', 'nameletterlower': 's', 'versionsuffix': '', 'toolchain_name': 'GCCcore', 'namelower': 'sphinxcontrib-qthelp', 'version_minor': '0', 'arch': 'ppc64le', 'versionprefix': '', 'name': 'sphinxcontrib-qthelp', 'version_major': '1', 'nameletter': 's', 'version_major_minor': '1.0', 'version': '1.0.2', 'github_account': 'python', 'toolchain_version': '8.3.0'}`

This is mostly caused by the line https://github.com/easybuilders/easybuild-framework/blob/364590cfb5be6cac959f024fd60f8ebb8fad7d92/easybuild/framework/extensioneasyblock.py#L121

1. Please clarify the meaning of `exts_filter`. The docu `"Extension filter details: template for cmd and input to cmd (templates for name, version and src)."` is not helpful and incorrect. PythonPackage sets it to `('python -c "import %(ext_name)s"', '')`, and Extension describes "name" and "version" as ` deprecated, remove in v2.0` while EasyBlock seems to expect a `list or tuple of ("command","input")`
2. Can the default value be changed to `python -c "import %(modulename)s"` which **is**  set by PythonPackage?
3. Instead of 2: Set the correct options: 
  - 'modulename' -> 'ext_name'
  - ' version' -> ' ext_version'
4. Or fix up the code, see e.g. https://github.com/Flamefire/easybuild-framework/commit/1079546e5fcb8e989653aee621fad471d1a7f2b7

**Comment by boegel** [comment]
The `exts_filter` is used to determine whether or not an extension is installed already, and it is used when `eb --skip` is used and also during the sanity check, to verify whether all listed extensions are actually installed.

The change in https://github.com/Flamefire/easybuild-framework/commit/6924d441fdb808eb166bcce28ccd27c6bdfd2c20 makes sense to avoid triggering the warning.

The template specified in `exts_filter` is only completed in `Extension.sanity_check_step`, so whenever we grab the value we should indeed use `get_ref` to avoid triggering the warning.

I need to take a closer look at https://github.com/Flamefire/easybuild-framework/commit/1079546e5fcb8e989653aee621fad471d1a7f2b7, but it seems like you're fleshing out the duplicate code in `easyblock.py` and `extension.py`, which makes perfect sense.

@Flamefire Can you open a pull request for these changes, for easy review?

**Comment by Flamefire** [comment]
I was just in the process of doing that and fixing up the description ;)
