### ISSUE TITLE
get_software_libdir fails for symlinked lib64->lib

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-framework#3139]
An installation of SuperLU fails due to it calling `openblas_lib = os.path.join(get_software_root('OpenBLAS'), get_software_libdir('OpenBLAS'), "libopenblas.a")` with an implicit `only_one=True` parameter to `get_software_libdir` but that finds `lib` and `lib64` and fails with an error.

The problem is that (our?) installation of `OpenBLAS/0.2.20-GCC-6.4.0-2.28` contains a symlink `lib64 -> lib`.

There are multiple solutions to this:
1. Reinstall OpenBLAS w/o the symlink. I guess it was manually added because I can't see it in the reinstalled one. But maybe this makes something else fail
2. SuperLU should be a) using `get_software_libdir('OpenBLAS', fs=["libopenblas.a"]) and b) then allow multiple dirs to be returned and simply pick the first
3. `get_software_libdir` should not return/check paths which are the same real path (resolving symlinks). I'd prefer this as this is the more universal solution that avoids problems in other EBs

**Comment by boegel** [comment]
@Flamefire Can you provide some more details on how the `SuperLU` installation is failing exactly?

`get_software_libdir` basically just does `os.path.exists`, it's not actively trying to resolve symlinks at all...

**Comment by boegel** [comment]
OK, I think I understand... See fix in #3141

**Comment by Flamefire** [comment]
Updated the issue, sorry for the brevity.
