### ISSUE TITLE
DEB package version doesn't follow dpkg policy

### ISSUE THREAD

**Issue by Mycron** [easybuilders/easybuild-framework#3143]
Hi!
I'm using EasyBuild v4.0.0 and creating a deb package to distribute it in such way.
I faced a problem while installing package with en error like this:

> debconf: delaying package configuration, since apt-utils is not installed
dpkg: error processing archive /tmp/apt-dpkg-install-RmYRki/0-m4-1.4.17_eb-4.0.0-48_amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'm4-1.4.17':
 error in 'Version' field string 'eb-4.0.0-48': version number does not start with digit

I found that by the default(using **EasyBuildPNS** class) value of a version field is composing from eb-**EASYBUILD_VERSION** which doesn't comply with [Debian policy manual](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-version) and **should start with a digit**

**Comment by Mycron** [comment]
The same error happens using EasyBuild 4.1.0 version

**Comment by boegel** [comment]
Thanks for the problem report @Mycron!

Fixing this is sort of painful now, since people may be expecting that we stick to the `eb-<easybuild_version>` format for the package version.

What would be an acceptable format? Would `<easybuild_version>-eb` work? Any other suggestions?

**Comment by Mycron** [comment]
Hi, @boegel !
We fixed this issue in our project just creating separate package naming scheme class and point to it using cmd option --package-naming-scheme=<PNS_name>. In our project, we decided to use a form of <STACK_RELEASE>.<BUILD_DATE> and PACKAGE_RELEASE equals to build number(using Jenkins), where:
STACK_RELEASE - digit, like a major part of the commonly used version scheme. Because we are using a bunch of modules as one thing(we call it - software stack)
BUILD_DATE - just a date in form of YYYYMMDD

**Comment by boegel** [comment]
@Mycron That makes a lot of sense...

So with that in mind, is there anything we should change in EasyBuild itself? Doesn't seem like there is?

**Comment by Mycron** [comment]
Hi, @boegel !
I can make a proposal(changes, that can be useful) using my fork and create PR into the base branch.
Sorry for the delay, it was a Christmas holiday in Russia for a few days

**Comment by boegel** [comment]
@Mycron Sounds good!
