### ISSUE TITLE
codecov and coverage reports

### ISSUE THREAD

**Issue by shahzebsiddiqui** [easybuilders/easybuild-framework#3155]
@boegel 

it makes sense to have codecov visualize coverage report. That will help eb maintainers to focus time in regression testing. Here is what codecov looks like https://codecov.io/gh/HPC-buildtest/buildtest-framework

Just add codecov app to easybuild-framework, easyblocks, etc... 

https://github.com/marketplace/codecov

Travis will automatically push coverage reports to codecov

**Comment by boegel** [comment]
Thanks for the suggestion @shahzebsiddiqui, sounds useful indeed.

**Comment by shahzebsiddiqui** [comment]
@boegel  might as well add coveralls https://github.com/marketplace/coveralls looks much better with more details. Works with Travis.

Check out Julia coveralls report https://coveralls.io/github/JuliaLang/julia 

You can view this PR for more details on implementation https://github.com/HPC-buildtest/buildtest-framework/pull/149

**Comment by boegel** [comment]
@shahzebsiddiqui OK to close now #3204 is merged?

**Comment by shahzebsiddiqui** [comment]
yep thanks @boegel  issue closed!
I dont see point of having codecov unless if you want codecov bot on PR report. That can be a separate issue
