### ISSUE TITLE
GCC compiler related problems : Make Error 126

### ISSUE THREAD

**Issue by grotewold-lab** [easybuilders/easybuild-framework#3243]
Dear easybuild developers 

I'm having troubles installing tools when they depend on gcc as compilers (not with intel or  foss) 
specially if depends on GCCcore-7.3.0 or GCCcore-6.4.0
The error message are not helpful to fix the issue
`build failed (first 300 chars): cmd "./Configure -de  -Dcc="gcc" -Dccflags="-O2 -ftree-vectorize -march=native -fno-math-errno -fPIC" -Dinc_version_list=none  ` 
or 
`failed (err: 'build failed (first 300 chars): cmd " make -j 32 " exited with exit code 2 and output:\ncd man && make DESTDIR=""` 

In the log file  : 

`build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): cmd " make -j 32 " exited with exit code 2 and output:
make[1]: *** [term.h] Error 126
make[1]: *** [parametrized.h] Error 126
make[1]: *** [ncurses_def.h] Error 126
make: *** [all] Error 2`

Thanks in advance 
Server features
OS  Red Hat Enterprise Linux Server 7.7 x86-64
`python --version`
Python 3.7.0
`module -v`
Version 8.2.7
`module av EasyBuild`
EasyBuild/4.1.1

**Comment by boegel** [comment]
@grotewold-lab My apologies for the late reply...

Can you share the full log file for this, since the actual problem is not exposed yet based on what you shared.

You should probably look for "`Error 1`" in the log, the actual errors should be a couple of lines higher in the `make` output.

One possible issue is a lack of sufficient memory, building GCC with `make -j 32` can be quite memory hungry. If that's the problem, it would manifest with errors like "`Bus error`" or "`Segmentation fault`".

**Comment by Sailendra1920** [comment]
all: testlib

testlib: libsqlinsert.o libfetchdata.o
		gcc -c teslib.c -o testing && ./testing

libsqlinsert.o: fetchdata.h sqlinsert.h
		gcc -c libsqlinsert.c

libfetchdata.o: fetchdata.h 
		gcc -c libfetchdata.c
sqlinsert.h: fetchdata.h
		gcc -c sqlinsert.h -lmariadbclient -L/usr/include/mariadb/mysql

fetchdata.h:
		gcc fetchdata.h -lcurl -L/usr/include/x86_64-linux-gnu/curl/curl.h

clean:
		rm *.o


Output goes like::
gcc -c sqlinsert.h -lmariadbclient -L/usr/include/mariadb/mysql
gcc -c libsqlinsert.c
gcc -c libfetchdata.c
gcc -c teslib.c -o testing && ./testing
/bin/sh: 1: ./testing: Permission denied
make: *** [Makefile:4: testlib] Error 126


dunno wats the error for

**Comment by boegel** [comment]
No reply for over 3 years, so closing this...
