### ISSUE TITLE
Installing extensions from git repository

### ISSUE THREAD

**Issue by jotelha** [easybuilders/easybuild-framework#3251]
Usually, it is possible to install from a git repository directly, and without looking at the mechanisms in too much detail, I believe that this works by providing `git_config` at

https://github.com/easybuilders/easybuild-framework/blob/210743d0e3618a8ac0a56eb9c0f4fa4fd8ae53b9/easybuild/framework/easyblock.py#L379

However, I was not able to figure out how to do the same for an extension (defined within the `exts_list` easyconfig parameter), and I suspect that might be due to the fact that no `git_config` from an extension's options is passed at 

https://github.com/easybuilders/easybuild-framework/blob/0b7a627f28131633870148d643c0286bc348206c/easybuild/framework/easyblock.py#L520

Why not? Wouldn't that be useful, i.e. for installing a custom python repository via git together with its dependencies (say, standard pipy packages) in a `PythonBundle`?

**Comment by boegel** [comment]
@jotelha Building extensions straight from a Git repository is currently not supported, and yes this would be useful.

For extensions, the way to specify which source to use is a bit crippled: all you can use is `source_tmpl`, as opposed to `sources` for non-extensions (where you can use `git_config`, see https://easybuild.readthedocs.io/en/latest/Writing_easyconfig_files.html#downloading-from-a-git-repository).

The easiest way to ensure you can use `git_config` for extensions is probably to make sure that `sources` is picked up for extensions (and then probably deprecate the custom `source_tmpl` which only works for extensions)...

**Comment by boegel** [comment]
Relevant recent PR by @kelseymh: #3294
