### ISSUE TITLE
pyver and pyshortver template names don't work with cray-python

### ISSUE THREAD

**Issue by ekouts** [easybuilders/easybuild-framework#3263]
I am not sure if this a bug or a feature request. As far as I understood the pyver and pyshortver templates should work with external module `cray-python` as long as there is an entry in the external-modules-metadata file.

I have for example this easyconfig:
```
easyblock = 'PythonPackage'

name = 'parameterized'
version = '0.6.1'

py_maj_ver = '3'
py_min_ver = '6'
py_rev_ver = '5.7'

versionsuffix = '-python%s' % py_maj_ver

homepage = 'https://pypi.python.org/pypi/%s' % name
description = """Parameterized testing with any Python test framework."""

toolchain = {'name': 'CrayGNU', 'version': '19.10'}

source_urls = [PYPI_SOURCE]
sources = [SOURCE_TAR_GZ]

dependencies = [
     ('cray-python/3.6.5.7', EXTERNAL_MODULE),
]

sanity_check_paths = {
    'files': [],
    'dirs': ['lib/python%(pyshortver)s/site-packages'],
}

exts_filter = ('python -c "import parameterized"', "")

moduleclass = 'tools'
```

which fails with the error:
```
.../parameterized-0.6.1-CrayGNU-19.10-python3.eb failed (err: "build failed (first 300 chars): Sanity check failed: no (non-empty) directory found at 'lib/python%(pyshortver)s/site-packages' in /apps/dom/UES/eirinik/easybuild/software/parameterized/0.6.1-CrayGNU-19.10-python3")
```

If I replace this line:
```
'dirs': ['lib/python%(pyshortver)s/site-packages'],
```
with
```
'dirs': ['lib/python3.6/site-packages'],
```
the installation is completed successfully.

I checked the metadata file (https://github.com/eth-cscs/production/blob/master/easybuild/cray_external_modules_metadata-19.10.cfg) and it has this entry
```
[cray-python/3.6.5.7]
name = Python
version = 3.6.5.7
prefix = /opt/python/3.6.5.7
```

Am I missing something in the easyconfig or should there be some change in the framework to be able to use these template values?

**Comment by boegel** [comment]
@ekouts Do you remember if this ever worked with the `cray-python` external module as dependency?

It's probably not very difficult to fix this, regardless whether it worked or not, it's possible we're simply not taking into account external modules when defining the templates right now...

**Comment by ekouts** [comment]
That's great, as far as I know it never worked with `cray-python`.

**Comment by boegel** [comment]
@ekouts I've reproduced the problem in a test and implemented a fix for this issue in https://github.com/easybuilders/easybuild-framework/pull/3273
