### ISSUE TITLE
Can extensions' builds take configuration options?

### ISSUE THREAD

**Issue by kelseymh** [easybuilders/easybuild-framework#3266]
As discussed in EasyConfig issue #[10318](https://github.com/easybuilders/easybuild-easyconfigs/issues/10318), I'm having an issue with the libllvmlite.so resolving its dependent libraries at runtime.

Is it possible to pass build options through to the extensions (exts_list) from an EasyConfig?

**Comment by ocaisa** [comment]
Sorry for the slow reply. For posterity, yes this is indeed possible, see https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/a/Arrow/Arrow-0.7.1-intel-2017b-Python-3.6.3.eb as an example (`confgiopts` etc. can be passed in the same way)

**Comment by kelseymh** [comment]
Should this be included in the documentation?

**Comment by boegel** [comment]
@kelseymh I guess this could be clarified in the documentation, but since this basically concerns which keys you can use in `exts_list` (basically anything listed in `eb -a`), it should be documented separate (and linked from the `exts_list` entry), I guess...

This has been supported since EasyBuild v3.2.0 btw (see #2194)

**Comment by kelseymh** [comment]
@boegel Thank you very much for your follow up!  I wish GitHub's search was better; that PR should have come up when I was looking for an aswer.  Perhaps a note in the "extensions parameters" documentaton would be enough?

**Comment by kelseymh** [comment]
Okay, I just tried one specific case, which failed.  Our experiment's (CDMS) code is maintained in a Git repository, but we don't make or distribute tar-balls, we just check it out for building.  For regular modules using 'CMakeMake', I was able to deal with the easily with
a `git_config` block:

    sources = [{
        'filename' : '%(name)s-v%(version)s.tar.gz',
        'git_config': {
            'url' : 'ssh://nero.stanford.edu/data/git/Reconstruction/',
            'repo_name' : name,
            'tag' : 'v%(version)s',
        },
    }]

But I've learned that 'PythonBundle' doesn't use `sources` at all (in fact, it throws an error if you try).  I tried taking the structure above and putting into `exts_list`, but this didn't work either (specifically, it didn't create a tarball on the fly):

    exts_list = [
        (name, version, {
            'modulename': name,
    	    'filename': '%(name)s-v%(version)s.tar.gz',
            'git_config': {
                'url': 'ssh://nero.stanford.edu/data/git/Analysis/',
	        'repo_name': name,
	        'tag': 'v%(version)s#egg=cdms[rawio]',	# Is this right?
            }
        }),
    ]

For my person use case, I'd love an example of how to do a Git source download like this.  With that in hand, I will expand the addition I made to the documentation in [EB PR #617](https://github.com/easybuilders/easybuild/pull/617).

**Comment by kelseymh** [comment]
I'm following up on this stuff in the mailing list, and will come back with a solution here.

**Comment by boegel** [comment]
@kelseymh I think this issue can be closed now, since: #3290 is closed via #3294, and docs are updated in https://github.com/easybuilders/easybuild/pull/617
