### ISSUE TITLE
--upload-test-report should post comment with test report in easyblocks PR if --include-easyblock-from-pr was used

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#3289]
(but only if it's used without `--from-pr`)

That would be useful to have a record of with which existing easyconfigs testing was done for PRs that change existing easyblocks (like https://github.com/easybuilders/easybuild-easyblocks/pull/2030 for example).

Test case, using `Score-P-6.0-gompi-2019a.eb` easyconfig file that is already included in EasyBuild releases:

```shell
eb Score-P-6.0-gompi-2019a.eb -f --include-easyblocks-from-pr 2030
```

**Comment by migueldiascosta** [comment]
in the `--from-pr` case, we could reference the easyblock PR in the easyconfig PR comment?
