### ISSUE TITLE
fetch_extension_sources does not appear to support 'git_config'

### ISSUE THREAD

**Issue by kelseymh** [easybuilders/easybuild-framework#3290]
I'm attempting to build a `PythonBundle` for one of my experiment's Git packages.  For other "regular" (i.e., C++) packages, I was able to configure `sources` with the `git_config` dictionary setup, and have it create a local tar-ball on the fly (as done in [OpenFOAM-Extend](https://github.com/easybuilders/easybuild-easyconfigs/blob/377a1e92e1df9d75bdfa78245bcb6917c2b8a9f2/easybuild/easyconfigs/o/OpenFOAM-Extend/OpenFOAM-Extend-4.1-20191120-intel-2019b-Python-2.7.16.eb#L19),
but with a tag, not a commit SHA).  I'm trying to do this now in `exts_list`, with a deeply nested construction:

    exts_list = [
        (name, version, {
            'modulename': name,
            'source_tmpl': {
                'filename': '%(name)s-v%(version)s.tar.gz',
                'git_config': {
                    'url': 'ssh://nero.stanford.edu/data/git/Analysis/',
                    'repo_name': name,
                    'tag': 'v%(version)s#egg=cdms[rawio]',  # Is this right?        
                }
            }
        }),
    ]

Unfortunately, this fails, returning a regexp mismatch:

    [...]
      File "/sw/eb/sw/EasyBuild/2020a-sprint/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 520, in fetch_extension_sources
        src_fn = self.obtain_file(fn, extension=True, urls=source_urls, force_download=force_download)
      File "/sw/eb/sw/EasyBuild/2020a-sprint/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 598, in obtain_file
        if re.match(r"^(https?|ftp)://", filename):
      File "/usr/lib64/python2.7/re.py", line 137, in match
        return _compile(pattern, flags).match(string)
    TypeError: expected string or buffer
     (at easybuild/main.py:147 in build_and_install_software)

I see that the problem is here:
https://github.com/easybuilders/easybuild-framework/blob/7fa6c42d111fde358eba114fa3e55f3cd93b4156/easybuild/framework/easyblock.py#L520
where the additional `git_config` argument to `obtain_file()` is not being passed.

I think this could be fixed by adding after line 518:

    git_config = ext_options.get('git_config', None)

and adding that option to the end of line 520:

    src_fn = self.obtain_file(fn, extension=True, urls=source_urls, force_download=force_download, git_config=git_config)

I don't know how to test this, since this the topmost level `framework/easyblock.py`, and I'm not sure I can override it with a local version.

**Comment by kelseymh** [comment]
I was able to successfully test this (see my note in PR #3294 .  Awaiting review.

**Comment by boegel** [comment]
Fixed in #3294, so closing, thanks @kelseymh!
