### ISSUE TITLE
Replace usage of distutils.dir_util

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-framework#3306]
User fizwit reported on Slack that distutils may not be installed, see https://github.com/spack/spack/issues/8968#issuecomment-412647398

From tgamblin

> There is also this issue with distutils.dir_util that led us to stop using it entirely — it’s only designed to be used once in a process:
https://github.com/spack/spack/pull/8182#pullrequestreview-121560040
it actually caches directory creations in a global, so if you somehow end up having to create the same directory twice, it won’t work the second time.

Hence remove the usage of `distutils.dir_util` introduced in https://github.com/easybuilders/easybuild-framework/pull/3270

Possible replacements:

- https://stackoverflow.com/questions/1868714/how-do-i-copy-an-entire-directory-of-files-into-an-existing-directory-using-pyth
- https://spack.readthedocs.io/en/latest/llnl.util.html#llnl.util.filesystem.copy_tree

**Comment by boegel** [comment]
fix implemented in #3310
