### ISSUE TITLE
Specify dependency search path within an EasyConfig file

### ISSUE THREAD

**Issue by kelseymh** [easybuilders/easybuild-framework#3323]
I recently had a situation where I need to pick up a "hand-written" (script generated) Lmod module file that is included in a group-specific software build.  This file isn't meant to be installed in a sitewide modules area, and we are not wanting our users to have to know or specify the path to this module themselves.

I wrote an EasyBlock file to support creating a "public" EasyBuild Bundle to wrap this special module, along with the infrastructure it needs (toolchain, Python, etc.).  The EasyBlock only implements an overload of `make_module_deps()`:

    def make_module_dep(self, unload_info=None):
        dependencydir = self.cfg['dependencydir']
        if dependecydir:
            txt += self.module_generator.prepend_paths('MODULEPATH', dependencydir, allow_abs=True)

        txt += super(EB_scdms_minus_release, self).make_module_dep()        
        return txt

(the real code has existence checks, and currently only supports a single directory for my particular case).

I wonder if this would be a useful feature to add to `easyblock.py`.  I'm thinking of a new parameter, `moddeppath = '/path/to/dependencies'` or `moddeppath = [ '/one/path', '/two/path' ]`.  These would typically be absolute paths, and get added to `MODULEPATH` as I did above, before the dependencies' `load()` actions were generated.  I'd like to also include a directive in the output module file to strip these paths back out of `MODULEPATH` after the `load()` actions (so the location isn't exposed to end users), but I didn't find a function to do that in `module_generator.py`.

Does this seem like useful functionality for EasyConfigs?  Or is my use case sufficiently obscure that it doesn't need a general solution?

**Comment by boegel** [comment]
@kelseymh I think this is a sensible use case to support.

It hasn't popped up before, as far as I know, but that doesn't mean it's not relevant for others.

And it should be relatively easy to implement support for this without introducing problems elsewhere.

**Comment by kelseymh** [comment]
Okay!  Since I've already got the code in my local EasyBlock, I'll work on porting into `easyblock.py`, and see how well I can do treating all of the various type cases properly.

**Comment by boegel** [comment]
Closed since support for `moddependpaths` easyconfig paramter was implemented in #3324 

Thanks a lot for your efforts on this @kelseymh! :+1:
