### ISSUE TITLE
self.cfg.update() appears to not handle a dictionary value

### ISSUE THREAD

**Issue by kelseymh** [easybuilders/easybuild-framework#3348]
In a custom (project specific) EasyBlock, I am overloading the `make_module_extra()` action to set a large number of required envvars.  To avoid the long, cumbersome lines of "`txt += self.module_generator.set_environment()`" with even longer string constructions as arguments, I thought I could just add to self.cfg['modextravars'] and let the base class take care of it.

In the EB, I wrote:

        batsdir = os.path.join(self.installdir, 'share', self.name)
        batsset = os.path.join(batsdir, 'UserSettings', 'BatRootSettings')
        bats_envvars = {
            'CDMSBATSDIR': batsdir,
            'BATCALIB_RQDATA': os.path.join(batsdir, 'NoiseFiles'),
            'BATCALIB_RRQDATA': os.path.join(batsdir, 'NoiseFiles'),
            'BATNOISE_TEMPLATES': os.path.join(batsdir, 'PulseTemplates'),
            'BATROOT_NOISEFILES': os.path.join(batsdir, 'FilterFiles'),
            'BATROOT_RQDATA': os.path.join(batsdir, 'RQData'),
            'BATROOT_PROC': os.path.join(batsset, 'processing'),
            'BATROOT_CONST': os.path.join(batsset, 'analysis'),
            'BATROOT_CALIB': os.path.join(batsset, 'calibration'),
        }

        self.cfg.update('modextravars', bats_envvars)

Which should have worked (thanks, @boegel !).  Instead, it complained that `bats_envvars` "is not a string or list":

    == 2020-05-26 00:11:36,043 build_log.py:169 ERROR EasyBuild crashed with an erro
    r (at easybuild/base/exceptions.py:124 in __init__): Can't update configuration 
    value for modextravars, because the attempted update value, '{'BATROOT_CALIB': '
    [...]
    msbats/FilterFiles'}', is not a string or list. (at easybuild/framework/easyconf
    ig/easyconfig.py:586 in update)

Since 'modextravars' is supposed to be a dictionary in the EasyConfig file, a dictionary value supplied in `self.cfg.update()` should work.

For the record, I worked around the problem using an assignment:

    self.cfg['modextravars'] = bats_envvars

and produced a module file with all of my needed envvars properly set.

**Comment by boegel** [comment]
I guess we never ran into a case where passing a `dict` value to `self.cfg.update` was needed...

I don't see a reason to not support updating `dict` values through `self.cfg.update`, especially since `self.cfg['modextravars'].update(...)` doesn't work (because `self.cfg['modextravars']` returns a *copy* with templates resolved, not a reference to the actual `modextravars` value, so updating that is futile).

@kelseymh Are you up for taking a stab at this yourself?
See the `def update` in `easybuild/framework/easyconfig/easyconfig.py` (and the accompanying `test_update` in `test/framework/easyconfig.py`).

**Comment by kelseymh** [comment]
Yes, I can take a look at it.  Before even looking at the code, it sounds like the error is being generated by failing an `if isinstance(argument, (string_type, list)):` condition.  It'll probably need an extra block to handle `dict` type.

**Comment by kelseymh** [comment]
This was resolved and merged for the next release.

**Comment by boegel** [comment]
Fixed in #3356, so closing, thanks @kelseymh!
