### ISSUE TITLE
multi_deps = {'Python', ...} appears to set PYTHONPATH incorrectly

### ISSUE THREAD

**Issue by kelseymh** [easybuilders/easybuild-framework#3357]
I have a local EasyConfig, numba-0.37.0-foss-2018b.eb, which I adapted from the official version (partly to learn it, and because I didn't know about the --try options).  The EC uses `multi_deps` to support both Python 2 and Python 3:

    multi_deps = {'Python': ['3.6.6', '2.7.15']}

and

    modextrapaths = {
        'PYTHONPATH': ['lib/python%(pyshortver)s/site-packages'],
    }

But it produces just the one module (of course), and that module sets the wrong PYTHONPATH, using 2.7 unconditionally:

    prepend_path("PYTHONPATH", pathJoin(root, "lib/python2.7/site-packages"))

This causes numba to fail when we run using our preferred Python-3.6.6 environment:
````
[kelsey@terra2 eb]$ numba --help
Traceback (most recent call last):
  File "/scratch/group/mitchcomp/eb/x86_64/sw/numba/0.37.0-foss-2018b/bin/numba"
, line 5, in <module>
    from numba.numba_entry import main
[...]
ImportError: /scratch/group/mitchcomp/eb/x86_64/sw/numba/0.37.0-foss-2018b/lib/p
ython2.7/site-packages/numba/typeconv/_typeconv.so: undefined symbol: PyString_F
romString
````
If I manually reset PYTHONPATH to point to the pyth3.6/site-packages, it works fine.  

I think I understand the issue: with multi_deps, both passes produce the same named .lua file, and the last version in the list wins the battle.  Would it make sense for `multi_deps` to trigger conditional blocks in generating the module so that the specified version creates different actions when one of the multi_deps templates (like `%(pyshortver)s`, here) is in play?

**Comment by akesandgren** [comment]
With multi_deps for python you should NOT add an explicit PYTHONPATH since it uses a different method in that case.

multi_deps will automatically set EBPYTHONPREFIXES which is used to handle this instead.

See the module for SciPy-bundle/2019.03 for instance.

**Comment by akesandgren** [comment]
Look at numba-0.46.0-foss-2019a.eb for example

**Comment by kelseymh** [comment]
Well, that's embarrassing.  numba-0.46.0 is exactly what I used (a couple of months ago) as the template for my own (for context, I needed to backtrack to LLVM 6.0.1).  Of course, in using it I didn't just change the version; I tried to "clean it up" to match the other ECs I had.  Sigh...

...I was going to close this, but removing the PYTHONPATH setting has opened a new problem.  Now the sanity_check (which is identical to what's in numba-0.46.0) is crapping out:
````
sanity_check_commands = ["numba --help"]

== 2020-05-28 13:10:58,271 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): Sanity check failed: sanity check command numba --help exited with code 1 (output: Traceback (most recent call last):
  File "/scratch/group/mitchcomp/eb/x86_64/sw/numba/0.37.0-foss-2018b/bin/numba", line 5, in <module>
    from numba.numba_entry import main
ModuleNotFoundError: No module named 'numba'
)
````
The log also shows that the other two extensions (llvmlite and singledispatch) failed import. 

But I can run the same numba executable myself, at the command line, and the `numba --help` works just fine.

**Comment by kelseymh** [comment]
Closing this issue.  I'm sure now the sanity_check stuff is unrelated.  Removing my setting of PYTHONPATH was successful, as @akesandgren said.
