### ISSUE TITLE
Using hooks (or not) to change directory permissions

### ISSUE THREAD

**Issue by Falkor** [easybuilders/easybuild-framework#3363]
by default, easybuild is using regular permissions under `$EASYBUILD_PREFIX` when creating sub-folders (755) / files (640) for both the software, modules -- the same applies for everything create in the directories listed as `$EASYBUILD_SOURCEPATH`. 
We need to allow group write permissions to all these files/folders (everything is installed in a project directory shared by several users) in an automatic way. 

We saw the option `group-writable-installdir` in the configuration file, but it does not apply to the sourcepaths. Do you see a good way to handle that ?

**Comment by akesandgren** [comment]
I'd say ACL's is the easiest way to handle it.

**Comment by ocaisa** [comment]
There are a few existing options that can potentially help you here:
```
--set-gid-bit       Set group ID bit on newly created directories (default: False)
--sticky-bit        Set sticky bit on newly created directories (default: False)
--umask=UMASK       umask to use (e.g. '022'); non-user write permissions on install directories are removed
```

**Comment by Falkor** [comment]
My bad, I did not pay attention nor knew about those ones, thanks for summarizing them here! 
I'll close the bug, the question for the sources directory seems still open as unless I'm wrong, all the above applies to the installpath only.

**Comment by ocaisa** [comment]
Those options will apply in general...but of course that assumes the directories don't already exist, they won't change the permissions on an existing directory
