### ISSUE TITLE
Ordering bug when making module file in v4.2.x

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-framework#3366]
We ran into problems with a recent install of `impi`, when investigating we discovered that the order of the prepends to `LD_LIBRARY_PATH` has changed between v4.1.2 and v4.2.x:
```
[ocais1@jrl11 ~]$ module load EasyBuild/4.1.2 

The following have been reloaded with a version change:
  1) EasyBuild/4.2.1 => EasyBuild/4.1.2

[ocais1@jrl11 ~]$ eb  impi-2019.7.217-iccifort-2019.5.281-GCC-8.3.0.eb --module-only --force 
== temporary log file in case of crash /tmp/eb-qfskkD/easybuild-YNVdbn.log
== resolving dependencies ...
== processing EasyBuild easyconfig /usr/local/software/jureca/Stages/Devel-2019a/eb_repo/impi/impi-2019.7.217-iccifort-2019.5.281-GCC-8.3.0.eb
== building and installing Compiler/mpi/intel/2019-GCC-8.3.0/IntelMPI/2019.7.217...
== fetching files [skipped]
== creating build dir, resetting environment...
== backup of existing module file stored at /usr/local/software/jureca/Stages/Devel-2019a/modules/all/Compiler/mpi/intel/2019-GCC-8.3.0/IntelMPI/2019.7.217.bak_20200616164837_28214
== unpacking [skipped]
== patching [skipped]
== preparing...
== configuring [skipped]
== building [skipped]
== testing [skipped]
== installing [skipped]
== taking care of extensions [skipped]
== restore after iterating...
== postprocessing [skipped]
== sanity checking [skipped]
== cleaning up [skipped]
== creating module...
== comparing module file with backup /usr/local/software/jureca/Stages/Devel-2019a/modules/all/Compiler/mpi/intel/2019-GCC-8.3.0/IntelMPI/2019.7.217.bak_20200616164837_28214; diff is:
--- /usr/local/software/jureca/Stages/Devel-2019a/modules/all/Compiler/mpi/intel/2019-GCC-8.3.0/IntelMPI/2019.7.217.bak_20200616164837_28214
+++ /usr/local/software/jureca/Stages/Devel-2019a/modules/all/Compiler/mpi/intel/2019-GCC-8.3.0/IntelMPI/2019.7.217.lua
@@ -32,13 +32,13 @@
 
 prepend_path("CPATH", pathJoin(root, "intel64/include"))
 prepend_path("FI_PROVIDER_PATH", pathJoin(root, "intel64/libfabric/lib/prov"))
+prepend_path("LD_LIBRARY_PATH", pathJoin(root, "intel64/lib/release_mt"))
+prepend_path("LD_LIBRARY_PATH", pathJoin(root, "intel64/lib/release"))
 prepend_path("LD_LIBRARY_PATH", pathJoin(root, "intel64/lib"))
-prepend_path("LD_LIBRARY_PATH", pathJoin(root, "intel64/lib/release"))
-prepend_path("LD_LIBRARY_PATH", pathJoin(root, "intel64/lib/release_mt"))
 prepend_path("LD_LIBRARY_PATH", pathJoin(root, "intel64/libfabric/lib"))
+prepend_path("LIBRARY_PATH", pathJoin(root, "intel64/lib/release_mt"))
+prepend_path("LIBRARY_PATH", pathJoin(root, "intel64/lib/release"))
 prepend_path("LIBRARY_PATH", pathJoin(root, "intel64/lib"))
-prepend_path("LIBRARY_PATH", pathJoin(root, "intel64/lib/release"))
-prepend_path("LIBRARY_PATH", pathJoin(root, "intel64/lib/release_mt"))
 prepend_path("LIBRARY_PATH", pathJoin(root, "intel64/libfabric/lib"))
 prepend_path("MANPATH", pathJoin(root, "man"))
 prepend_path("PATH", pathJoin(root, "intel64/bin"))
@@ -59,7 +59,7 @@
 set_alias("mpiicc", "mpiicc -cc=icc")
 set_alias("mpiicpc", "mpiicpc -cxx=icpc")
 set_alias("mpiifort", "mpiifort -f90=ifort")
--- Built with EasyBuild version 4.2.1
+-- Built with EasyBuild version 4.1.2

```

**Comment by ocaisa** [comment]
I *think* this may be a result of https://github.com/easybuilders/easybuild-framework/pull/3176/files#diff-a1bcbbc1aab6b59688b219f298fddb56R1328 , it's definitely something like that where sorting was introduced without taking into account that the order may actually matter.

**Comment by ocaisa** [comment]
Nope, tested that and that wasn't it.

**Comment by ocaisa** [comment]
Ok, I found it, there are a couple of agressive sortings going on that were introduced in that PR. I'll make a PR to revert them.

**Comment by lexming** [comment]
The precedence of `release_mt` over `release` was introduce by commit https://github.com/easybuilders/easybuild-easyblocks/commit/de4aa4cd7a9b2cbaf98535c3c7cbd0b393b11614 in the easyblock of `impi`

This change was introduced in release v3.8.0. I guess that you are seeing this now because `impi` v2019 has not been part of a toolchain since last release.

**Comment by lexming** [comment]
According to the [Developers Guide for Intel MPI v2019](https://software.intel.com/content/www/us/en/develop/download/intel-mpi-library-for-linux-os-developer-guide-2019-update-1.html), `release` is the default with this version. Moreover, `release` is also a multi-threaded library as it is `release_mt`, they differ in how the multi-threading works. So I would fix the `impi` easyblock to follow the default behaviour.

**Comment by ocaisa** [comment]
> The precedence of `release_mt` over `release` was introduced by commit [easybuilders/easybuild-easyblocks@de4aa4c](https://github.com/easybuilders/easybuild-easyblocks/commit/de4aa4cd7a9b2cbaf98535c3c7cbd0b393b11614) (line 200) in the easyblock of `impi`

The ordering is the reverse of what you think here, it prepends `release_mt` then `release` then `lib`, so `lib` has highest precedence (that PR was exactly to address the change in `v2019`).

**Comment by lexming** [comment]
I think that this is not how it is intended to work. My understanding is that the order of the list in the easyblock directly reflects the order of precedence (first item goes in first position). The [comment in the easyblock of `impi`](https://github.com/easybuilders/easybuild-easyblocks/blob/50534e60198b4bebd06e07e1d37da4710bddcc26/easybuild/easyblocks/i/impi.py#L262) does state this intent as well, `release_mt` is meant to be in front in its current state and `lib` goes last
```
# Keep release_mt and release in front, to give them priority over the possible symlinks in intel64/lib.
                # IntelMPI 2019 changed the default library to be the non-mt version.
                lib_dirs = ['intel64/%s' % x for x in ['lib/release_mt', 'lib/release', 'lib']]
```
Therefore, the list ` ['lib/release_mt', 'lib/release', 'lib']` is currently correctly translated into the module (at least regarding the order set in the easyblock)
```
prepend_path("LD_LIBRARY_PATH", pathJoin(root, "intel64/lib"))
prepend_path("LD_LIBRARY_PATH", pathJoin(root, "intel64/lib/release"))
prepend_path("LD_LIBRARY_PATH", pathJoin(root, "intel64/lib/release_mt"))
```

**Comment by ocaisa** [comment]
Looks like that comment was updated from what was there originally:
https://github.com/easybuilders/easybuild-easyblocks/commit/0874dafb46550cbedc854d2f92d26422ac206121
The original comment matches what the code actually does.

**Comment by ocaisa** [comment]
I've reverted that commit and added a clarification in https://github.com/easybuilders/easybuild-easyblocks/pull/2080

**Comment by lexming** [comment]
@ocaisa The current comment is correct, at least regarding the goal of the list in `lib_dirs`, `release` or `release_mt` should precede `lib`. That's what Intel does.

Please check the script `$EBROOTIMPI/intel64/bin/mpivars.sh` in the installation of Intel MPI. This scripts is used to switch from the different release libraries. In line 128, you can see that the path to `release` or `relase_mt` precedes `lib`. Therefore, if our code is doing anything else, that is wrong.
