### ISSUE TITLE
reprod dir doesn't get copy of easyblock used for extensions

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-framework#3373]
The tensorflow.py is missing from the reprod dir of a recent install of TensorFlow

**Comment by ocaisa** [comment]
Pretty sure this means that we don't handle extensions (and probably bundles) at all there...

**Comment by boegel** [comment]
@ocaisa That should not be too difficult to fix, I think?

Is this something you could perhaps take a look at?

**Comment by ocaisa** [comment]
I don't think this is so easy. The reproducability stuff is done right at the end, not progressively. We would need something in the esayblock class that keeps track of the easyblocks used by extensions/bundles...does that exist?

**Comment by boegel** [comment]
@ocaisa `self.ext_instances` holds all the instances for the extensions that were installed, you can figure out which easyblocks were used through there?
