### ISSUE TITLE
Reprod folder does not contain specialized Bundle EasyBlocks

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-framework#3395]
I just checked the folder for TensorFlow and the easybuild/reprod/easyblocks folder only contains `bundle.py` and `pythonbundle.py` but not `tensorflow.py`

I guess that reprod algorithm ignores sub-easyblocks. This should be fixed

**Comment by ocaisa** [comment]
What version of eb are you running? This should have been fixed in https://github.com/easybuilders/easybuild-framework/pull/3375 which was solving the same problem that you describe (#3373)

**Comment by Flamefire** [comment]
I was running 3.2.1 so yes might be fixed by that. Rerunning to double check, thanks!

**Comment by Flamefire** [comment]
Confirmed to work with 3.2.2
