### ISSUE TITLE
installing M4-1.4.18.eb with --rpath fails if x86_64-pc-linux-gnu-gcc command is available

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#3398]
The RPATH sanity check fails because there is no `(RPATH)` section found in the output of `readelf -d`.

It seems that Autotools prefers using `x86_64-pc-linux-gnu-gcc` as compiler command when it is around (which it is in a Gentoo Prefix environment), and EasyBuild currently doesn't install a wrapper for this (only for `gcc`, `g++`, etc.).

This is probably only an issue when the system compiler is used, since in that case EasyBuild doesn't define `$CC`, `$CXX` and co. When `$CC` is set to `gcc`, the M4 build system uses `gcc` as expected, and then the issue does not occur (since there's an RPATH wrapper installed for `gcc`).

Two possible solutions:

* install wrappers for additional compiler commands when using the system compiler (`cc`, `x86_64-pc-linux-gnu-gcc`, and who knows what else)
* define `$CC`, `$CXX` & co to try and ensure the compiler wrappers are picked up

I'm in favor of the latter approach, since that's likely to be easier in the long run.

**Comment by lexming** [comment]
I agree with the second solution. It is possible to have multiple GCC versions installed at the same time in gentoo and there might be multiple  binaries with names such as `x86_64-pc-linux-gnu-gcc` or several variations of that. However, at any time there is only one active installation that is controlled with `gcc-config`. So we should stick to the standard commands (eg `gcc`), which are just symlinks to the active GCC installation, to be sure that we are using the correct system compiler.
