### ISSUE TITLE
bootstrap_eb.py not working on ubuntu 20.04

### ISSUE THREAD

**Issue by farzad685** [easybuilders/easybuild-framework#3457]
I am trying to install easy build on ubuntu 20.04 from https://easybuild.readthedocs.io/en/latest/Installation.html.
but when I type this >>python3 bootstrap_eb.py $EASYBUILD_PREFIX 
I receive error :+1: 
[[INFO]] EasyBuild bootstrap script (version 20200820.01, MD5: 13fd198a1baa9a165e8e0c983805f894)
[[INFO]] Found Python 3.8.2 (default, Jul 16 2020, 14:00:26) ; [GCC 9.3.0]

[[INFO]] Installation prefix /home/farzad/.local/easybuild
[[INFO]] Using modules tool specified by $EASYBUILD_MODULES_TOOL: Modules
[[INFO]] No suitable setuptools installation found, proceeding with stage 0...

[[INFO]] +++ STAGE 0: installing distribute via included (patched) distribute_setup.py...

Traceback (most recent call last):
  File "bootstrap_eb.py", line 1158, in <module>
    main()
  File "bootstrap_eb.py", line 943, in main
    distribute_egg_dir = stage0(tmpdir)
  File "bootstrap_eb.py", line 429, in stage0
    txt = re.sub(r'([^\n]*)(return subprocess.call\(args)(\) == 0)',
  File "/usr/lib/python3.8/re.py", line 208, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by boegel** [comment]
@farzad685 That's a bug in stage 0 of the bootstrap, but what stage 0 is trying to do (install an old version of `setuptools`) is likely not going to work out well anyway, especially with a recent Python version like 3.8.

A couple of things you can try:

* Make sure a recent version of `setuptools` is installed for Python 3.8 on your system

* Just install EasyBuild with `pip3 install easybuild` (and if you really want an environment module file for EasyBuild, run `eb --install-latest-eb-release` afterwards).

Do let us know if this helps you!

**Comment by farzad685** [comment]
> @farzad685 That's a bug in stage 0 of the bootstrap, but what stage 0 is trying to do (install an old version of `setuptools`) is likely not going to work out well anyway, especially with a recent Python version like 3.8.
> 
> A couple of things you can try:
> 
> * Make sure a recent version of `setuptools` is installed for Python 3.8 on your system
> * Just install EasyBuild with `pip3 install easybuild` (and if you really want an environment module file for EasyBuild, run `eb --install-latest-eb-release` afterwards).
> 
> Do let us know if this helps you!

**Comment by farzad685** [comment]
> > @farzad685 That's a bug in stage 0 of the bootstrap, but what stage 0 is trying to do (install an old version of `setuptools`) is likely not going to work out well anyway, especially with a recent Python version like 3.8.
> > A couple of things you can try:
> > 
> > * Make sure a recent version of `setuptools` is installed for Python 3.8 on your system
> > * Just install EasyBuild with `pip3 install easybuild` (and if you really want an environment module file for EasyBuild, run `eb --install-latest-eb-release` afterwards).
> > 
> > Do let us know if this helps you!

**Comment by farzad685** [comment]
@boegel .thanks a lot `pip3 install easybuild` did work.

**Comment by farzad685** [comment]
@boegel .and `eb --install-latest-eb-release` does not work.
eb: command not found

**Comment by farzad685** [comment]
> I am trying to install easy build on ubuntu 20.04 from https://easybuild.readthedocs.io/en/latest/Installation.html.
> but when I type this >>python3 bootstrap_eb.py $EASYBUILD_PREFIX
> I receive error 
> [[INFO]] EasyBuild bootstrap script (version 20200820.01, MD5: 13fd198a1baa9a165e8e0c983805f894)
> [[INFO]] Found Python 3.8.2 (default, Jul 16 2020, 14:00:26) ; [GCC 9.3.0]
> 
> [[INFO]] Installation prefix /home/farzad/.local/easybuild
> [[INFO]] Using modules tool specified by $EASYBUILD_MODULES_TOOL: Modules
> [[INFO]] No suitable setuptools installation found, proceeding with stage 0...
> 
> [[INFO]] +++ STAGE 0: installing distribute via included (patched) distribute_setup.py...
> 
> Traceback (most recent call last):
> File "bootstrap_eb.py", line 1158, in
> main()
> File "bootstrap_eb.py", line 943, in main
> distribute_egg_dir = stage0(tmpdir)
> File "bootstrap_eb.py", line 429, in stage0
> txt = re.sub(r'([^\n]*)(return subprocess.call(args)() == 0)',
> File "/usr/lib/python3.8/re.py", line 208, in sub
> return _compile(pattern, flags).sub(repl, string, count)
> TypeError: cannot use a string pattern on a bytes-like object

**Comment by farzad685** [comment]
> @boegel .thanks a lot `pip3 install easybuild` did work.
> but `module use $EASYBUILD_PREFIX/modules/all` does not work .

**Comment by farzad685** [comment]
> @boegel .and `eb --install-latest-eb-release` does not work.
> eb: command not found

**Comment by boegel** [comment]
@farzad685 You may need to update your `$PATH` variable after installing EasyBuild via `pip3` to make the `eb` command available.
`module load EasyBuild` will only works after you have installed EasyBuild with `eb` (for example via `eb --install-latest-eb-release`) and updating your `$MODULEPATH` (to the location where the `EasyBuild` module was installed).

Maybe this is helpful: https://easybuilders.github.io/easybuild-tutorial/installation/
