### ISSUE TITLE
Allow to skip tests from commandline

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-framework#3523]
Currently the EC may execute 2 different tests (besides the sanity check): test_step and test_cases_step.
The former is likely something like `make test` while the latter is something custom run after the (full) module is build and installed.

For some ECs (e.g. TensorFlow and PyTorch) running the test_step takes VERY long, i.e. multiple hours. So for some situations it might be good to (easily) skip that. Example: Testing a new version where some tests fail is easier by installing that without the tests and then work with the loaded module and debug the tests interactively. Rebuilding already takes 1-2h so doing that every time is not feasible. Another use case is to quickly install a module which is assumed to be good.

Currently we have `--skip-test-cases` but that only skips the test_cases_step not the test_step.

I propose a new `--skip-tests` switch which skips the test_step.

As a related enhancement I propose to always print the step(s) and simply add the "[SKIPPED]" marker to it, similar to what is done when `--module-only` is used. Currently when using `--skip-test-cases` the test_cases_step is not even added as a step and hence is missing from the stdout. I find it however useful to explicitly see, that the test is skipped. The current condition is `not build_option('skip_test_cases') and app.cfg['tests']` so I'd agree that when `app.cfg['tests']` is not set, the step is not added so there is a difference between an existing step, that is skipped and non-existing test_cases_step (i.e. empty/unset `tests`)

**Comment by boegel** [comment]
Fixed in #3524 by adding support for `--skip-test-step`
