### ISSUE TITLE
Symbolic link lib64 to lib should be a relative link

### ISSUE THREAD

**Issue by mboisson** [easybuilders/easybuild-framework#3564]
This is a comment from 
https://github.com/easybuilders/easybuild-framework/pull/3401

The symlink created for lib64 is a symlink to the absolute path. It should be a symlink with the relative path.

**Comment by mboisson** [comment]
In the event when someone rsync the installdir onto a different filesystem and attempts to change permissions/group, rsync will try to change permission/groups through the symlink, which points to the absolute path on the old filesystem.

**Comment by bartoldeman** [comment]
We had this particular case:
`/stratum0/cvmfs/restricted.computecanada.ca/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/maker/3.01.03/lib64 ->`
`/cvmfs/restricted.computecanada.ca/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/maker/3.01.03/lib`
when we rsync from `/cvmfs` to `/stratum0/cvmfs`

**Comment by Flamefire** [comment]
FYI: Your issue for moving stuff might also occur with the default version files `.version` and maybe others
