### ISSUE TITLE
Github hooks should check against develop branch

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-framework#3590]
Since `master` will be switched to `main`, it breaks --check-github.

Using the `develop` branch for these checks is the obvious fix; since that's a branch that all the people using github integration needs to have on their cloned repos as well.

There are numerous mentions of "master" in links, and branch names here as well, which should all use develop instead.
https://github.com/easybuilders/easybuild-framework/blob/develop/easybuild/tools/github.py

**Comment by boegel** [comment]
I've temporarily restored the `master` branch in the easyconfigs repo to avoid breakage for existing EasyBuild versions.

From EasyBuild v4.3.3 onwards, EasyBuild will use the `main` branch instead, so going forward things will work as expected.

Changing to `develop` makes sense, but it won't help with not breaking existing EasyBuild releases that still use `master`, the only way to avoid that is to keep `master` around for a while in the easyconfigs repo (but it can go stale, that doesn't matter).

**Comment by boegel** [comment]
It doesn't actually matter whether or not we keep the `master` branch around in the central `easybuild-easyconfigs` repo, what matters is the `main` branch being there in your own fork for EasyBuild v4.3.3 & newer...
