### ISSUE TITLE
eb --new-pr without github username should return clearer message

### ISSUE THREAD

**Issue by robert-mijakovic** [easybuilders/easybuild-framework#3615]
I had an issue where eb --new-pr was used without github username and it returned the following message:

ERROR: Failed to push branch '20210317112849_new_pr_AOCC300' to GitHub (git@github.com:None/easybuild-easyconfigs.git): Cmd('git') failed due to: exit code(128)
  cmdline: git push --porcelain github_None_qnHqP 20210317112849_new_pr_AOCC300
  stderr: 'fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.'

As you can see None was set instead of the username and the message is quite cryptic.
I think it should be handled that when None is set and exit code from git is 128 it should print that github username is not set.

**Comment by migueldiascosta** [comment]
fixed in https://github.com/easybuilders/easybuild-framework/pull/3644 (and https://github.com/easybuilders/easybuild-framework/pull/3681 addresses a similar problem in `--check-github`)
