### ISSUE TITLE
Recursive module unload with limited depth for Cray toolchains

### ISSUE THREAD

**Issue by lucamar** [easybuilders/easybuild-framework#3627]
I report here as a placeholder for further discussion a request to implement a limited depth recursive module unload when using the Cray toolchains: the relevant framework scripts are `easyblocks/generic/craytoolchain.py` and `tools/module_generator.py`.
The Cray toolchains load Cray external modules as dependencies that should not be unloaded, in order to keep a working programming environment. 
When you build a modulefile using a Cray toolchain with the recursive module unload feature enabled, the full list of dependencies is unrolled, therefore also the Cray external modules (dependencies of the Cray toolchain) are unloaded with the module. 
It would be preferable to stop the unloading at the depth of the Cray toolchain module, if possible.

**Comment by boegel** [comment]
@lucamar Thanks to the changes in #3689 (which will be included in the upcoming EasyBuild v4.4.0 release), you can now selectively opt-out of recursive module unloading in specific easyconfig files using `recursive_module_unload = False`, so you can use this in the easyconfig files for the Cray toolchains to avoid that the (external) modules for the toolchain components are unloaded.
