### ISSUE TITLE
`easy_install` method used in bootstrap script is deprecated

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-framework#3676]
In #3675 I had to remove Python 3.8 and 3.9 to get CI to pass. For Python >3.4 we should switch the bootstrap script to just use `pip3` for stage 1.

**Comment by boegel** [comment]
Deprecating the bootstrap script as a whole is probably a better way forward...

It served it's purpose when installing EasyBuild with `pip` was problematic, but that's long past us now...

We should update the documentation first though, that still recommend the bootstrap script.

**Comment by boegel** [comment]
Bootstrap script was deprecated in #3742, not planning to spend more time on it...
