### ISSUE TITLE
surprising behavior with patch files that don't have .patch extension

### ISSUE THREAD

**Issue by smoors** [easybuilders/easybuild-framework#3688]
patches hat don't have .patch extension work the same as patches, unless a custom path is provided, eg.

`('patch_without_extension', 'custom/path')`

in that case the patch file is considered a normal file and is just copied to the custom path.

to avoid surprises for users who are unaware of this, it would be better to do one of the following options:
1. never apply the patch if it does not contain the .patch suffix.

2. always apply the patch, unless explicitly specified that it should only be copied, eg. with an extra list/tuple item:
    `('patch_without_extension', 'custom/path', 'copy-only')`.
    this would require updating easyconfigs that do an implicit copy.

3. raise error if it does not contain the .patch suffix and no destination path is given.
    this may break some easyconfigs that are not in the EB repo (although this is unlikely, and it's easily fixed)
    
I think option 3 is the best way to avoid surprises, . note also that the documentation specifically mentions that paches should have .patch extension: https://caylo-easybuild.readthedocs.io/en/latest/Writing_easyconfig_files.html#source-files-and-patches

**Comment by boegel** [comment]
I think the right way forward here is to print a clear deprecation warning whenever an actual patch file is specified that doesn't have a `.patch` extension, and then hard break that in the upcoming EasyBuild 5.0.

**Comment by smoors** [comment]
I agree, just need to find time to implement it...
