### ISSUE TITLE
small glitches when uploading test reports from multiple prs

### ISSUE THREAD

**Issue by migueldiascosta** [easybuilders/easybuild-framework#3739]
- `cpu_arch_name` appears multiple times (e.g. https://github.com/easybuilders/easybuild-easyconfigs/pull/13073#issuecomment-860328137), easily fixed with e.g. `system_info = init_session_state['system_info'].copy()` 
- multiple identical gists are created (e.g. https://gist.github.com/migueldiascosta/fd67541a584bffa8ff3302d8455683b3, https://gist.github.com/migueldiascosta/c4870fa03ef7a0c3241b16e0b2ab0ec8), not a big deal?
- output of easybuild ("Test report uploaded to `gist_url` and mentioned in a comment in easybuild-easyconfigs PR# `pr_nr`") only mentions the last gist and PR, since `txt` is overwritten for each `pr_nr`

**Comment by boegel** [comment]
I think it would be nice to only have a single gist created, it's a bit "wasteful" otherwise?
