### ISSUE TITLE
Exclude EasyConfigs from --from-pr builds

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-framework#3774]
It would be great to exclude particular easyconfigs when doing `--from-pr`, e.g. all belonging to Intel/2017 for which we don't have a license.

Using only specified ECs is possible, but cumbersome when you want to build 16 and exclude 2 from 18 total.

So maybe: `--include-ec-regex` and `--exclude-ec-regex`?

**Comment by boegel** [comment]
@Flamefire This can be closed, thanks to the support for `--filter-ecs` which was implemented in #3796 ?

**Comment by Flamefire** [comment]
Yes
