### ISSUE TITLE
easybuild installation of julia 1.6.1-linux-x86_64 generating error when starting.

### ISSUE THREAD

**Issue by vraj004** [easybuilders/easybuild-framework#3804]
I installed Julia 1.6.1 using easybuild 4.4.1 successfully. I load julia module, start julia and get this error: 

ERROR: Unable to load dependent library /home/common/easybuild/software/Julia/1.6.1-linux-x86_64/bin/../lib/julia/libjulia-internal.so.1
Message:/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/common/easybuild/software/Julia/1.6.1-linux-x86_64/bin/../lib/julia/libjulia-internal.so.1)

However, also loading another module like GCCcore/6.4.1 or Emacs resolves this problem. Adding LD_LIBRARY_PATH="" before calling julia also helps as shown here: https://discourse.julialang.org/t/unable-to-launch-julia-1-6-ssl-and-glibc-issues/60488/5

Can this issue be resolved in the Julia package in easybuild, perhaps in the toolchain settings?

```
eb --show-config
#
# Current EasyBuild configuration
# (C: command line argument, D: default value, E: environment variable, F: configuration file)
#
buildpath      (E) = /home/common/easybuild/build
containerpath  (E) = /home/common/easybuild/containers
installpath    (E) = /home/common/easybuild/
packagepath    (E) = /home/common/easybuild/packages
prefix         (E) = /home/common/easybuild/
repositorypath (E) = /home/common/easybuild/ebfiles_repo
robot-paths    (D) = /home/common/easybuild/software/EasyBuild/4.4.1/easybuild/easyconfigs
sourcepath     (E) = /home/common/easybuild/sources
huia ~ []$ julia
```

**Comment by boegel** [comment]
@vraj004 Currently we only provide support in EasyBuild for installing pre-built binaries of Julia (as opposed to building Julia from source ourselves).

It seems like the C++ runtime library provided by the operating system you're using is too old, the pre-built Julia binaries require a more recent version.

There's nothing much that can be done about this on the EasyBuild side, except for properly installing Julia from source.
We've looked into this (see https://github.com/easybuilders/easybuild-easyconfigs/pull/11522), but more work is needed on this.
