### ISSUE TITLE
Report available GPUs and NVIDIA driver version in PR test reports

### ISSUE THREAD

**Issue by branfosj** [easybuilders/easybuild-framework#3825]
When looking at test reports it would be useful to know what GPUs were available during the build and what NVIDIA driver version is installed.

This would (probably) only be needed when testing software with a CUDA dependency.

Also, the equivalent for non-NVIDIA GPUs.

**Comment by SebastianAchilles** [comment]
I like this idea. I would like to also add the GPU and NVIDIA driver version information to `eb --show-system-info`.

I think as a start for the NVIDIA GPUs we could use the properties `gpu_name` and `driver_version`:
```
$ nvidia-smi --query-gpu=gpu_name,driver_version --format=csv
name, driver_version
A100-SXM4-40GB, 460.32.03
A100-SXM4-40GB, 460.32.03
A100-SXM4-40GB, 460.32.03
A100-SXM4-40GB, 460.32.03
```

A test report with GPU information could then look maybe like this:

```
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jrc0437 - Linux centos linux 8.3.2011, x86_64, AMD EPYC 7742 64-Core Processor (zen2), 4x A100-SXM4-40GB (Driver Version: 460.32.03), Python 3.6.8
See ... for a full test report.
```

**Comment by ocaisa** [comment]
Is there any need to restrict it to when you are using a CUDA dep? If the command is available, query it, if you get a non-zero exit code then reporting that is not going to do any harm.

**Comment by branfosj** [comment]
> Is there any need to restrict it to when you are using a CUDA dep? If the command is available, query it, if you get a non-zero exit code then reporting that is not going to do any harm.

Probably not. And it might be helpful when debugging failed builds to know there was a GPU there and the software decided to build for it even on a CPU-only toolchain.
