### ISSUE TITLE
finding easyconfigs fails

### ISSUE THREAD

**Issue by kelbstf** [easybuilders/easybuild-framework#3837]
Hello,

my EasyBuild installations seem to have issues with finding ec files.

The following fails:
````console
eb --show-ec M4
== 2021-09-15 13:07:29,646 build_log.py:169 
ERROR EasyBuild crashed with an error 
(at easybuild/4.4.2/lib/python3.6/site-packages/easybuild/base/exceptions.py:124 in __init__): 
One or more files not found: M4 
(search paths: /opt/ohpc/ebmaint/easybuild/4.4.2/easybuild/easyconfigs, \
/opt/ohpc/pub/libs/easybuild/4.3.4/software/EasyBuild/4.3.4/easybuild/easyconfigs) \
(at easybuild/4.4.2/lib/python3.6/site-packages/easybuild/tools/filetools.py:1002 in locate_files)
````

But when specifying a particular package, the same succeeds:
````console
eb --show-ec M4-1.4.16.eb
````

Tested on 
- EasyBuild 4.4.2 installed via pip and 
- EasyBuild 4.3.4, installed via rpm (OHPC)

Packages are indeed under: 
````console
/opt/ohpc/pub/libs/easybuild/4.3.4/software/EasyBuild/4.3.4/easybuild/easyconfigs/m/M4/
`````
The pathes seem to be o.k.:

````console
eb --show-config
#
# Current EasyBuild configuration
# (C: command line argument, D: default value, E: environment variable, F: configuration file)
#
buildpath      (D) = /home/nonadmin/.local/easybuild/build
containerpath  (D) = /home/nonadmin/.local/easybuild/containers
installpath    (D) = /home/nonadmin/.local/easybuild
repositorypath (D) = /home/nonadmin/.local/easybuild/ebfiles_repo
robot-paths    (D) = /opt/ohpc/pub/libs/easybuild/4.3.4/software/EasyBuild/4.3.4/easybuild/easyconfigs
sourcepath     (D) = /home/nonadmin/.local/easybuild/sources
````
Also in relation to PYTHONPATH:
````console
$PYTHONPATH: /opt/ohpc/pub/libs/easybuild/4.3.4/software/EasyBuild/4.3.4/lib/python3.6/site-packages
`````
I followed  "[automatically finding path of installed easyconfigs package fails when installed using pip #412]([](https://github.com/easybuilders/easybuild-framework/issues/412))", but problems discussed there seem to be unrelated?

Does this indicate that s.th. fundamental with my path scheme is unhealthy?

Any ideas very welcome!

**Comment by ocaisa** [comment]
`--show-ec` is used to echo the contents of an easyconfig file. When you only specify `M4` this is not enough information for EasyBuild to resolve this to a particular file in your search path.

It sounds to me that you want to use `eb --search M4` to search for all easyconfig filenamess that contain `M4` (or `eb --search ^M4` to find all files that start with `M4`). You can then take any of these filenames and input them into `eb --show-config <>`.

**Comment by kelbstf** [comment]
Hello @ocaisa,
thank you very much for your superquick answer and help.
Terrific, that works for me as well. 
I just was concerned, because it responds with an "Error", and it looked similar to (old) issues, which indicated setup/configuration shortcomings...
I'll adapt my methods accordingly ;-)
Thank you again!

**Comment by kelbstf** [comment]
Solved. Thank you again!
