### ISSUE TITLE
Pushing easyconfigs to local git repo fails in 4.5.0

### ISSUE THREAD

**Issue by i-mtz** [easybuilders/easybuild-framework#3892]
After we upgraded our EasyBuild installation to `4.5.0` we have noticed that the feature we use to send the easyconfigs and build logs to an internal git repo is no longer working. We have an ssh-key for our build user that works if we do a build with a previous EasyBuild version (`4.4.2` for example) but no longer works on `4.5.0`. At the end of the build we get:
```
/scicore/home/scicore/easybuil@bc2-gl.bc2.unibas.ch's password:
```
There seems to be some change in the way the `repositorypath` configuration option is processed, which in our config is:
```
repositorypath=git@bc2-gl.bc2.unibas.ch:easybuild/installed_easyconfigs_tests.git
```

@pescobar mentioned that this commit might be related https://github.com/easybuilders/easybuild-framework/commit/3252979f29b1b92a7223f5163cef02c7c03fa564

**Comment by boegel** [comment]
@i-mtz It looks like we're not taking into account that the `repositorypath` value may be something totally different than a simple path value...

Can you share the output of `eb --show-config` with both EasyBuild 4.4.2 and 4.5.0?

**Comment by boegel** [comment]
@i-mtz @pescobar The changes made in #3893 should fix the problem you're seeing, can you confirm?

**Comment by i-mtz** [comment]
@boegel, yes,  #3893 fixes the issue for us.
Thanks!

**Comment by Micket** [comment]
Another user mentioned issues and was using
`ssh://git@x.x.x.edu:2222/xxx/easybuild/slurm-cluster/deployed-recipes.git`
And, surely, some might be using local git repos with other usernames. I don't think `path.startswith('git@')` is good enough here.

**Comment by Micket** [comment]
One option would be to check with regexp if we have to modify that function without https://stackoverflow.com/questions/2514859/regular-expression-for-git-repository seems very robust.

**Comment by boegel** [comment]
How about just checking with `[a-z][@:]` for URL-like paths? That'll probably work just fine in practice?

**Comment by Micket** [comment]
Sure

**Comment by Micket** [comment]
Though, technically, can't you have a .ssh/config that specifies the username for you? So it's not a guarantee.

**Comment by boegel** [comment]
An alternative could perhaps be to check if the value corresponding with an existing absolute path, and if it doesn't, then don't try to "cast" it to an absolute path at all?

**Comment by akesandgren** [comment]
Isn't the problem the code in _postprocess_config (tools/options.py) where is does

**Comment by boegel** [comment]
> that it should only do that if self.options.repository is FileRepository ? And absolutely not if it is GitRepository ?

No, because `GitRepository` can also be local (so specified as a path), doesn't have to be remote (specified as a URL of some kind)

**Comment by boegel** [comment]
Another way out could be to simply skip the whole make-sure-it-is-an-absolute-path business for `repositorypath`, since it's quite unlikely that a relative path is specified there anyway?

The changes made in #3832 were mainly to prevent silly mistakes like in #3619, but for `repositorypath` it's probably much less likely that it's a problem...
