### ISSUE TITLE
add support for optional comment parameter for extensions

### ISSUE THREAD

**Issue by smoors** [easybuilders/easybuild-framework#3946]
right now when we update the checksums of an easyconfig with `eb --inject-checksums`, all comments are removed, due to the way the extensions dictionary is parsed.

unless there's an easy way to fix this, I propose a workaround, where the comments are added to the dictionary itself, for example with an optional `comment` string (or perhaps a list of strings):
```
exts_list = [
    ('wheel', '0.36.2', {
        'checksums': ['e11eefd162658ea59a60a0f6c7d493a7190ea4b9a85e335b33489d9f17e0245e'],
        'comment': "this wheel is an essential extension", 
    }),
```

**Comment by boegel** [comment]
I don't think this is the right way forward... The comments being stripped out when using `eb --inject-checksums` is a bug, we are keeping the comments in other places, so we should keep them here too.

Adding a feature to work around a bug seems like to wrong way forward to me...

**Comment by smoors** [comment]
fair enough
