### ISSUE TITLE
drop into shell with full environment in case of failure

### ISSUE THREAD

**Issue by surak** [easybuilders/easybuild-framework#3950]
This is an issue regarding the discussion on 19.01.2022

**Comment by boegel** [comment]
We're looking into implementing support for this in EasyBuild 5.0, along with the implementation of the new `run` function (see #4252).

@Micket mentioned he has looked into this a bit already, but it would be good to get #4284 merged first to start working on the actual implementation (which probably involves leveraging [`pty.spawn`](https://docs.python.org/3/library/pty.html))

**Comment by boegel** [comment]
Starting an interactive shell for a failing shell command will be supported in EasyBuild 5.0, see #4486, so closing this...
