### ISSUE TITLE
stop relying on distutils (will no longer be available in Python 3.12)

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#3963]
`distutils` is deprecated since Python 3.10, will be removed in Python 3.12; see https://www.python.org/dev/peps/pep-0632

Places we rely on `distutils` currently:

* `from distutils.version import LooseVersion` (framework + easyblocks)
  * we need a replacement to do software version comparison
  * attempt was made in #3794, ~but that has bitrotted a bit~ looks promising...
  * can/should we come up with a better solution than just copy-pasting `LooseVersion` from Python stdlib into EasyBuild?
  * maybe infix operators like `|before|` (see also http://tomerfiliba.com/blog/Infix-Operators/)?
* `from distutils.version import StrictVersion` in `easybuild/tools/modules.py` + tests
* in `setup.py`, to avoid depending on `setuptools`
  * it looks like `setuptools` will be a necesary evil (see also #2836)
* `from distutils.util import strtobool` in `easybuild/framework/easyconfig/types.py`

**Comment by boegel** [comment]
All done, see #4484

**Comment by haampie** [comment]
@boegel can you reopen? there are still distutils remnants

https://github.com/easybuilders/easybuild-framework/blob/d700144108b3a5508659a4d957c7594d35033e62/setup.py#L35-L36

having setuptools installed does not mean that distutils can be imported.

See https://github.com/cython/cython/pull/5754#issuecomment-1752102480

**Comment by boegel** [comment]
Let's follow up in #4478, I've re-opened that, maybe we overlooked something indeed...

@haampie Thanks for raising this!

**Comment by boegel** [comment]
fixed with #4478
