### ISSUE TITLE
allow --copy-ec for installed modules without requiring --rebuild

### ISSUE THREAD

**Issue by jfgrimm** [easybuilders/easybuild-framework#3992]
Currently, trying to use `--copy-ec` when the module already exists gives the message:
```
== category/software/version is already installed (module found), skipping
== No easyconfigs left to be built.
```
since nothing is being (re)built when `--copy-ec` is passed, it seems unnecessary to require `--rebuild`

**Comment by branfosj** [comment]
fixed in #3993
