### ISSUE TITLE
Time to switch to `icx/icpx` for Intel C/C++ compilers

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-framework#4009]
The current recommendation from Intel is that we should be using the `icx/icpx` LLVM-based compilers by default

**Comment by ocaisa** [comment]
I _think_ this would mean adding a version check to https://github.com/easybuilders/easybuild-framework/blob/develop/easybuild/toolchains/compiler/intel_compilers.py#L59 and overriding the values `self.variables['CXX']`/` self.variables['CC']` (that's assuming none of the compiler arguments have changed)

**Comment by ocaisa** [comment]
Looking at https://www.intel.com/content/www/us/en/developer/articles/guide/porting-guide-for-icc-users-to-dpcpp-or-icx.html 
```
- ICX drivers icx and icpx will accept ICC Classic Compiler options or Clang*/LLVM Compiler options.
  - Clang*/LLVM Compiler options are interpreted directly.
  - Classic ICC Compiler options passed to ICX are translated to their Clang*/LLVM equivalents, wherever possible.
- Not all ICC Classic options are accepted and/or implemented in ICX.
```
We would also need to use `-fiopenmp` for OpenMP (according to that page).

I wonder if we will also end up with version differences compared to `ifort`?

**Comment by akesandgren** [comment]
Should we do this for the 2022a toolchain version?

**Comment by ocaisa** [comment]
Since #4031 includes (initial) support for these has been merged I think we can close this
