### ISSUE TITLE
--show-system-info fails on Apple Silicon M1

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#4013]
Different system queries via `sysctl` are broken on Apple Silicon.

Known issues:

* "`sysctl -n hw.cpufrequency_max`" returns empty result, used in `get_cpu_speed`
  * see also https://github.com/sebhildebrandt/systeminformation/issues/564)
* `machdep.cpu.vendor` (used in `get_cpu_vendor`) and `machdep.cpu.extfeatures` (used in `get_cpu_features`) are not supported, triggers `sysctl: unknown oid` error

**Comment by terjekv** [comment]
`powermetrics` gives some useful information, but requires to be run as root..
````
namtso:~ root# powermetrics -n1 -ftext | grep frequen
E-Cluster HW active frequency: 1797 MHz
CPU 0 frequency: 1826 MHz
CPU 1 frequency: 1825 MHz
P0-Cluster HW active frequency: 902 MHz
CPU 2 frequency: 1070 MHz
CPU 3 frequency: 1042 MHz
CPU 4 frequency: 1032 MHz
CPU 5 frequency: 1030 MHz
P1-Cluster HW active frequency: 714 MHz
CPU 6 frequency: 1037 MHz
CPU 7 frequency: 998 MHz
CPU 8 frequency: 1009 MHz
CPU 9 frequency: 1020 MHz
GPU active frequency: 72 MHz
GPU requested frequency: (389 MHz:  15% 486 MHz: .86% 648 MHz: .52% 778 MHz: .52% 972 MHz: .20% 1296 MHz: .09%)

````
