### ISSUE TITLE
[Edgecase] --recursive not respected when added later

### ISSUE THREAD

**Issue by robogast** [easybuilders/easybuild-framework#4037]
Donwloaded `.tar.gz`'s are not re-verified, even under changing configurations:
I initially forgot to add `recursive: True` to the `git_config` of my easyconfig, but was surprised to find empty submodules after adding the flag.
It took me quite some time and digging in the `easyconfig-framework` codebase to figure out the `git clone  --recursive <repo>` command was skipped every time due to the `.tar.gz` already being downloaded, thus re-using a `.tar.gz` without submodules being initialized.

Two suggestions:
- Improve logging:
  the reason I couldn't find anything in my logs is that I was looking for some sort of `git` command or logging info.
  Instead, the message is `INFO Found file <x>.tar.gz`. I would suggest additionally logging which (first time executed) step is skipped in favor of re-using the already downloaded file. E.g.: `logger.INFO(f"{skipped_download_step} skipped since {file}.tar.gz is already found")` --> `INFO git clone skipped since <x>.tar.gz is already found`
- Check that the to-be re-used file is the same given the current configuration. I wouldn't know how this could be implemented except by downloading the file again and checking the hash (thus rendering the check useless), but maybe you know a smarter solution :)

**Comment by boegel** [comment]
This looks like a duplicate of the recently opened issue #4002, is that right @robogast?

**Comment by robogast** [comment]
Ah, that issue is exactly the same as I'm describing here; I'll close this issue then :)
