### ISSUE TITLE
EasyBuild 4.6.0 not building on beegfs

### ISSUE THREAD

**Issue by rungitta** [easybuilders/easybuild-framework#4060]
Just ran into this issue while installing latest `4.6.0` EasytBuild on all our clusters. The cluster who has beegfs as filesystem cannot untar the tarfile since it doesn't support hard links. The issue was quickly resolved by building in `/tmp` instead but after looking closer at the source it seems like the tarfile here (which you get when using `--install-latest-eb-release`:
https://files.pythonhosted.org/packages/e8/e4/16246c2e65b477eca58a9c3e55a86822d9e1846cd38eef0d316e09f2888e/easybuild-framework-4.6.0.tar.gz
is not the same as this one here:
https://github.com/easybuilders/easybuild-framework/archive/refs/tags/easybuild-framework-v4.6.0.tar.gz
The second one has a symlink:
```bash
$ ls -la easybuild-framework-easybuild-framework-v4.6.0/test/framework/sandbox/sources |grep alt
lrwxrwxrwx. 1 user user   3 Jul  8 08:11 alt_toy -> toy
```
Where as in the first one, the content of alt_toy has been converted into a hardlinks.

Error message from log:
```bash
easybuild-framework-4.6.0/test/framework/sandbox/sources/toy/extensions/bar-0.0.tar.gz
tar: easybuild-framework-4.6.0/test/framework/sandbox/sources/toy/extensions/bar-0.0.tar.gz: Cannot hard link to `easybuild-framework-4.6.0/test/framework/sandbox/sources/alt_toy/extensions/bar-0.0.tar.gz': Operation not permitted
```

**Comment by boegel** [comment]
Hmm, we're not using hard links deliberately, this is probably done when we create the source tarballs that are uploaded to `PyPI` which is done with `python3 setup.py sdist`... (see [create_source_tarball.sh](https://github.com/easybuilders/easybuild/blob/develop/scripts/create_source_tarball.sh))

**Comment by ocaisa** [comment]
Eek, I introduced the `alt_toy` symlink without a second thought.
