### ISSUE TITLE
downloads fail, is there no caching?

### ISSUE THREAD

**Issue by codepaster** [easybuilders/easybuild-framework#4140]
I use both Easybuild and Spack and I like EB better because it is better integrated with lmod, builds faster binaries and is overall more deterministic. However Easybuild fails me completely on reproducibility because only 70-75% of the packages can be successfully built and the overwhelming reason is failed downloads from the internet (my locations are US Florida, Northern California and Oregon. Since Spack has implemented the cloud cache the likelihood of successfully installing a package is probably close to 99%. 

Note these issues are unrelated to the lack of resilient downloads that I reported in #4139

Worse, on our EB sites, when a package build fails our sysadmins are not loading the nice EB toolchains prior to building something by hand because they cannot edit all the dependencies into the lua files and are now often building old school. 
To address that we had to give them some tool so they could leverage the toolchains. That tool writes a lua module file and adds all currently loaded modules as a dependency. This is a bad hack (see below)

Can't there be a content distribution network to cache the source code? I get that this costs money but is there not one cloud provider that could sponsor this?  Or is this like $10 / month on Wasabi? 

```
#!/usr/bin/python3
#
# Generate a Easybuild compatible LMod lua module for applications that
# are not installed "old school" without using Easybuild 
# 
# It writes all currently loaded LMod modules as dependencies into the lua module
# which allows Administrators untrained in creating Easybuild packages to use 
# Easybuild toolchains and dependencies to offer software to their users. 
#
#import site; site.addsitedir('/app/lib/python3.6.8/lib/python3.6/site-packages/')
import sys, os, subprocess


MOD_ROOT='/app/other/modules'

if len(sys.argv) < 2:
  print (' Please load the modules needed, switch to the root directory '
         'of the new application and enter the desired application ' 
         'name (without spaces) as first command argument and the '
         '(optional) version as second argument when you run "%s"\n' % 
         os.path.basename(sys.argv[0]))
  print(" Example: %s SAMTools 1.15" % os.path.basename(sys.argv[0]))
  sys.exit(1)

currdir = os.getcwd()
active_mods=subprocess.check_output('ml --terse list', shell=True,
     stderr=subprocess.STDOUT, universal_newlines=True).split('\n')
if active_mods[0]=='No modules loaded':
   active_mods=[]

appname = sys.argv[1]
appver =  os.path.basename(currdir)
if len(sys.argv) >= 3:
  appver = sys.argv[2]

bindir = os.path.join(currdir,'bin')
libdir = os.path.join(currdir,'lib')
if not os.path.isdir(os.path.join(MOD_ROOT,appname)):
  os.makedirs(os.path.join(MOD_ROOT,appname))
luafile = os.path.join(MOD_ROOT,appname,appver+'.lua')

with open(luafile, 'w') as f:
  f.write('local root = "%s"\n' % currdir)
  f.write('conflict("%s")\n' % appname)
  for m in active_mods:
    f.write('if not ( isloaded("%s") ) then\n' % m.strip())
    f.write('    load("%s")\n' % m.strip())
    f.write('end\n\n')
  if os.path.isdir(bindir):
    f.write('prepend_path("PATH", pathJoin(root, "bin"))\n')
  else:
    f.write('prepend_path("PATH", root)\n')
  if os.path.isdir(libdir):
    f.write('prepend_path("LIBRARY_PATH", pathJoin(root, "lib"))\n')
    f.write('prepend_path("LD_LIBRARY_PATH", pathJoin(root, "lib"))\n')

print('\n *** Added currently loaded modules as dependency ***')
os.system('ml --terse list')
print('\n Module "%s" version "%s" written to %s' % (appname,appver,luafile))
print('\n Try running "ml %s" or "ml %s/%s"\n' % (appname,appname,appver))
```

**Comment by ocaisa** [comment]
As mentioned in https://github.com/easybuilders/easybuild-framework/issues/4139#issuecomment-1346498139, you can set up local caching for your organisation by appropriately configuring `--sourcepath` and populating a shared location (with `--fetch` for example)

**Comment by codepaster** [comment]
Thank you, I'll wait for the cache as part of EESSI and it is good to know that it will support build from source and not just binaries shared via cernvm-fs
