### ISSUE TITLE
Regression with versionsuffix types

### ISSUE THREAD

**Issue by mboisson** [easybuilders/easybuild-framework#4281]
Commit https://github.com/easybuilders/easybuild-framework/commit/0e5ba5c858
introduced a check for string-type for `versionsuffix`, while `None` used to be an accepted value for `versionsuffix`. Our hooks replace many version suffixes with `None`.

**Comment by Flamefire** [comment]
Interestingly every falsy value was accepted. So next to empty string and `None` also `False` or an empty list.
I don't see how anything but string and `None` make sense here

So might be ok to break a potential abuse and only allow `None` next to the string type

**Comment by mboisson** [comment]
In the immediate, I will just hot-fix our copy of framework to remove that check (or allow None)
