### ISSUE TITLE
Implement hook to run after easyconfigs are parsed but before the build starts

### ISSUE THREAD

**Issue by XavierCS-dev** [easybuilders/easybuild-framework#4303]
A hook that is run which is passed all of the easyconfigs would be very helpful. It would be passed a copy of `ordered_ecs`, so it can extract information from it.

The hook would then use the knowledge about all the easyconfigs to be built for various operations such as notifying external tools about the number of easyconfigs, and what they are, which could even be used to estimate build time.

I plan to implement this feature myself

**Comment by XavierCS-dev** [comment]
I am struggling to think of a name for such a hook, how do you feel about "poised hook"?

**Comment by boegel** [comment]
I like this idea of this extra hook, but I'm not sure whether "poised" is a good name for it...

At least to me (as a non-native English speaker), the term is meaningless to me.
And looking up the term doesn't help me much (see https://www.merriam-webster.com/dictionary/poised for example).

In addition, there should be a `pre` *and* `post` variant of this hook imho: the `pre` being triggered right before EasyBuild starts looping over the installations to perform, the `post` being triggered right after (small difference with the `end` hook), but in the `build_and_install_software` function?

I'm also struggling to find a good name, but how about `pre_iter` and `post_iter` (before/after iterating over all installations to perform)?
Or maybe `pre_loop` and `post_loop`?

**Comment by branfosj** [comment]
We've decided on `pre_build_and_install_loop` and `post_build_and_install_loop`.
