### ISSUE TITLE
(re)Design of make_extension_string & friends

### ISSUE THREAD

**Issue by wpoely86** [easybuilders/easybuild-framework#4340]
As pointed out in #4331 there is a bit of a weird design around the functions `make_extension_string` and its use in `_generate_extensions_list` in `module_generator.py` from #3697. The list of extensions is built (tuples of name/version), put in a list, joined to a string and then split again into a list. It can't be fixed without change the API and might break somebodies EasyBlock (no EasyBlock in the repo or in a PR touches this code right now).

It would be cleaner to keep it as a list and only convert to a string when it's really needed.

**Comment by wpoely86** [comment]
From @Flamefire:

> I can't remember the exact reasons from back then but yes it seems make_extension_string isn't really needed.
> However we use the functionality in 2 places: EBEXTSLIST and modulegenerator::_generate_extension_list and maybe we anticipated that more things might use it.
> 
> BTW: _generate_extension_list vs _generate_extensions_list in module generator is also...confusing

**Comment by Flamefire** [comment]
I think this is fully adressed with #4690?

**Comment by lexming** [comment]
PR #4690 merged, closing.
