### ISSUE TITLE
GitHub tests fail in CI because we're hitting GitHub API rate limit

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#4372]
Since the changes proposed in #4192 by @Flamefire have been merged, we're more frequently seeing failing GitHub-related tests in the `develop` branch (when a GitHub token is available that can be used to run the GitHub tests).

We'll need to revisit the configuration, to only install the available GitHub token is less configurations, for example only when testing with `Lua` as module syntax, and maybe even only for selected Python versions (only for Python 3.6, default in RHEL8-based OSs, and Python 3.9, default for RHEL9-based OSs).

**Comment by boegel** [comment]
I had to bypass the branch protection to get https://github.com/easybuilders/easybuild-framework/pull/4370 merged when releasing EasyBuild v4.8.2 because of this, it's especially a pain when releasing EasyBuild...

**Comment by Flamefire** [comment]
Ouch, that is a bummer: By avoiding one kind of rate limit we run into another. Maybe the step to install the token should be removed entirely and the token only installed for specific jobs (e.g. in the `include` part define a `use_token: True` for some jobs similar to `modules_tool: xxx`) and as you suggested only when running the LUA part of the loop at https://github.com/easybuilders/easybuild-framework/pull/4192/files#diff-c91058a32040621ac54d6ea4194b302a420b7849f6e8561920d23a0e97acf69aR175

I guess we have to switch the order (first Tcl then Lua) or remove the token afterwards

**Comment by boegel** [comment]
Indeed, that would make sense.
Tcl first is probably way easier than removing the token.
