### ISSUE TITLE
GNU_SOURCE (https://ftpmirror.gnu.org/gnu/) downloads failing

### ISSUE THREAD

**Issue by branfosj** [easybuilders/easybuild-framework#4382]
https://ftpmirror.gnu.org/gnu/ is not working. So, any easyconfig using [`GNU_SOURCE`](https://github.com/easybuilders/easybuild-framework/blob/ea8433dcf5e6edea3e72ad9bd9e23023ecc6b228/easybuild/framework/easyconfig/templates.py#L130) is currently failing on fetching the source.

Workaround is to download from https://ftp.gnu.org/gnu/ instead (or one of the other mirrors: https://www.gnu.org/prep/ftp.en.html).

**Comment by branfosj** [comment]
For current develop https://github.com/easybuilders/easybuild-easyconfigs

```bash
$ grep GNU_SOURCE */*/*.eb | wc -l
874
```

**Comment by branfosj** [comment]
It is working again now.

**Comment by boegel** [comment]
This is popping up again, `ftpmirror.gnu.org` has been having issue for several days now...

I started looking into a workaround for this in:
- https://github.com/easybuilders/easybuild-framework/pull/5224

**Comment by boegel** [comment]
Workaround merged, to be included with next EasyBuild release, so closing this (I don't really see what else we can do with reasonable effort)
