### ISSUE TITLE
Change default value for module-depends-on to True

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-framework#4397]
Many are already doing this, it's just better than the if-not-loaded-then-load workarounds you get otherwise.
I would also hope this would allow Lmod to better handle some bugs that can occur when trying to incorrectly load conflicting modules (which it would no way chance at handling correctly when using the if-not-loaded syntax). Admittedly, last i tried it didn't actually help, but this syntax at least would offer a chance as it would store the actual dependency information in the modules, allowing for a full graph to be built.

**Comment by boegel** [comment]
fixed in #4500
