### ISSUE TITLE
Honor dependency order when (re)building multiple ECs

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-framework#4404]
When eb is instructed to (re)build multiple ECs it should first resolve the dependencies and build the dependencies before the dependents.

Currently it builds them in the order passed and especially for PRs this is bad as it builds them basically in alphabetical order. This causes trouble for PRs when e.g. an EC was updated to fix a bug that did not led to a build failure and the EC was installed before but now rebuild after the EC that uses it.    
For regular builds this is an issue as passing all required ECs with potential rebuilds will now also rebuild an EC after the one that uses it.

Resolving the dependency relations manually is not feasible and EB has that information, so it should be used! At least when e.g. `--robot` is used.

**Comment by boegel** [comment]
Do you have an example where order is not correct?

Because EasyBuild already should already be building things in the correct order (but only when `--robot` is used)...

**Comment by Flamefire** [comment]
I noticed this with https://github.com/easybuilders/easybuild-easyconfigs/pull/19087 where `eb --from-pr 19087 --rebuild -r` (re)builds Z3 after PyTorch
And IIRC when I tried it manually (`eb PyTorch-...eb Z3-...eb -r --rebuild`) it did the same: Z3 last. But might need to re-verify this.

**Comment by branfosj** [comment]
And similarly when no order is specified - e.g. in a PR build report.

Command `eb --from-pr 19086 -Tur --rebuild` but [a build order](https://gist.github.com/branfosj/b3394aa92df096d10e16542fcc22f673) of

* PyTorch-2.1.0-foss-2022a.eb 
* Z3-4.12.2-GCCcore-12.2.0-Python-3.10.8.eb

**Comment by Flamefire** [comment]
Actually I think this was only a confusion on my side: 19086 contained indeed `Z3-4.12.2-GCCcore-12.2.0-Python-3.10.8.eb` but `PyTorch-2.1.0-foss-2022a.eb` doesn't depend on it: foss2022a is GCC 11.3 so I wrongly uploaded that EC there and [removed it already](https://github.com/easybuilders/easybuild-easyconfigs/pull/19086/commits/0bbfac9c65b4a39fd068df75dce3fa88a283068b).

Testing with `eb --from-pr 19087 --rebuild -r` or `eb PyTorch-2.1.0-foss-2022a.eb Z3-4.10.2-GCCcore-11.3.0-Python-3.10.4.eb --rebuild -r` does indeed honor the dependency order.

Hence all looks good, sorry for the confusion
