### ISSUE TITLE
More granular `eb` exit codes (return codes)

### ISSUE THREAD

**Issue by dirkpetersen** [easybuilders/easybuild-framework#4426]
EB mostly returns 1 as an exit code if a build fails. It will return the exit code of the application it is attempting to build. If there are errors that are not related to the actual application build it would be very beneficial to have more granular exit codes for these condititions. 

- cannot find source tar (and no download url available) 
- transient connection error when downloading source tar 
- 404 error - source tar not found
- os-dependency not available  
- error in build dependency 
- dependency not installed 

There may be some other errors states that are worth catching ?

**Comment by dirkpetersen** [comment]
from Boegel on Slack:

We currently typically use raise EasyBuildError, which is then caught in main.py where the exit is done (via print_error); see bottom of https://github.com/easybuilders/easybuild-framework/blob/develop/easybuild/main.py
To allow for custom exit code, we probably need to add an exit_code field to EasyBuildError, which can be passed down to print_error.
Things have changed a bit there in preparation for EasyBuild 5.0, see the 5.0.x branch (see main_with_hooks function in https://github.com/easybuilders/easybuild-framework/blob/5.0.x/easybuild/main.py).  I would target the 5.0.x branch

**Comment by draentropia** [comment]
@boegel can you assign this ticket to me, please?

**Comment by boegel** [comment]
> @boegel can you assign this ticket to me, please?

Sure, thanks!

**Comment by lexming** [comment]
Fixed by https://github.com/easybuilders/easybuild-framework/pull/4534 which will be part of the future EasyBuild v5.0 release.
