### ISSUE TITLE
Post-installation hooks

### ISSUE THREAD

**Issue by itkovian** [easybuilders/easybuild-framework#443]
It should be possible to have custom post-installation hooks, for example, to register the installed software elsewhere than with the modules. 

While registering a new module for the newly installed software packages is indispensable, sites may have a database or other repository where the installed modules are stored to interface with, e.g., a web application where user can register and log projects or requirements for jobs they wish to run. There are multiple options to keep such a registry up to date:
    - have a cron job interrogate the modules on the various clusters and sync them with the central DB (this adds a new data flow in the system, which may be undesirable. also, this data flow should be monitored to make sure everything keeps working)
    - manually add the software after each installation task (error prone)
    - add a hook so admins can register a set of tasks to be conducted when easybuild installs software. 

The latter has the advantage that the admin will see the hook fail (or should see it), and thus can intervene right away. Also, if the hook works properly, no extra dataflow is needed and no extra manual labour is spent on registering this.

**Comment by fgeorgatos** [comment]
For the record, implementing this would have the extra advantage of being able to call judiciously:
`touch $HOME/.lmod.d/.cache/invalidated`. 
That would imply that the Lmod cache gets to become invalid exactly when it needs to, so that users do not get surprised by missing modulefiles.

**Comment by fgeorgatos** [comment]
btw. 
previous trick with `invalidated` dropfile would work with a recent Lmod (fi. 6.6 has the feature included)

**Comment by fgeorgatos** [comment]
Also, the more generic approach on this issue would be:

```
pon each step invocation of EB, either before or after, an external hook can be invoked -exporting useful environmental information- so that extensions can be written, at will, in any language.
```

Eh, where is the PR?!? :-p

**Comment by akesandgren** [comment]
Would the now implemented hook feature solve this completely?
https://easybuild.readthedocs.io/en/latest/Hooks.html

**Comment by boegel** [comment]
@akesandgren Yes imho, so closing, thanks for picking this up.
