### ISSUE TITLE
`run_shell_cmd` hooks should be applied earlier

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-framework#4490]
The hooks for run_shell_cmd
https://github.com/easybuilders/easybuild-framework/blob/24a0f8a396d1e2b414ac8b1a579e8e0b5f0fe3db/easybuild/tools/run.py#L311-L317
are applied just before we run the subprocess, but after all of logging, dry-run etc. `cmd_str` (before hooks) is used in a bunch of places. 

I would argue it should be done as early as possible, since it would reflect the true command being run.

**Comment by boegel** [comment]
@Micket This is fixed by #4544, so can be closed?

**Comment by Micket** [comment]
I thought "fixes ..." would make github auto-close this as fixed.
