### ISSUE TITLE
Default value of `XDG_CONFIG_DIRS` should be `/etc/xdg`, not `/etc`

### ISSUE THREAD

**Issue by runiq** [easybuilders/easybuild-framework#4581]
The XDG basedir spec [says](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables) that the fallback value of `XDG_CONFIG_DIRS` should be `/etc/xdg`, not `/etc`:

> If `$XDG_CONFIG_DIRS` is either not set or empty, a value equal to /etc/xdg should be used. 

I would have submitted a PR instead, but simply changing the default config location would probably break a *lot* of setups in the wild, so I decided to create an issue for deliberation.

What do?

**Comment by bartoldeman** [comment]
Fixed by #4591
