### ISSUE TITLE
Deprecate `post_install_step`, rename it to `post_processing_step`

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-framework#4656]
When trying to create a `post_install_hook` for CUDA, I noticed that the easyblock already has a `post_install_step` that I didn't want to interfere with. The next opportunity to apply the hook was unclear and in fact is `post_postproc_hook`, which would be much clearer if the `post_install_step` had the more accurate name `post_processing_step` (I'm paraphrasing @boegel from Slack here, so he can correct me if I misrepresent the discussion)

**Comment by boegel** [comment]
@bartoldeman Can you take a look at this one?
