### ISSUE TITLE
provide a --download-only command line option

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#538]
Feature request by @georgets:

Provide a `--download-only` command line options that attempts to download all sources for a set of easyconfig files (and doesn't stop on the first failure).

**Comment by bmcgough** [comment]
+1 - with the increasingly large monolithic builds that we are doing for R and Python, failing a download is much more common than it should be. We are beginning to cache source downloads so we don't rely on PyPi, CRAN, or Bioconductor as none of them have 100% uptime.

**Comment by scroogie** [comment]
+1 from me. This would also be helpful for use with --job, for clusters which don't have internet connectivity on the worker nodes.

**Comment by boegel** [comment]
Support for `--fetch` was added in #2457 (EasyBuild v3.6.0)
