### ISSUE TITLE
allow setting post message from easyconfig file

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#542]
In some cases, it would be interesting to allow setting the post message that is printed at the end of the installation process in the easyconfig file, e.g. for issuing warnings in case like `bbcp` which requires certain ports to be open for it to work properly.

The `easyblock` module already supports this via the `self.postmsg` class variable.

**Comment by Falkor** [comment]
+1 :)

**Comment by boegel** [comment]
@Falkor What's the use case you have in mind?

**Comment by Falkor** [comment]
I just updated the easybuild recipes for [Likwid](https://github.com/RRZE-HPC/likwid) that relies on the `likwid-accessD` daemon (built under `$EBROOTLIKWID/sbin`) to forwards the read and write requests to the MSR registers with higher priviledges as per [power] checks -- you will soon have the merge requests. 

There are 3 ways to do that (setuid / setgid or libcap methods), only the first one actually works, but in all cases it would be worth to give the [sudo] commands to perform to the user.
So far, if I can only add some messages as part of the `postinstallcmds`, typically as follows: 

```python
postinstallcmds = [
    'echo "IMPORTANT: you will have to manually apply the following changes **as root**:"',
    'echo "  sudo chown root:root \$EBROOTLIKWID/sbin/likwid-accessD && sudo chmod u+s \$EBROOTLIKWID/sbin/likwid-accessD"']
```
but that hides it in the build logs as they are not exposed to the user on the regular `eb` process. 
In this case, having the possibility to provide post messages would be grateful.

**Comment by boegel** [comment]
@victorusu was looking for suggestions for contributions, maybe this is an easy one to tackle...
