### ISSUE TITLE
User Runtime != User Compiler time != EB compile time.

### ISSUE THREAD

**Issue by spikebike** [easybuilders/easybuild-framework#680]
First a couple high level goals that are hopefully easy to agree on:
- Easybuild should be as simple as possible
- Users should not have to be aware of EB to be able to build their own source code in their own home directory
- EB should eat it's dog food, if users are expected to compile in an env modules managed environment, so should EB.
- EB should not internally replicate the functionality of environment modules.
- Compile time environment should be identical to runtime environment, any difference  is a bug.

Before EB I maintained a large complex environment modules environment.  So if a user needed to build some source code against HDF they would say something like:

```
$ module load gcc szip hdf
```

Then CPATH (to find include files), LIBRARY_PATH (to find libraries at compile time), and LD_LIBRARY_PATH (to run runtime libraries) were set.

So the user could say:

```
$ module load gcc szip hdf
$ gcc foo.c -o foo -l szip -lhdf
```

To run the resulting binary:

```
$ module load gcc szip hdf
$ ./foo
```

Easybuild seems to have a rather large complex set of environment variables for internal use.  So from that I can tell the above would be necessary:

```
$ module load gcc szip hdf
$ gcc foo.c -o foo -L$EBROOTHDF/lib -L$EBROOTSZIP/lib -lszip -lhdf
(i'm likely missing other libs as well, zlib, gcc, etc.)
```

Note how I don't need a bunch of -I commands.  That's because $CPATH is set.
The runtime is also managed by EB, so I don't need to manually tinker with LD_LIBRARY_PATH either.  This is good thing, strange that it doesn't include $LIBRARY_PATH.  Currently half of the compile time environment is set, but 100% of the runtime.

So basically EB is managing 2/3rd of the environment variables to enable a nice clean compile time and run time.  By managing LIBRARY_PATH (which should be IDENTICAL to LD_LIBRARY_PATH) we get a nice clean compile time and run time.

Additionally EB should use this identical compile time environment to compile EB packages.  Why manage EBROOTBISON, EBROOTFFTW, EBROOTFLEX, EBROOTGCC,EBROOTGOMPI,  EBROOTGOOLF etc. When environment modules, 
LIBRARY_PATH, LD_LIBRARY_PATH, and CPATH already do this for you?

I saw this document:
https://github.com/ULHPC/UserDoc/blob/master/incoming/HowToBuildAgainstLibrariesMadeViaEasyBuild.md

Why manage CPPFLAGS, _LMFILES_,  EBVARCPPFLAGS, LDFLAGS, EBVARLDFLAGS, etc.  Just having EB manage CPATH and LIBRARY_PATH will handle all of this automatically and much cleaner.  

There shouldn't need to be a document on how to build on libraries made by easybuild, it should be transparent and identical to the way easybuild builds against easybuild.

Building abyss in my home directory should require:

```
$ module load <dependencies>
$ ./Configure ...
$ make.
```

The only difference for an EB build of abyss should be the EB file that lists the dependencies, configure options, and does a build using the same $CPATH, $LIBRARY_PATH, and $LD_LIBRARY_PATH.

Runtime for abyss of course should require the same module load and get the same 
$CPATH, $LIBRARY_PATH, and $LD_LIBRARY_PATH.

Am I missing something?

**Comment by Micket** [comment]
So these days, pkg-config paths, cmake paths, CPATH, LIBRARY_PATH and whatever else might exist that affect the classic "compile time" environment.
The `buildenv` modules adds the last step, and basically provides the environment from the toolchain just about exactly the same EB sees it.

We of course can't do any magic when it comes to any custom easyblocks, and a lot of configure tools and whatnot out there don't respect these variables like they should, and still requires massaging (thus the custom easyblocks) to actually build. But I think it's very safe to say this is as solved as it can get.
