### ISSUE TITLE
make robot consider archived easyconfigs (ebfiles_repo)

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#722]
The robot should also take into account the folder with archived easyconfigs when searching for easyconfig files that match the given specifications.
The archive folder should probably also take precedence over other sources of easyconfig files, since site customizations made by hand would be preserved then.

**Comment by bartoldeman** [comment]
This is closed but I could not make it work with a GitRepository, unless I refer to a checkout and make sure to do a git pull before issuing an eb command.

Would it be possible to get the robot to refer to eb files installed under software too, e.g.:
$EASYBUILD_PREFIX/software/EasyBuild/2.2.0/easybuild/EasyBuild-2.2.0.eb
that would work no matter what repository style is used right?

**Comment by bartoldeman** [comment]
Nevermind, I think a git post-receive hook will do the job too.

**Comment by boegel** [comment]
The GitRepository is a bare repository, and EasyBuild simply checks for files, it doesn't query the repo via `git`. But maybe it should?

Can you open a new issue for this, to make sure that EasyBuild can search through a `GitRepository`? We can probably fix this...
