### ISSUE TITLE
feature request, to only generate modules with EB

### ISSUE THREAD

**Issue by olavks** [easybuilders/easybuild-framework#998]
There is allready a --stop option,l this could be, but you cannot currently use this to _only_ generate modules.
combining --stop with --start or a special option only for modules.

**Comment by boegel** [comment]
`--module-only` has been supported since EasyBuild v1.16, see also http://easybuild.readthedocs.io/en/latest/Partial_installations.html#only-re-generating-additional-module-files-using-module-only
